const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path');
const base=process.env.UI_BASE||'http://127.0.0.1:8110',out=process.env.UI_OUT||'benchmarks/ui-refinement';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true,executablePath:'C:/Users/Administrator/AppData/Local/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-win64/chrome-headless-shell.exe'});const findings=[],errors=[];try{const p=await b.newPage({viewport:{width:1366,height:768}});p.on('pageerror',e=>errors.push(e.message));const check=(name,pass,detail)=>findings.push({name,pass,detail});
 await p.goto(base+'/growth/');await p.waitForSelector('#starter button:enabled');await p.waitForSelector('canvas');await p.waitForTimeout(400);
 for(const selector of ['[data-open-panel="panel-travel"]','.player-dock']){const box=await p.locator(selector).first().boundingBox();check('desktop visible '+selector,box.y>=0&&box.y+box.height<=768,box);}
 const ratio=await p.evaluate(()=>{const h=document.querySelector('#map').getBoundingClientRect(),c=document.querySelector('canvas').getBoundingClientRect();return c.height/h.height;});check('desktop canvas fills available height',ratio>.9,ratio);check('no premature wild instruction',!(await p.locator('#target-empty').textContent()).includes('点击地图上的野生'),await p.locator('#target-empty').textContent());await p.screenshot({path:path.join(out,'growth-desktop.png'),fullPage:true});
 await p.setViewportSize({width:390,height:844});await p.waitForTimeout(700);const layout=await p.evaluate(()=>{const h=document.querySelector('#map').getBoundingClientRect(),c=document.querySelector('canvas').getBoundingClientRect(),d=document.querySelector('.player-dock').getBoundingClientRect(),nav=document.querySelector('[data-open-panel="panel-travel"]').getBoundingClientRect();return{host:{x:h.x,y:h.y,right:h.right,bottom:h.bottom},canvas:{x:c.x,y:c.y,right:c.right,bottom:c.bottom},dock:d.y,navBottom:nav.bottom,scrollWidth:document.documentElement.scrollWidth};});check('mobile canvas contained',layout.canvas.x>=layout.host.x-1&&layout.canvas.right<=layout.host.right+1&&layout.canvas.bottom<=layout.host.bottom+1,layout);check('mobile camera is square',Math.abs((layout.canvas.right-layout.canvas.x)-(layout.canvas.bottom-layout.canvas.y))<2,layout);check('mobile navigation above dock',layout.navBottom<=layout.dock,layout);check('mobile no overflow',layout.scrollWidth<=390,layout);await p.screenshot({path:path.join(out,'growth-mobile.png'),fullPage:true});
 await p.setViewportSize({width:1366,height:768});await p.goto(base+'/evaluation/');await p.waitForSelector('#create:enabled');const submit=await p.locator('#create').boundingBox();check('evaluation submit visible',submit.y>=0&&submit.y+submit.height<=768,submit);
 await p.goto(base+'/duel/');await p.waitForSelector('#start:enabled');check('empty arena hidden before battle',!(await p.locator('.arena').isVisible()),{});await p.selectOption('#difficulty','rookie');await p.click('#start');check('invalid selection error visible',await p.locator('#notice').isVisible(),await p.locator('#notice').textContent());await p.selectOption('#difficulty','standard');check('battle configuration change clears obsolete validation',!(await p.locator('#notice').textContent()),{});await p.goto(base+'/quest/');await p.waitForSelector('canvas');check('quest guide initially collapsed',!(await p.locator('#journey-host details').evaluate(e=>e.open)),{});
 await p.locator('.task-secondary summary').click();check('quest partner selection accessible',await p.locator('#ai-partner').isVisible(),{});await p.locator('.player-mode-menu summary').click();await p.keyboard.press('Escape');check('focused menu closes on Escape',!(await p.locator('.player-mode-menu').evaluate(e=>e.open)),{});check('browser errors',errors.length===0,errors);fs.writeFileSync(path.join(out,'acceptance.json'),JSON.stringify({base,findings,errors,paidCalls:0},null,2));console.log(JSON.stringify(findings));if(findings.some(f=>!f.pass))process.exitCode=1;
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
