package game.agent.growth;
import game.agent.action.ActionResult;import game.agent.llm.Json;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class GrowthTest {
 private static GrowthPokemon mon(String species,int level){return new GrowthPokemon(UUID.randomUUID().toString(),species,level);}
 private static void go(GrowthWorld w,String region){for(int i=0;i<60&&!w.region().equals(region);i++){ActionResult r=w.execute("go_to_region",Json.object("regionId",region));assertNotEquals(ActionResult.Status.REJECTED,r.getStatus(),r.getCode());}assertEquals(region,w.region());}
 private static void approach(GrowthWorld w,String id){for(int i=0;i<60;i++){ActionResult r=w.execute("move_to",Json.object("targetId",id));assertNotEquals(ActionResult.Status.REJECTED,r.getStatus(),r.getCode());if(r.getStatus()==ActionResult.Status.SUCCESS)return;}fail("No native path");}
 @Test void referenceExperienceAndStats(){assertEquals(135,GrowthRules.experienceAt(5));assertEquals(2535,GrowthRules.experienceAt(16));assertEquals(5460,GrowthRules.experienceAt(20));assertArrayEquals(new int[]{20,12,10,10,10,9},GrowthRules.stats("MUDKIP",5));assertEquals(4,GrowthRules.typeMultiplier("GRASS",new String[]{"WATER","GROUND"}));assertEquals(.5,GrowthRules.typeMultiplier("DARK",new String[]{"FIRE","FIGHTING"}));assertTrue(GrowthRules.special("DARK"));assertFalse(GrowthRules.special("GROUND"));}
 @Test void levelEvolutionPreservesIndividualExperienceAndFainting(){GrowthPokemon p=mon("MUDKIP",5);assertEquals("EVOLUTION_LEVEL_REQUIRED",p.evolve());p.hurt(p.maxHp());p.gainExperience(6000);assertEquals(0,p.getHitPoints());p.rest();String id=p.captureId;int exp=p.experience;p.hurt(5);assertEquals("EVOLVED",p.evolve());assertEquals(id,p.captureId);assertEquals(exp,p.experience);assertEquals("MARSHTOMP",p.species);assertTrue(p.getHitPoints()<p.maxHp());assertEquals("EVOLUTION_LEVEL_REQUIRED",p.evolve());}
 @Test void fourMovesRequireExplicitReplacementAndPersistPP(){GrowthPokemon p=mon("TREECKO",16);assertEquals(4,p.pp.size());assertEquals("REPLACE_MOVE_REQUIRED",p.learn("PURSUIT",null));assertEquals("MOVE_LEARNED",p.learn("PURSUIT","LEER"));p.pp.put("PURSUIT",7);GrowthPokemon restored=GrowthPokemon.restore(Json.asObject(Json.read(Json.write(p.export()))));assertEquals(p.captureId,restored.captureId);assertEquals(7,restored.pp.get("PURSUIT"));assertFalse(restored.pp.containsKey("LEER"));assertEquals("EVOLVED",restored.evolve());restored=GrowthPokemon.restore(Json.asObject(Json.read(Json.write(restored.export()))));assertEquals(7,restored.pp.get("PURSUIT"));assertFalse(restored.availableMoves().contains("PURSUIT"));assertEquals("MOVE_LEARNED",restored.learn("FURY_CUTTER","POUND"));}
 @Test void nativeMovementAndManifestCollisionAgreeForEveryTile(){for(String region:GrowthMaps.regions()){edu.monash.fit2099.engine.positions.GameMap map=GrowthMaps.create(region);Map<String,Object> d=GrowthMaps.definition(region);List<Object> collision=Json.asArray(d.get("collision"));int width=GrowthPokemon.num(d.get("width"));GrowthPokemon p=mon("TREECKO",5);for(int y:map.getYRange())for(int x:map.getXRange())assertEquals(GrowthPokemon.num(collision.get(y*width+x))==0,map.at(x,y).canActorEnter(p),region+":"+x+","+y);}}
 @Test void captureUsesNativeOwnershipAndSurvivesFaintedRestore(){GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");go(w,"forest");approach(w,"forest-1-0");assertEquals("GROWTH_CAPTURED",w.execute("capture",Json.object("targetId","forest-1-0")).getCode());int xp=w.partner().experience;assertEquals("TARGET_UNAVAILABLE",w.execute("capture",Json.object("targetId","forest-1-0")).getCode());assertEquals(xp,w.partner().experience);go(w,"lab");Map<String,Object> caught=Json.asObject(Json.asArray(w.view().get("team")).get(1));w.select((String)caught.get("captureId"));w.partner().hurt(w.partner().maxHp());GrowthWorld restored=GrowthWorld.restore(Json.asObject(Json.read(Json.write(w.export()))),()->0);assertEquals(0,restored.partner().getHitPoints());assertEquals("GROWTH_RESTED",restored.rest().getCode());assertEquals("MILESTONE_REWARDED",restored.claim("FIRST_CAPTURE").getCode());int gained=restored.partner().experience;assertEquals("REWARD_ALREADY_CLAIMED",restored.claim("FIRST_CAPTURE").getCode());assertEquals(gained,restored.partner().experience);GrowthWorld.restore(Json.asObject(Json.read(Json.write(restored.export()))),()->0);}
 @Test void actualBattlesAutomaticallyEvolveAt16AndResumeWithoutDuplicateXp(){GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");int turns=0;while(w.partner().level()<16&&turns++<800){go(w,"forest");List<Object> rows=Json.asArray(w.view().get("encounters"));String target=null;for(Object row:rows){Map<String,Object> e=Json.asObject(row);if("WILD".equals(e.get("state"))){target=(String)e.get("id");break;}}if(target==null){go(w,"lab");w.rest();assertEquals("EXPEDITION_READY",w.nextExpedition().getCode());continue;}approach(w,target);String move="TACKLE";for(String id:w.partner().pp.keySet())if(GrowthRules.move(id).power>0&&w.partner().pp.get(id)>0)move=id;ActionResult result=w.execute("use_skill",Json.object("targetId",target,"moveId",move));assertEquals(ActionResult.Status.SUCCESS,result.getStatus(),result.getCode());if(w.partner().getHitPoints()<w.partner().maxHp()/2||w.partner().pp.values().stream().allMatch(n->n==0)){go(w,"lab");w.rest();}w=GrowthWorld.restore(Json.asObject(Json.read(Json.write(w.export()))),()->0);}assertTrue(w.partner().level()>=16);go(w,"lab");w.rest();String id=w.partner().captureId;int xp=w.partner().experience;assertEquals("MARSHTOMP",w.partner().species);GrowthWorld saved=GrowthWorld.restore(Json.asObject(Json.read(Json.write(w.export()))),()->0);assertEquals("MARSHTOMP",saved.partner().species);assertEquals(id,saved.partner().captureId);assertEquals(xp,saved.partner().experience);assertEquals("MOVE_LEARNED",saved.learn("MUD_SHOT","GROWL").getCode());}
 @Test void trainingObservationPredictsUsefulEquippedDamageWithoutMutatingWorld(){GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");w.partner().gainExperience(GrowthRules.experienceAt(10)-w.partner().experience);String before=Json.write(w.export());Map<String,Object> row=Json.asObject(Json.asArray(Json.read(w.observation().get("encounters"))).get(0));Map<String,Object> damage=Json.asObject(row.get("estimatedDamage"));assertTrue(((Number)damage.get("TACKLE")).intValue()>((Number)damage.get("WATER_GUN")).intValue());assertEquals(before,Json.write(w.export()));}
 @Test void aiObservationExcludesResolvedTargetsAndNamesExpeditionPhase(){GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");go(w,"forest");for(int i=0;i<3;i++){String id="forest-1-"+i;approach(w,id);assertEquals("GROWTH_CAPTURED",w.execute("capture",Json.object("targetId",id)).getCode());}assertTrue(Json.asArray(Json.read(w.observation().get("encounters"))).isEmpty());assertEquals("RETURN_FOR_NEW_EXPEDITION",w.observation().get("trainingPhase"));go(w,"lab");assertEquals("PREPARE_NEW_EXPEDITION",w.observation().get("trainingPhase"));}
 @Test void corruptedProfilesAndWorldAreRejected(){GrowthPokemon p=mon("MARSHTOMP",16);Map<String,Object> bad=p.export();bad.put("experience",135);assertThrows(IllegalArgumentException.class,()->GrowthPokemon.restore(bad));GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");Map<String,Object> invalid=w.export();invalid.put("encounters",Collections.emptyList());assertThrows(IllegalArgumentException.class,()->GrowthWorld.restore(invalid,()->0));}
 @Test void aiTrainingCannotCaptureOrMutateEvolution(){GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");assertFalse(w.trainingTools().definitions().stream().anyMatch(d->d.getName().equals("capture")||d.getName().equals("evolve")||d.getName().equals("observe")));assertEquals("UNKNOWN_TOOL",w.trainingTools().execute(new game.agent.tools.ToolRequest("x","capture",Json.object("targetId","forest-1-0"))).getCode());}

 @Test void finalEvolutionThresholdsAndCapAreReferenceBased(){
  assertEquals(40007,GrowthRules.experienceAt(36));assertEquals(56660,GrowthRules.experienceAt(40));
  for(String[] chain:new String[][]{{"TREECKO","GROVYLE","SCEPTILE"},{"MUDKIP","MARSHTOMP","SWAMPERT"},{"TORCHIC","COMBUSKEN","BLAZIKEN"}}){
   GrowthPokemon p=mon(chain[0],16);String id=p.captureId;assertEquals("EVOLVED",p.evolve());assertEquals(chain[1],p.species);
   p.gainExperience(GrowthRules.experienceAt(35)-p.experience);assertEquals("EVOLUTION_LEVEL_REQUIRED",p.evolve());
   p.gainExperience(GrowthRules.experienceAt(36)-p.experience);int exp=p.experience;p.hurt(7);int hp=p.getHitPoints(),max=p.maxHp();
   assertEquals("EVOLVED",p.evolve());assertEquals(chain[2],p.species);assertEquals(id,p.captureId);assertEquals(exp,p.experience);assertEquals((int)((long)hp*p.maxHp()/max),p.getHitPoints());
   p.gainExperience(Integer.MAX_VALUE);assertEquals(40,p.level());assertEquals(56660,p.experience);assertEquals("NO_EVOLUTION",p.evolve());assertEquals(p.experience,p.view().get("nextLevelExperience"));
   assertEquals(chain[2],GrowthPokemon.restore(p.export()).species);
  }
 }
 @Test void retainedMovesTraverseBothEvolutionAncestorsAndRejectEarlyFinalForms(){
  GrowthPokemon p=mon("TREECKO",36);assertEquals("MOVE_LEARNED",p.learn("SLAM","LEER"));p.pp.put("SLAM",8);p.evolve();p.evolve();assertEquals("SCEPTILE",p.species);assertFalse(p.availableMoves().contains("SLAM"));
  GrowthPokemon restored=GrowthPokemon.restore(p.export());assertEquals(8,restored.pp.get("SLAM"));assertEquals(4,restored.pp.size());
  Map<String,Object> corrupt=p.export();corrupt.put("experience",GrowthRules.experienceAt(35));assertThrows(IllegalArgumentException.class,()->GrowthPokemon.restore(corrupt));
  GrowthPokemon fire=mon("COMBUSKEN",39);assertEquals("MOVE_LEARNED",fire.learn("SLASH","GROWL"));fire.evolve();assertFalse(fire.availableMoves().contains("SLASH"));assertTrue(GrowthPokemon.restore(fire.export()).pp.containsKey("SLASH"));
 }
 @Test void lateMovesUnlockAtTheirSpeciesSpecificReferenceLevel(){
  assertFalse(mon("GROVYLE",28).availableMoves().contains("LEAF_BLADE"));assertTrue(mon("GROVYLE",29).availableMoves().contains("LEAF_BLADE"));
  assertTrue(mon("MARSHTOMP",37).availableMoves().contains("MUDDY_WATER"));assertFalse(mon("SWAMPERT",38).availableMoves().contains("MUDDY_WATER"));assertTrue(mon("SWAMPERT",39).availableMoves().contains("MUDDY_WATER"));
  assertEquals(70,GrowthRules.move("LEAF_BLADE").power);assertEquals(95,GrowthRules.move("MUDDY_WATER").power);assertEquals(85,GrowthRules.move("MUDDY_WATER").accuracy);assertEquals(10,GrowthRules.move("BLAZE_KICK").pp);
  assertArrayEquals(new int[]{109,96,60,89,60,68},GrowthRules.stats("BLAZIKEN",36));
 }
 @Test void highCriticalDamageIgnoresUnfavorableStagesButPreservesBurnAndType(){
  GrowthPokemon a=mon("BLAZIKEN",36),d=mon("SWAMPERT",36);GrowthRules.Move move=GrowthRules.move("SLASH");a.attackStage=-6;d.defenseStage=6;
  int normal=GrowthRules.damage(a,d,move,0,move.power),critical=GrowthRules.damage(a,d,move,0,move.power,true);assertTrue(critical>normal*2);
  a.attackStage=0;d.defenseStage=0;assertEquals(critical,GrowthRules.damage(a,d,move,0,move.power,true));a.burned=true;assertTrue(GrowthRules.damage(a,d,move,0,move.power,true)<critical);
 }
 @Test void lateStatusMovesAndRecoilExecuteThroughActualNativeBattle(){
  GrowthWorld w=new GrowthWorld(()->0);w.starter("TORCHIC");w.partner().gainExperience(GrowthRules.experienceAt(28)-w.partner().experience);w.evolve();assertEquals("MOVE_LEARNED",w.learn("BULK_UP","GROWL").getCode());go(w,"forest");approach(w,"forest-1-0");
  assertEquals("SKILL_USED",w.execute("use_skill",Json.object("targetId","forest-1-0","moveId","BULK_UP")).getCode());assertEquals(1,w.partner().attackStage);assertEquals(1,w.partner().defenseStage);assertEquals(19,w.partner().pp.get("BULK_UP"));
  go(w,"lab");w.rest();assertEquals(0,w.partner().attackStage);assertEquals(20,w.partner().pp.get("BULK_UP"));
  GrowthWorld water=new GrowthWorld(()->0);water.starter("MUDKIP");water.partner().gainExperience(GrowthRules.experienceAt(31)-water.partner().experience);water.evolve();assertEquals("MOVE_LEARNED",water.learn("TAKE_DOWN","GROWL").getCode());go(water,"forest");approach(water,"forest-1-0");int hp=water.partner().getHitPoints();
  ActionResult result=water.execute("use_skill",Json.object("targetId","forest-1-0","moveId","TAKE_DOWN"));assertEquals("GROWTH_DEFEATED",result.getCode());assertTrue(water.partner().getHitPoints()<hp);assertEquals(19,water.partner().pp.get("TAKE_DOWN"));
 }
 @Test void highLevelExpeditionsScaleAndFirstEvolutionRewardRemainsOnce(){
  GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");go(w,"forest");for(int i=0;i<3;i++){approach(w,"forest-1-"+i);w.execute("capture",Json.object("targetId","forest-1-"+i));}go(w,"lab");w.partner().gainExperience(GrowthRules.experienceAt(36)-w.partner().experience);w.evolve();assertEquals("MILESTONE_REWARDED",w.claim("FIRST_EVOLUTION").getCode());w.evolve();assertEquals("REWARD_ALREADY_CLAIMED",w.claim("FIRST_EVOLUTION").getCode());w.nextExpedition();List<Object> rows=Json.asArray(w.view().get("encounters"));assertTrue(((Number)Json.asObject(rows.get(0)).get("level")).intValue()>20);GrowthWorld restored=GrowthWorld.restore(w.export(),()->0);assertEquals(w.partner().captureId,restored.partner().captureId);assertEquals("SWAMPERT",restored.partner().species);go(restored,"forest");approach(restored,"forest-2-2");assertEquals(ActionResult.Status.SUCCESS,restored.execute("use_skill",Json.object("targetId","forest-2-2","moveId","WATER_GUN")).getStatus());
 }
}
