package game.agent.growth;
import game.agent.action.ActionResult;
import game.agent.llm.Json;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GrowthExpansionTest {
 private GrowthPokemon mon(String id,int level){return new GrowthPokemon(UUID.randomUUID().toString(),id,level);}
 private GrowthWorld fresh(){GrowthWorld w=new GrowthWorld(()->0);assertEquals("ADVENTURE_STARTED",w.startAdventure().getCode());w.starter("MUDKIP");return w;}
 private void go(GrowthWorld w,String region){for(int n=0;n<160&&!w.region().equals(region);n++)assertNotEquals(ActionResult.Status.REJECTED,w.execute("go_to_region",Json.object("regionId",region)).getStatus());assertEquals(region,w.region());}
 private void approach(GrowthWorld w,String id){for(int n=0;n<90;n++){ActionResult a=w.execute("move_to",Json.object("targetId",id));assertNotEquals(ActionResult.Status.REJECTED,a.getStatus());if(a.getStatus()==ActionResult.Status.SUCCESS)return;}fail("Unreachable encounter");}
 private void clear(GrowthWorld w,String region){go(w,region);for(Object v:new ArrayList<>(Json.asArray(w.view().get("encounters")))){String id=(String)Json.asObject(v).get("id");approach(w,id);assertEquals("GROWTH_CAPTURED",w.execute("capture",Json.object("targetId",id)).getCode());}}
 @Test void allSixLinesEvolveAtExactThresholdAndKeepAncestorMoves(){String[] bases={"POOCHYENA","ZIGZAGOON","TAILLOW","WINGULL","SHROOMISH","ELECTRIKE"};int[] levels={18,20,22,25,23,26};assertEquals(21,GrowthRules.speciesIds().size());for(int i=0;i<bases.length;i++){GrowthPokemon p=mon(bases[i],levels[i]-1);String id=p.captureId;Set<String> moves=new HashSet<>(p.pp.keySet());assertEquals("EVOLUTION_LEVEL_REQUIRED",p.evolve());p.gainExperience(GrowthRules.experienceAt(levels[i])-p.experience);assertEquals("EVOLVED",p.evolve());assertEquals(id,p.captureId);assertTrue(p.pp.keySet().containsAll(moves));assertEquals(Json.write(p.export()),Json.write(GrowthPokemon.restore(p.export()).export()));assertEquals("NO_EVOLUTION",p.evolve());}}
 @Test void campaignUnlocksOnlyAfterResolutionAndRewardsAreOnce(){GrowthWorld w=fresh();String before=Json.write(w.export());assertEquals("REGION_LOCKED",w.execute("go_to_region",Json.object("regionId","river")).getCode());assertEquals(before,Json.write(w.export()));assertEquals("REGION_LOCKED",w.chooseExpedition("mountain").getCode());for(String region:Arrays.asList("forest","river","mountain")){clear(w,region);w=GrowthWorld.restore(w.export(),()->0);go(w,"lab");String reward="ADVENTURE_"+region.toUpperCase(Locale.ROOT);int xp=w.partner().experience;assertEquals("ADVENTURE_REWARDED",w.claim(reward).getCode());assertEquals(xp+GrowthAdventure.reward(reward),w.partner().experience);assertEquals("REWARD_ALREADY_CLAIMED",w.claim(reward).getCode());}assertEquals(true,Json.asObject(w.view().get("adventure")).get("completed"));assertEquals("ADVENTURE_REWARDED",w.claim("DEX_THREE").getCode());assertEquals("REWARD_ALREADY_CLAIMED",w.claim("DEX_THREE").getCode());assertEquals(Json.write(w.export()),Json.write(GrowthWorld.restore(w.export(),()->0).export()));}
 @Test void sixNewBasesAppearOnFirstRouteAndCaptureSurvivesRestore(){GrowthWorld w=fresh();Set<String> caught=new HashSet<>();for(String region:Arrays.asList("forest","river","mountain")){go(w,region);for(Object row:Json.asArray(w.view().get("encounters")))caught.add((String)Json.asObject(row).get("species"));clear(w,region);w=GrowthWorld.restore(w.export(),()->0);}assertTrue(caught.containsAll(Arrays.asList("POOCHYENA","ZIGZAGOON","TAILLOW","WINGULL","SHROOMISH","ELECTRIKE")));assertEquals(10,Json.asArray(w.view().get("team")).size());}
 @Test void legacyProfileDefaultsAndInvalidTraitsReject(){GrowthPokemon p=mon("TREECKO",5);Map<String,Object> old=p.export();old.remove("traits");GrowthPokemon restored=GrowthPokemon.restore(old);assertEquals("HARDY",restored.nature);assertArrayEquals(new int[6],restored.ev);Map<String,Object> bad=p.export();Json.asObject(bad.get("traits")).put("ev",Arrays.asList(255,255,1,0,0,0));Map<String,Object> oldBad=bad;assertThrows(IllegalArgumentException.class,()->GrowthPokemon.restore(oldBad));bad=p.export();Json.asObject(bad.get("traits")).put("status","SLEEP");Map<String,Object> invalid=bad;assertThrows(IllegalArgumentException.class,()->GrowthPokemon.restore(invalid));}
 @Test void oldWorldMigratesWithoutLockingExistingRegions(){GrowthWorld w=new GrowthWorld(()->0);w.starter("TREECKO");go(w,"mountain");Map<String,Object> old=w.export();old.remove("adventure");GrowthWorld restored=GrowthWorld.restore(old,()->0);assertTrue(restored.regionUnlocked("mountain"));assertEquals(w.partner().captureId,restored.partner().captureId);assertEquals("LAB_REQUIRED",restored.startAdventure().getCode());assertEquals(Json.write(restored.export()),Json.write(GrowthWorld.restore(restored.export(),()->0).export()));}
 @Test void natureAndEvUseCorrectRoundingCapsAndPreserveFainting(){GrowthPokemon p=mon("MUDKIP",40);int[] normal=p.stats();p.assignNature("ADAMANT");assertEquals(normal[1]*110/100,p.stats()[1]);assertEquals(normal[3]*90/100,p.stats()[3]);p.hurt(p.maxHp());for(int n=0;n<300;n++)p.awardEv("POOCHYENA");assertEquals(255,p.ev[1]);for(int n=0;n<300;n++)p.awardEv("TAILLOW");assertEquals(255,p.ev[5]);for(int n=0;n<20;n++)p.awardEv("MUDKIP");assertEquals(510,Arrays.stream(p.ev).sum());assertEquals(0,p.getHitPoints());p.rest();assertEquals(p.maxHp(),p.getHitPoints());assertEquals(Json.write(p.export()),Json.write(GrowthPokemon.restore(p.export()).export()));}
 @Test void criticalIncludesOrdinaryMovesAndBurnKeepsItsPenalty(){GrowthPokemon a=mon("MUDKIP",20),d=mon("POOCHYENA",20);GrowthCombat critical=new GrowthCombat(()->0),normal=new GrowthCombat(()->1);GrowthPokemon c=GrowthPokemon.restore(d.export());critical.strike(a,d,GrowthRules.move("TACKLE"));normal.strike(a,c,GrowthRules.move("TACKLE"));assertTrue(d.getHitPoints()<c.getHitPoints());}
 @Test void sleepBlocksTwoActionsWithoutPpConsumptionAndRestCures(){GrowthPokemon a=mon("SHROOMISH",20),d=mon("MUDKIP",20);GrowthCombat battle=new GrowthCombat(()->1);battle.strike(a,d,GrowthRules.move("SLEEP_POWDER"));assertEquals("SLEEP",d.status);int pp=d.pp.get("TACKLE");battle.turn(d,a,"TACKLE");battle.turn(d,a,"TACKLE");assertEquals(pp,d.pp.get("TACKLE"));assertEquals("NONE",d.status);battle.strike(a,d,GrowthRules.move("STUN_SPORE"));assertEquals("PARALYSIS",d.status);d.burned=false;d.rest();assertEquals("NONE",d.status);assertEquals(0,d.sleepTurns);}
 @Test void statusNeverStacksAndGroundImmuneToElectricStatus(){GrowthPokemon a=mon("ELECTRIKE",20),d=mon("MARSHTOMP",20);GrowthCombat b=new GrowthCombat(()->1);b.strike(a,d,GrowthRules.move("THUNDER_WAVE"));assertEquals("NONE",d.status);GrowthPokemon target=mon("MUDKIP",20);b.strike(a,target,GrowthRules.move("THUNDER_WAVE"));b.strike(a,target,GrowthRules.move("SLEEP_POWDER"));assertEquals("PARALYSIS",target.status);assertEquals(0,target.sleepTurns);}
 @Test void poisonResidualAndKeenEyeStaticAbilitiesAreShared(){GrowthCombat b=new GrowthCombat(()->1);GrowthPokemon a=mon("POOCHYENA",20),d=mon("TAILLOW",20);b.strike(a,d,GrowthRules.move("SAND_ATTACK"));assertEquals(0,d.accuracyStage);GrowthPokemon electric=mon("ELECTRIKE",20);b.strike(a,electric,GrowthRules.move("TACKLE"));assertEquals("PARALYSIS",a.status);a.rest();b.strike(a,d,GrowthRules.move("POISON_FANG"));assertEquals("POISON",d.status);int hp=d.getHitPoints();b.residual(a,d);assertEquals(Math.max(0,hp-Math.max(1,d.maxHp()/8)),d.getHitPoints());}
 @Test void lowHpStarterAbilityBoostsMatchingTypeOnly(){GrowthPokemon a=mon("TREECKO",20),d=mon("MUDKIP",20);GrowthRules.Move grass=GrowthRules.move("ABSORB"),normal=GrowthRules.move("POUND");int grassBefore=GrowthRules.damage(a,d,grass,0,grass.power),normalBefore=GrowthRules.damage(a,d,normal,0,normal.power);a.hurt(a.maxHp()-1);assertTrue(GrowthRules.damage(a,d,grass,0,grass.power)>grassBefore);assertEquals(normalBefore,GrowthRules.damage(a,d,normal,0,normal.power));}
 @Test void genThreeTypeCoverageIncludesSteelResistingDarkGhostAndDoubleWeakness(){assertEquals(.5,GrowthRules.typeMultiplier("DARK",new String[]{"STEEL"}));assertEquals(.5,GrowthRules.typeMultiplier("GHOST",new String[]{"STEEL"}));assertEquals(4,GrowthRules.typeMultiplier("ELECTRIC",new String[]{"WATER","FLYING"}));assertEquals(0,GrowthRules.typeMultiplier("FIGHTING",new String[]{"GHOST"}));assertEquals(0,GrowthRules.typeMultiplier("POISON",new String[]{"STEEL"}));assertTrue(GrowthRules.special("ELECTRIC"));}
 @Test void dexRetainsCaptureAfterTransferAndEvolution(){GrowthWorld w=fresh();clear(w,"forest");go(w,"lab");String caught=null;for(Object row:Json.asArray(w.view().get("team")))if("POOCHYENA".equals(Json.asObject(row).get("species")))caught=(String)Json.asObject(row).get("captureId");w.select(caught);w.partner().gainExperience(GrowthRules.experienceAt(18)-w.partner().experience);w.evolve();w.withdraw(caught);Map<String,Object> a=Json.asObject(w.view().get("adventure"));assertTrue(Json.asArray(a.get("caught")).containsAll(Arrays.asList("POOCHYENA","MIGHTYENA")));assertEquals(Json.write(w.export()),Json.write(GrowthWorld.restore(w.export(),()->0).export()));}
 @Test void forgedAdventureOrderAndUnknownDexAreRejected(){Map<String,Object> bad=Json.object("enabled",true,"seen",Collections.emptyList(),"caught",Collections.emptyList(),"cleared",Arrays.asList("mountain"));assertThrows(IllegalArgumentException.class,()->GrowthAdventure.restore(bad));bad.put("cleared",Collections.emptyList());bad.put("seen",Arrays.asList("INVALID"));assertThrows(IllegalArgumentException.class,()->GrowthAdventure.restore(bad));}
}
