package game.agent.growth;
import game.agent.llm.Json;import game.agent.action.ActionResult;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class GrowthAutoEvolutionTest {
 private GrowthWorld old(String species,int level){GrowthWorld w=new GrowthWorld(()->0);w.starter(species);w.partner().gainExperience(GrowthRules.experienceAt(level)-w.partner().experience);return w;}
 @Test void legacyOwnedLevel17UpdatesNameAndSpeciesAndPreservesIdXpPpAndHealthRatio(){GrowthWorld old=old("MUDKIP",17);GrowthPokemon p=old.partner();p.hurt(9);p.pp.put("TACKLE",7);String id=p.captureId;int xp=p.experience,hp=p.getHitPoints(),max=p.maxHp();GrowthWorld restored=GrowthWorld.restore(old.export(),()->0);GrowthPokemon n=restored.partner();assertEquals("MARSHTOMP",n.species);assertEquals("沼跃鱼",Json.asObject(restored.view().get("partner")).get("name"));assertEquals(id,n.captureId);assertEquals(xp,n.experience);assertEquals(7,n.pp.get("TACKLE"));assertEquals((int)((long)hp*n.maxHp()/max),n.getHitPoints());assertEquals(Json.write(restored.export()),Json.write(GrowthWorld.restore(restored.export(),()->0).export()));}
 @Test void legacyAllStarterChainsCatchUpAndFaintedPartnerStaysFainted(){for(String[] chain:new String[][]{{"TREECKO","GROVYLE","SCEPTILE"},{"MUDKIP","MARSHTOMP","SWAMPERT"},{"TORCHIC","COMBUSKEN","BLAZIKEN"}}){assertEquals(chain[0],GrowthWorld.restore(old(chain[0],15).export(),()->0).partner().species);assertEquals(chain[1],GrowthWorld.restore(old(chain[0],16).export(),()->0).partner().species);GrowthWorld w=old(chain[0],36);w.partner().hurt(w.partner().maxHp());GrowthWorld restored=GrowthWorld.restore(w.export(),()->0);assertEquals(chain[2],restored.partner().species);assertEquals(0,restored.partner().getHitPoints());}}
 @Test void realBattleAtThresholdAutomaticallyEvolvesWithoutLabClick(){GrowthWorld w=old("MUDKIP",15);w.partner().gainExperience(GrowthRules.experienceAt(16)-1-w.partner().experience);go(w,"forest");Map<String,Object> seed=w.export();for(Object row:Json.asArray(seed.get("encounters")))if("forest-1-0".equals(Json.asObject(row).get("id")))Json.asObject(Json.asObject(row).get("pokemon")).put("hp",1);w=GrowthWorld.restore(seed,()->0);String id=w.partner().captureId;for(int i=0;i<80;i++){ActionResult a=w.execute("move_to",Json.object("targetId","forest-1-0"));if(a.getStatus()==ActionResult.Status.SUCCESS)break;}assertEquals("GROWTH_DEFEATED",w.execute("use_skill",Json.object("targetId","forest-1-0","moveId","TACKLE")).getCode());assertEquals("MARSHTOMP",w.partner().species);assertEquals(id,w.partner().captureId);assertEquals("forest",w.region());assertTrue(w.partner().level()>=16);assertEquals("MARSHTOMP",GrowthWorld.restore(w.export(),()->0).partner().species);}
 @Test void rewardAndImportedPartnerAlsoUseAutomaticEvolution(){GrowthWorld w=old("MUDKIP",15);w.partner().gainExperience(GrowthRules.experienceAt(16)-1-w.partner().experience);Map<String,Object> seed=w.export();for(Object row:Json.asArray(seed.get("encounters"))){Json.asObject(row).put("state","DEFEATED");Json.asObject(Json.asObject(row).get("pokemon")).put("hp",0);}w=GrowthWorld.restore(seed,()->0);assertEquals("MILESTONE_REWARDED",w.claim("FIRST_CLEAR").getCode());assertEquals("MARSHTOMP",w.partner().species);GrowthWorld imported=new GrowthWorld(()->0);GrowthPokemon profile=new GrowthPokemon(UUID.randomUUID().toString(),"MUDKIP",17);imported.acceptTraining(profile.export());assertEquals("MARSHTOMP",imported.partner().species);}
 private void go(GrowthWorld w,String id){for(int i=0;i<160&&!id.equals(w.region());i++)w.execute("go_to_region",Json.object("regionId",id));assertEquals(id,w.region());}
}
