package game.agent.growth;
import game.agent.llm.Json;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class GrowthRespawnTest {
 static GrowthWorld cleared(){GrowthWorld w=new GrowthWorld(()->0);w.startAdventure();w.starter("MUDKIP");for(int i=0;i<80&&!w.region().equals("forest");i++)w.execute("go_to_region",Json.object("regionId","forest"));for(Object row:new ArrayList<>(Json.asArray(w.view().get("encounters")))){String id=(String)Json.asObject(row).get("id");for(int i=0;i<80&&!Boolean.TRUE.equals(Json.asObject(Json.asArray(w.view().get("encounters")).stream().filter(v->id.equals(Json.asObject(v).get("id"))).findFirst().get()).get("targetAdjacent"));i++)w.execute("move_to",Json.object("targetId",id));assertEquals("GROWTH_CAPTURED",w.execute("capture",Json.object("targetId",id)).getCode());}return w;}
 static Map<String,Object> region(GrowthWorld w){return Json.asObject(Json.asArray(w.view().get("regions")).stream().filter(v->"forest".equals(Json.asObject(v).get("id"))).findFirst().get());}
 @Test void refreshAfterTenActualMovesAndKeepPartyAndCampaign(){GrowthWorld w=cleared();int size=Json.asArray(w.view().get("team")).size();assertEquals(10,region(w).get("respawnMoves"));for(int i=0;i<10;i++){w.execute("observe",Collections.emptyMap());assertEquals(10,region(w).get("respawnMoves"));}for(int i=0;i<10;i++){int before=w.turn();w.move(i%2==0?"S":"N");assertEquals(before+1,w.turn());}assertEquals(3L,region(w).get("remaining"));assertEquals(2,region(w).get("wave"));assertEquals(size,Json.asArray(w.view().get("team")).size());assertTrue(w.regionUnlocked("river"));assertEquals(Json.write(w.export()),Json.write(GrowthWorld.restore(w.export(),()->0).export()));}
 @Test void cooldownSurvivesReloadAndOldSavesStartAtTen(){GrowthWorld w=cleared();w.move("S");Map<String,Object>s=w.export();assertEquals(9,region(GrowthWorld.restore(s,()->0)).get("respawnMoves"));s.remove("respawnMoves");assertEquals(10,region(GrowthWorld.restore(s,()->0)).get("respawnMoves"));s.put("respawnMoves",Json.object("forest",-1,"river",10,"mountain",10));assertThrows(IllegalArgumentException.class,()->GrowthWorld.restore(s,()->0));}
 @Test void standingOnSpawnDefersWholeBatchAndMovingAwayReleasesIt(){GrowthWorld w=cleared();for(int i=0;i<10;i++)w.move(i%2==0?"S":"N");/* covered separately via persisted empty region at a spawn */Map<String,Object>s=w.export();for(Object row:Json.asArray(s.get("encounters"))){Map<String,Object>e=Json.asObject(row);if("forest".equals(e.get("region"))){e.put("state","DEFEATED");Map<String,Object>p=Json.asObject(e.get("pokemon"));p.put("hp",0);}}s.put("x",7);s.put("y",5);s.put("battleTarget",null);s.put("respawnMoves",Json.object("forest",0,"river",10,"mountain",10));w=GrowthWorld.restore(s,()->0);assertEquals(0L,region(w).get("remaining"));assertEquals(2,region(w).get("wave"));w.move("S");assertEquals(3L,region(w).get("remaining"));assertEquals(3,region(w).get("wave"));}
}
