package game.agent.growth;
import game.agent.action.ActionResult;import game.agent.llm.Json;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class GrowthRegionTest {
 private GrowthWorld world(){GrowthWorld w=new GrowthWorld(()->0);w.starter("TREECKO");return w;}
 private void go(GrowthWorld w,String destination){for(int i=0;i<160&&!w.region().equals(destination);i++){String before=w.region();Map<String,Object> old=w.view();ActionResult a=w.execute("go_to_region",Json.object("regionId",destination));assertNotEquals(ActionResult.Status.REJECTED,a.getStatus(),a.getCode());if(before.equals(w.region())){assertTrue(Math.abs(((Number)old.get("x")).intValue()-((Number)w.view().get("x")).intValue())<=1);assertTrue(Math.abs(((Number)old.get("y")).intValue()-((Number)w.view().get("y")).intValue())<=1);}else{boolean connected=false;for(Object v:GrowthMaps.exits(before))if(w.region().equals(Json.asObject(v).get("regionId")))connected=true;assertTrue(connected);if(!w.region().equals(destination))assertEquals(ActionResult.Status.IN_PROGRESS,a.getStatus());}assertEquals(0,GrowthPokemon.num(Json.asArray(GrowthMaps.definition(w.region()).get("collision")).get(((Number)w.view().get("y")).intValue()*GrowthPokemon.num(GrowthMaps.definition(w.region()).get("width"))+((Number)w.view().get("x")).intValue())));}assertEquals(destination,w.region());}
 private void approach(GrowthWorld w,String id){for(int i=0;i<80;i++){ActionResult a=w.execute("move_to",Json.object("targetId",id));assertNotEquals(ActionResult.Status.REJECTED,a.getStatus(),a.getCode());if(a.getStatus()==ActionResult.Status.SUCCESS)return;}fail("No path to target");}
 private String regionRows(GrowthWorld w,String id){List<Object> rows=new ArrayList<>();for(Object v:Json.asArray(w.export().get("encounters")))if(id.equals(Json.asObject(v).get("region")))rows.add(v);return Json.write(rows);}
 @Test void routeVisitsIntermediateRegionsAndNeverMovesMoreThanOneNativeExit(){GrowthWorld w=world();List<String> entered=new ArrayList<>();for(int i=0;i<160&&!w.region().equals("mountain");i++){String before=w.region();ActionResult a=w.execute("go_to_region",Json.object("regionId","mountain"));assertNotEquals(ActionResult.Status.REJECTED,a.getStatus(),a.getCode());if(!before.equals(w.region()))entered.add(w.region());}assertEquals(Arrays.asList("forest","river","mountain"),entered);go(w,"lab");assertEquals(w.partner().captureId,GrowthWorld.restore(w.export(),()->0).partner().captureId);}
 @Test void eachRegionHasReachableEncountersAndDifferentConfiguredLevels(){GrowthWorld w=world();for(String id:Arrays.asList("forest","river","mountain")){go(w,id);List<Object> rows=Json.asArray(w.view().get("encounters"));assertEquals(3,rows.size());assertEquals(GrowthPokemon.num(GrowthMaps.definition(id).get("minimumLevel")),GrowthPokemon.num(Json.asObject(rows.get(0)).get("level")));for(Object v:rows){Map<String,Object> row=Json.asObject(v);assertEquals(id,row.get("region"));approach(w,(String)row.get("id"));}}}
 @Test void captureAndDefeatPersistAcrossRegionsWithoutDuplicateXpOrTargets(){GrowthWorld w=world();go(w,"river");approach(w,"river-1-0");assertEquals("GROWTH_CAPTURED",w.execute("capture",Json.object("targetId","river-1-0")).getCode());approach(w,"river-1-1");for(int i=0;i<30;i++){if(!w.partner().isConscious()){for(int j=0;j<80&&!w.canRest();j++)w.execute("go_to_recovery",Collections.emptyMap());w.rest();approach(w,"river-1-1");}ActionResult a=w.execute("use_skill",Json.object("targetId","river-1-1","moveId","POUND"));if(a.getCode().equals("GROWTH_DEFEATED"))break;}String river=regionRows(w,"river");assertTrue(river.contains("DEFEATED"));int xp=w.partner().experience;go(w,"mountain");go(w,"river");assertEquals(river,regionRows(w,"river"));assertEquals(xp,w.partner().experience);assertEquals("TARGET_UNAVAILABLE",w.execute("use_skill",Json.object("targetId","river-1-1","moveId","POUND")).getCode());GrowthWorld restored=GrowthWorld.restore(Json.asObject(Json.read(Json.write(w.export()))),()->0);assertEquals(Json.write(w.export()),Json.write(restored.export()));}
 @Test void returnWalkRefreshesOnlyClearedRegionAndManualNextCannotOverwriteWildBatch(){GrowthWorld w=world();go(w,"mountain");String mountain=regionRows(w,"mountain");go(w,"river");for(int i=0;i<3;i++){approach(w,"river-1-"+i);assertEquals("GROWTH_CAPTURED",w.execute("capture",Json.object("targetId","river-1-"+i)).getCode());}go(w,"lab");assertEquals("EXPEDITION_UNFINISHED",w.nextExpedition().getCode());assertEquals(mountain,regionRows(w,"mountain"));assertTrue(regionRows(w,"river").contains("river-2-0"));go(w,"mountain");assertEquals("EXPEDITION_UNFINISHED",goAndNext(w).getCode());}
 private ActionResult goAndNext(GrowthWorld w){go(w,"lab");return w.nextExpedition();}
 @Test void offMapTargetsAndUnknownRegionsCannotBeAttacked(){GrowthWorld w=world();go(w,"river");String before=Json.write(w.export());assertEquals("TARGET_REGION_REQUIRED",w.execute("use_skill",Json.object("targetId","forest-1-0","moveId","POUND")).getCode());assertEquals("UNKNOWN_REGION",w.execute("go_to_region",Json.object("regionId","ocean")).getCode());assertEquals(before,Json.write(w.export()));}
 @Test void riverWaterAndMountainCliffsBlockMovementButBridgeAndPassRemainWalkable(){for(String id:Arrays.asList("river","mountain")){Map<String,Object> d=GrowthMaps.definition(id);List<Object> c=Json.asArray(d.get("collision"));int width=GrowthPokemon.num(d.get("width"));assertEquals(1,GrowthPokemon.num(c.get((id.equals("river")?5:6)*width+8)));assertEquals(0,GrowthPokemon.num(c.get((id.equals("river")?7:6)*width+10)));}GrowthWorld w=world();go(w,"river");for(int i=0;i<4;i++)w.move("N");for(int i=0;i<4;i++)w.move("E");int turn=w.turn();assertEquals("NO_PATH",w.move("E").getCode());assertEquals(turn,w.turn());}
 @Test void campAllowsFaintedRecoveryAndCheckpointInEveryWildRegion(){GrowthWorld w=world();for(String id:Arrays.asList("forest","river","mountain")){go(w,id);w.partner().hurt(w.partner().maxHp());w.partner().pp.put("POUND",0);assertEquals("RECOVERY_POINT_REQUIRED",w.rest().getCode());for(int i=0;i<80&&!w.canRest();i++)w.execute("go_to_recovery",Collections.emptyMap());assertTrue(w.canRest());w=GrowthWorld.restore(w.export(),()->0);assertTrue(w.canRest());assertEquals(w.partner().maxHp(),w.partner().getHitPoints());assertEquals("GROWTH_RESTED",w.rest().getCode());assertEquals(w.partner().maxHp(),w.partner().getHitPoints());assertTrue(w.partner().pp.get("POUND")>0);}}
 @Test void v1ForestCheckpointMigratesWithoutRecreatingIndividuals(){GrowthWorld w=world();go(w,"forest");Map<String,Object> legacy=w.export();legacy.put("schemaVersion",1);legacy.remove("waves");legacy.remove("expeditionRegion");for(Object row:Json.asArray(legacy.get("encounters")))Json.asObject(row).remove("region");GrowthWorld restored=GrowthWorld.restore(legacy,()->0);assertEquals(w.partner().captureId,restored.partner().captureId);assertEquals(regionRows(w,"forest"),regionRows(restored,"forest"));assertEquals(2,restored.export().get("schemaVersion"));go(restored,"river");}
 @Test void corruptRegionWaveGroupAndCrossRegionBattlePointersAreRejected(){GrowthWorld w=world();go(w,"river");Map<String,Object> bad=Json.asObject(Json.read(Json.write(w.export())));Json.asObject(bad.get("waves")).put("river",0);assertThrows(IllegalArgumentException.class,()->GrowthWorld.restore(bad,()->0));Map<String,Object> shortRows=Json.asObject(Json.read(Json.write(w.export())));Json.asArray(shortRows.get("encounters")).remove(0);assertThrows(IllegalArgumentException.class,()->GrowthWorld.restore(shortRows,()->0));Map<String,Object> pointer=w.export();pointer.put("battleTarget","forest-1-0");assertThrows(IllegalArgumentException.class,()->GrowthWorld.restore(pointer,()->0));}
 @Test void takingTheLastPartnerOutAndReturningDoesNotRefreshWildIndividuals(){GrowthWorld w=world();go(w,"river");String rows=regionRows(w,"river");go(w,"lab");Map<String,Object> profile=w.partner().export();w.withdraw(w.partner().captureId);w=GrowthWorld.restore(w.export(),()->0);assertNull(w.partner());w.acceptTraining(profile);assertEquals(rows,regionRows(w,"river"));go(w,"river");}
 @Test void carriedCapturedIndividualHasOneOwnershipAndItsResolvedEncounterRemains(){GrowthWorld w=world();go(w,"river");approach(w,"river-1-0");w.execute("capture",Json.object("targetId","river-1-0"));String id=(String)Json.asObject(Json.asArray(w.view().get("team")).get(1)).get("captureId");go(w,"lab");w.select(id);Map<String,Object> profile=w.partner().export();w.withdraw(id);w=GrowthWorld.restore(w.export(),()->0);assertTrue(regionRows(w,"river").contains("TRANSFERRED"));w.acceptTraining(profile);assertTrue(regionRows(w,"river").contains("CAPTURED"));assertFalse(regionRows(w,"river").contains("TRANSFERRED"));assertEquals(2,Json.asArray(w.view().get("team")).size());GrowthWorld.restore(w.export(),()->0);}
 @Test void trainingToolsCannotSilentlyChangeChosenDestinationOrAttackForeignTargets(){GrowthWorld w=world();w.chooseExpedition("river");game.agent.tools.GameToolRegistry tools=w.trainingTools();String before=Json.write(w.export());assertEquals("TRAINING_REGION_RESTRICTED",tools.execute(new game.agent.tools.ToolRequest("wrong-region","go_to_region",Json.object("regionId","forest"))).getCode());assertEquals("TRAINING_REGION_RESTRICTED",tools.execute(new game.agent.tools.ToolRequest("wrong-target","move_to",Json.object("targetId","forest-1-0"))).getCode());assertEquals(before,Json.write(w.export()));assertNotEquals(ActionResult.Status.REJECTED,tools.execute(new game.agent.tools.ToolRequest("right-region","go_to_region",Json.object("regionId","river"))).getStatus());}
 @Test void retainedEncountersWithoutAnActivePartnerStillProduceSafeObservation(){GrowthWorld w=world();w.withdraw(w.partner().captureId);w=GrowthWorld.restore(w.export(),()->0);assertEquals("NO_PARTNER",w.observation().get("trainingPhase"));assertEquals("[]",w.observation().get("encounters"));assertEquals("CHOOSE_STARTER",w.execute("observe",Collections.emptyMap()).getCode());}
}
