package game.runtime;
import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
import java.util.*;import game.web.dto.EventDto;import game.actors.pokemon.*;import game.actions.*;
class EventContractTest {
    GameSession game(){return GameFactory.fromRows(new String[]{"#####","#...#","#...#","#...#","#####"},2,2,b->b-1);}
    @Test void movementEventsHaveStableOrderingAndTypedCoordinates(){GameSession s=game();ActionCatalog.Entry a=ActionCatalog.entries(s).stream().filter(e->"North".equals(e.dto.direction)).findFirst().get();List<EventDto> events=s.execute(a.action);Set<String> ids=new HashSet<>();for(int i=0;i<events.size();i++){EventDto e=events.get(i);assertEquals(1,e.revision);assertEquals(i,e.order);assertTrue(ids.add(e.id));}EventDto move=events.stream().filter(e->e.kind.equals("MOVE")).findFirst().get();assertEquals(2,move.from.y);assertEquals(1,move.to.y);}
    @Test void numericChangesAreNumbersAndAllPreferencesMatchGuide(){game.actors.pokemon.Pokemon[] pokemon={new Treecko(),new Mudkip(),new Torchic()};for(int i=0;i<3;i++){GameSession s=game();s.map().addActor(pokemon[i],s.map().at(1,2));AffectionAction action=i==0?new DancingAction(pokemon[i]):i==1?new ChestPoundingAction(pokemon[i]):new SingingAction(pokemon[i]);List<EventDto> events=s.execute(action);EventDto affection=events.stream().filter(e->e.kind.equals("AFFECTION_CHANGE")).findFirst().get();assertEquals(10,affection.amount);assertEquals(10,s.context().affection.getAffectionPoint(pokemon[i]));}}
    @Test void pickupAndDropKeepTheSameItemIdentity(){GameSession s=game();s.map().at(2,2).addItem(new game.items.Candy());String item=s.snapshot().groundItems.get(0).item.id;s.execute(ActionCatalog.entries(s).stream().filter(e->e.dto.kind.equals("PICK_UP")).findFirst().get().action);assertEquals(item,s.snapshot().inventory.get(0).id);s.execute(ActionCatalog.entries(s).stream().filter(e->e.dto.kind.equals("DROP")).findFirst().get().action);assertEquals(item,s.snapshot().groundItems.get(0).item.id);}
}
