package game.runtime;
import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
import game.actors.pokemon.*;import game.actions.AttackAction;import game.environments.*;import game.environments.spawners.*;
import edu.monash.fit2099.engine.positions.*;
class MovementAndProbabilityTest {
    GameSession game(RandomSource r){return GameFactory.fromRows(new String[]{"#######","#.....#","#.....#","#.....#","#.....#","#.....#","#######"},3,3,r);}
    @Test void allEightDirectionsMoveOneCell(){String[] directions={"North","North-East","East","South-East","South","South-West","West","North-West"};int[][] offsets={{0,-1},{1,-1},{1,0},{1,1},{0,1},{-1,1},{-1,0},{-1,-1}};for(int i=0;i<8;i++){GameSession s=game(b->b-1);String dir=directions[i];ActionCatalog.Entry e=ActionCatalog.entries(s).stream().filter(a->dir.equals(a.dto.direction)).findFirst().get();s.execute(e.action);assertEquals(3+offsets[i][0],s.map().locationOf(s.player()).x());assertEquals(3+offsets[i][1],s.map().locationOf(s.player()).y());assertEquals(1,s.turn());}}
    @Test void collisionAndOccupiedCellsAreNotOffered(){GameSession s=game(b->b-1);s.map().at(3,2).setGround(new game.environments.structures.Wall());s.map().addActor(new Mudkip(),s.map().at(4,3));assertFalse(ActionCatalog.entries(s).stream().anyMatch(a->"North".equals(a.dto.direction)||"East".equals(a.dto.direction)));}
    @Test void hitAndMissKeepInclusiveOriginalBoundary(){for(int roll:new int[]{50,51}){GameSession s=game(b->roll%b);Treecko a=new Treecko();Mudkip target=new Mudkip();s.map().addActor(a,s.map().at(1,1));s.map().addActor(target,s.map().at(2,1));new AttackAction(target,"East").execute(a,s.map());assertEquals(roll==50?90:100,target.getHitPoints());assertTrue(s.context().events.stream().anyMatch(e->e.kind.equals(roll==50?"ATTACK":"MISS")));}}
    @Test void spawnerInclusiveThresholdsAndLavaEquality(){for(int roll:new int[]{10,11}){GameSession s=game(b->roll%b);Location l=s.map().at(1,1);l.setGround(new Crater());l.getGround().tick(l);assertEquals(roll==10,l.containsAnActor());Location lava=s.map().at(4,4);Lava g=new Lava();lava.setGround(g);g.tick(lava);g.dayEffect();assertEquals(roll==10,s.map().at(5,4).getGround() instanceof Lava);}}
    @Test void treeTriesGrassNeighboursUntilSuccessful(){java.util.concurrent.atomic.AtomicInteger calls=new java.util.concurrent.atomic.AtomicInteger();GameSession s=game(b->{calls.incrementAndGet();return 16;});Location l=s.map().at(1,1);l.setGround(new Tree());s.map().at(2,1).setGround(new Hay());s.map().at(1,2).setGround(new Hay());l.getGround().tick(l);assertFalse(l.containsAnActor());assertEquals(2,calls.get());GameSession hit=game(b->15);Location t=hit.map().at(1,1);t.setGround(new Tree());hit.map().at(2,1).setGround(new Hay());t.getGround().tick(t);assertTrue(t.getActor() instanceof Treecko);}
}
