package game.agent.demo;
import game.agent.growth.*;import game.agent.llm.Json;import java.util.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;
/** Offline native-combat sample; explicitly a scripted policy, never an AI/model evaluation. */
public final class ExpansionBalanceDemo {
 private static GrowthPokemon mon(String id,int level){return new GrowthPokemon(UUID.randomUUID().toString(),id,level);}
 private static String best(GrowthPokemon a,GrowthPokemon d){String chosen=null;int best=-1;for(String id:a.pp.keySet()){GrowthRules.Move move=GrowthRules.move(id);if(move.power<=0||a.pp.get(id)<=0)continue;int damage=GrowthRules.damage(a,d,move,0,move.power)*("DOUBLE".equals(move.effect)?2:1);if(damage>best){best=damage;chosen=id;}}return chosen;}
 private static void equip(GrowthPokemon p,GrowthPokemon target){List<String> moves=new ArrayList<>();for(String id:p.availableMoves())if(GrowthRules.move(id).power>0)moves.add(id);moves.sort((a,b)->Integer.compare(GrowthRules.damage(p,target,GrowthRules.move(b),0,GrowthRules.move(b).power),GrowthRules.damage(p,target,GrowthRules.move(a),0,GrowthRules.move(a).power)));p.pp.clear();for(String id:moves)if(p.pp.size()<4)p.pp.put(id,GrowthRules.move(id).pp);}
 public static Map<String,Object> run(){List<Object> rows=new ArrayList<>(),summary=new ArrayList<>();int cases=0,unresolved=0;for(String species:Arrays.asList("POOCHYENA","ZIGZAGOON","TAILLOW","WINGULL","SHROOMISH","ELECTRIKE")){int wins=0,losses=0,draws=0,totalTurns=0;for(int level:new int[]{5,10,20,30})for(String opponent:Arrays.asList("TREECKO","MUDKIP","TORCHIC"))for(int seed=0;seed<16;seed++){GrowthPokemon a=mon(species,level),d=mon(opponent,level);a.assignNature(GrowthRules.NATURES.get(seed%5));equip(a,d);equip(d,a);Random rng=new Random(seed*31L+level);GrowthCombat combat=new GrowthCombat(rng::nextInt);int turns=0;while(a.isConscious()&&d.isConscious()&&turns<80){String move=best(a,d);if(move==null)break;combat.turn(a,d,move);turns++;}String result=!a.isConscious()&&!d.isConscious()?"DRAW":!d.isConscious()?"WIN":!a.isConscious()?"LOSS":"UNRESOLVED";if(result.equals("WIN"))wins++;else if(result.equals("LOSS"))losses++;else if(result.equals("DRAW"))draws++;else unresolved++;cases++;totalTurns+=turns;rows.add(Json.object("species",species,"opponent",opponent,"level",level,"seed",seed,"nature",a.nature,"result",result,"turns",turns,"hp",Math.max(0,a.getHitPoints()),"targetHp",Math.max(0,d.getHitPoints())));}summary.add(Json.object("species",species,"cases",192,"wins",wins,"losses",losses,"draws",draws,"averageTurns",totalTurns/192.0));}return Json.object("status",unresolved==0?"PASSED":"REVIEW_REQUIRED","kind","SCRIPTED_NATIVE_BALANCE_SAMPLE","realAi",false,"policy","highest equipped estimated damage vs native wild counter; no healing, no EV, five natures, same levels","cases",cases,"unresolved",unresolved,"summary",summary,"runs",rows);}
 public static void main(String[] args)throws Exception{if(args.length!=1)throw new IllegalArgumentException("Usage: ExpansionBalanceDemo report.json");Map<String,Object> report=run();Files.write(Paths.get(args[0]),Json.write(report).getBytes(StandardCharsets.UTF_8));System.out.println("Native balance sample: "+report.get("cases")+" cases, "+report.get("unresolved")+" unresolved");if(!"PASSED".equals(report.get("status")))throw new IllegalStateException("Balance sample needs review");}
}
