package game.agent.web;
import game.agent.duel.DuelBattle;
import game.agent.growth.*;
import game.agent.llm.*;
import game.agent.runtime.AgentLoop;
import game.agent.tools.*;
import game.agent.persistence.*;
import game.agent.eval.EvaluationProviders;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Supplier;
/** V5 duel orchestration. Workers decide from immutable side-specific observations only. */
public final class DuelRoom implements WebRoom {
 private final String id=UUID.randomUUID().toString(),owner;private String taskId=UUID.randomUUID().toString();private long revision=1;
 private final ProviderSelection primary;private final EvaluationProviders providers;private final Executor executor;private final WorldStore store;
 private final Supplier<List<GrowthPokemon>> owned;
 private DuelBattle battle;private String status="IDLE",mode="manual",error,difficulty="standard";private final String[] models={"baseline","baseline"};
 private final CompletableFuture<Decision>[] pending=new CompletableFuture[2];private final long[] started=new long[2];private final int[] failures={0,0},calls={0,0};
 private final List<Map<String,Object>> decisions=new ArrayList<>();private final Map<String,String> payloads=new LinkedHashMap<>();private final Map<String,AgentRoom.Reply> receipts=new LinkedHashMap<>();
 private long tokens;private boolean unknownUsage;
 private static class Decision {ToolRequest action;Map<String,Number> usage;String error;double latency;}
 DuelRoom(String owner,ProviderSelection primary,EvaluationProviders providers,Executor executor,WorldStore store,Supplier<List<GrowthPokemon>> owned){this.owner="duel:"+owner;this.primary=primary;this.providers=providers;this.executor=executor;this.store=store;this.owned=owned;if(store!=null){Map<String,Object> saved=store.load(this.owner);if(saved!=null)restore(saved);else persist();}}
 public String getId(){return id;}
 private Set<String> modelNames(){Set<String> names=new LinkedHashSet<>(providers.models());names.add("baseline");if(primary.gateway!=null)names.add(primary.model);return names;}
 private AgentLoop.DecisionProvider gateway(String model){if(model.equals("baseline"))return DuelRoom::baseline;if(primary.gateway!=null&&model.equals(primary.model))return primary.gateway;if(!providers.models().contains(model))throw new ProviderException(ProviderException.Code.CONFIGURATION);return providers.create(model);}
 public static ToolRequest baseline(AgentLoop.Context c){Map<String,String> o=c.getObservation();List<Object> moves=Json.asArray(Json.read(o.get("legalMoves")));if(Boolean.parseBoolean(o.get("forcedSwitch")))return new ToolRequest(UUID.randomUUID().toString(),"battle_switch",Json.object("slot",Json.asArray(Json.read(o.get("legalSwitches"))).get(0)));List<Object> own=Json.asArray(Json.read(o.get("ownTeam")));Map<String,Object> p=Json.asObject(own.get(Integer.parseInt(o.get("activeSlot")))),opp=Json.asObject(Json.read(o.get("opponentActive")));double best=-1;String chosen=(String)moves.get(0);for(Object obj:moves){String m=(String)obj;if(m.equals("STRUGGLE"))continue;GrowthRules.Move move=GrowthRules.move(m);List<Object> types=Json.asArray(opp.get("types"));String[] ts=types.toArray(new String[0]);double score=move.power*move.accuracy*GrowthRules.typeMultiplier(move.type,ts);if(score>best){best=score;chosen=m;}}return new ToolRequest(UUID.randomUUID().toString(),"battle_move",Json.object("moveId",chosen));}
 private AgentRoom.Reply reply(int code,String req,String reason){return new AgentRoom.Reply(code,Json.object("requestId",req,"outcome",code==200?"ACCEPTED":"REJECTED","reasonCode",reason));}
 public AgentRoom.Reply command(Map<String,Object> input,long now){return command(input,now,(String)null);}
 public AgentRoom.Reply command(Map<String,Object> input,long now,boolean blocked){return command(input,now,blocked?"MODE_NOT_SELECTED":null);}
 public AgentRoom.Reply command(Map<String,Object> input,long now,String block){String req="";try{
  if(!input.keySet().equals(new HashSet<>(Arrays.asList("requestId","taskId","expectedRevision","command","params"))))return reply(400,req,"INVALID_FIELDS");req=(String)input.get("requestId");if(req==null||!req.matches("[a-zA-Z0-9_-]{1,128}"))return reply(400,"","INVALID_REQUEST_ID");String kind=(String)input.get("command"),payload=Json.write(input);
  if(status.equals("STORAGE_ERROR")&&!"RECOVER".equals(kind))return reply(503,req,"STORAGE_UNAVAILABLE");
  if(payloads.containsKey(req))return payload.equals(payloads.get(req))?receipts.get(req):reply(409,req,"REQUEST_ID_CONFLICT");
  int expected=GrowthPokemon.num(input.get("expectedRevision"));boolean stop=Arrays.asList("PAUSE","CANCEL").contains(kind);if(!taskId.equals(input.get("taskId"))||expected<1||expected>revision||(!stop&&expected!=revision))return reply(409,req,"STALE_REVISION");Map<String,Object> params=Json.asObject(input.get("params"));if(status.equals("STORAGE_ERROR")&&!kind.equals("RECOVER"))return reply(503,req,"STORAGE_UNAVAILABLE");
  if(block!=null&&!Arrays.asList("PAUSE","CANCEL","RECOVER").contains(kind))return reply(409,req,block);
  if(kind.equals("START")){if(status.equals("RUNNING"))return reply(409,req,"BATTLE_ACTIVE");Set<String> startFields=new HashSet<>(Arrays.asList("mode","seed","leftModel","rightModel","teamIds"));if(params.containsKey("difficulty"))startFields.add("difficulty");if(!params.keySet().equals(startFields))return reply(400,req,"INVALID_PARAMS");String difficulty=params.containsKey("difficulty")?(String)params.get("difficulty"):"standard";if(!Arrays.asList("standard","rookie").contains(difficulty))return reply(400,req,"INVALID_PARAMS");String m=(String)params.get("mode"),l=(String)params.get("leftModel"),r=(String)params.get("rightModel");if(!Arrays.asList("manual","delegated","auto").contains(m)||!modelNames().contains(l)||!modelNames().contains(r))return reply(400,req,"INVALID_BATTLE_CONFIGURATION");List<Object> ids=Json.asArray(params.get("teamIds"));if(ids.size()>3||new HashSet<>(ids).size()!=ids.size())return reply(400,req,"INVALID_TEAM");List<GrowthPokemon> team=new ArrayList<>();List<GrowthPokemon> catalog=owned.get();for(Object wanted:ids){GrowthPokemon found=null;for(GrowthPokemon p:catalog)if(p.captureId.equals(wanted))found=p;if(found==null)return reply(409,req,"PARTNER_NOT_AVAILABLE");team.add(found);}boolean rookie="rookie".equals(difficulty);if(rookie&&(!m.equals("manual")||!l.equals("baseline")||!r.equals("baseline")||team.size()!=1))return reply(400,req,"INVALID_ROOKIE_CONFIGURATION");List<GrowthPokemon> opposition=rookie?Collections.singletonList(new GrowthPokemon(UUID.randomUUID().toString(),"POOCHYENA",rookieLevel(team.get(0)))):DuelBattle.demoTeam();DuelBattle next=new DuelBattle(team.isEmpty()?DuelBattle.demoTeam():team,opposition,GrowthPokemon.num(params.get("seed")));cancelPending();battle=next;this.difficulty=difficulty;mode=m;models[0]=l;models[1]=r;tokens=0;unknownUsage=false;calls[0]=calls[1]=failures[0]=failures[1]=0;decisions.clear();status="RUNNING";error=null;taskId=UUID.randomUUID().toString();
  }else if(kind.equals("ACTION")){if(status.equals("RUNNING")&&!mode.equals("manual"))return reply(409,req,"AI_CONTROLS_TEAM");if(!status.equals("RUNNING")||battle==null)return reply(409,req,"BATTLE_NOT_RUNNING");if(!params.keySet().equals(new HashSet<>(Arrays.asList("tool","arguments"))))return reply(400,req,"INVALID_PARAMS");String result=battle.submit(0,new ToolRequest(req,(String)params.get("tool"),Json.asObject(params.get("arguments"))));if(!result.equals("CHOICE_ACCEPTED"))return reply(409,req,result);finish();
  }else{if(!params.isEmpty())return reply(400,req,"INVALID_PARAMS");switch(kind){case "PAUSE":if(!status.equals("RUNNING"))return reply(409,req,"NOT_RUNNING");cancelPending();status="PAUSED";error=null;break;case "RESUME":if(!status.equals("PAUSED")||battle==null)return reply(409,req,"NOT_PAUSED");if(unknownUsage&&(!models[0].equals("baseline")||!models[1].equals("baseline")))return reply(409,req,"BATTLE_USAGE_UNCERTAIN");if(calls[0]+calls[1]>=120||tokens>=250000)return reply(409,req,"BATTLE_BUDGET_EXHAUSTED");failures[0]=failures[1]=0;status="RUNNING";error=null;break;case "MANUAL":if(!status.equals("PAUSED")||battle==null)return reply(409,req,"NOT_PAUSED");cancelPending();mode="manual";models[1]="baseline";status="RUNNING";error=null;break;case "CANCEL":cancelPending();status="CANCELLED";break;case "RECOVER":if(store==null||!status.equals("STORAGE_ERROR"))return reply(409,req,"NO_STORAGE_RECOVERY");Map<String,Object> saved=store.load(owner);if(saved==null)return reply(503,req,"STORAGE_UNAVAILABLE");cancelPending();restore(saved);error=null;break;default:return reply(400,req,"UNKNOWN_COMMAND");}}
  revision++;AgentRoom.Reply result=reply(200,req,"ACCEPTED");if(payloads.size()>=64){String first=payloads.keySet().iterator().next();payloads.remove(first);receipts.remove(first);}payloads.put(req,payload);receipts.put(req,result);return persist()?result:reply(503,req,"STORAGE_UNAVAILABLE");
 }catch(IllegalArgumentException|ClassCastException|NullPointerException|ArithmeticException e){return reply(400,req,"INVALID_COMMAND");}catch(StoreException e){status="STORAGE_ERROR";error=e.getCode().name();cancelPending();revision++;return reply(503,req,"STORAGE_UNAVAILABLE");}}
 private void finish(){if(battle!=null&&!battle.result().equals("ACTIVE")){status="COMPLETED";cancelPending();}}
 public void tick(long now){if(!status.equals("RUNNING"))return;for(int s=0;s<2&&status.equals("RUNNING");s++){
  if(s==0&&mode.equals("manual"))continue;
  if(pending[s]!=null){if(!pending[s].isDone()&&now-started[s]>=Math.max(primary.timeoutMillis,providers.timeout())+1000L){pending[s].cancel(true);pending[s]=null;unknownUsage=true;pauseError("PROVIDER_TIMEOUT");break;}if(!pending[s].isDone())continue;Decision d;try{d=pending[s].join();}catch(CancellationException|CompletionException e){pauseError("PROVIDER_UNAVAILABLE");break;}pending[s]=null;
   String outcome=d.error;if(outcome==null){try{outcome=d.action==null?"INVALID_BATTLE_ACTION":battle.submit(s,d.action);}catch(RuntimeException invalid){outcome="INVALID_BATTLE_ACTION";}}if(d.usage==null||!d.usage.containsKey("totalTokens"))unknownUsage=true;else {long used=d.usage.get("totalTokens").longValue();if(used<0)unknownUsage=true;else tokens+=used;}
   decisions.add(Json.object("side",s,"round",battle.round(),"model",models[s],"latencyMs",d.latency,"usage",d.usage==null?Collections.emptyMap():d.usage,"tool",d.action==null?null:d.action.getName(),"arguments",d.action==null?null:d.action.getArguments(),"outcome",outcome));
   if(unknownUsage&&!models[s].equals("baseline")&&d.error==null)pauseError("PROVIDER_USAGE_UNKNOWN");
   if(!"CHOICE_ACCEPTED".equals(outcome)){failures[s]++;if(d.error!=null||failures[s]>=3)pauseError(outcome);}else failures[s]=0;finish();revision++;if(!persist())break;
  }
  if(status.equals("RUNNING")&&battle.needsChoice(s)&&pending[s]==null){if(calls[0]+calls[1]>=120||tokens>=250000){pauseError("BATTLE_BUDGET_EXHAUSTED");persist();break;}AgentLoop.DecisionProvider gateway;try{gateway=gateway(models[s]);}catch(ProviderException unavailable){pauseError(unavailable.getMessage());persist();break;}AgentLoop.Context context=AgentLoop.Context.snapshot("Win this singles trainer battle. Choose exactly one legal action. Switch when forced. Only observation is authoritative; do not invent hidden opponent moves or reserves.",battle.observation(s),battle.tools(s),null);calls[s]++;started[s]=now;revision++;if(!persist())break;final String selectedModel=models[s];
   try{pending[s]=CompletableFuture.supplyAsync(()->{Decision d=new Decision();long start=System.nanoTime();try{d.action=gateway.decide(context);d.usage=sanitizedUsage(gateway.getUsage());if(selectedModel.equals("baseline"))d.usage=JsonNumber.zero();}catch(ProviderException e){d.error=e.getMessage();}catch(RuntimeException e){d.error="PROVIDER_UNAVAILABLE";}d.latency=(System.nanoTime()-start)/1000000.0;return d;},executor);}catch(RejectedExecutionException e){pauseError("MODEL_QUEUE_FULL");}revision++;persist();
  }
 }}
 private static Map<String,Number> sanitizedUsage(Map<String,Number> raw){Map<String,Number> usage=new LinkedHashMap<>();if(raw!=null)for(String key:Arrays.asList("inputTokens","outputTokens","totalTokens","cachedInputTokens","reasoningOutputTokens","cacheWriteTokens")){Number n=raw.get(key);if(n!=null&&Double.isFinite(n.doubleValue())&&n.doubleValue()==n.longValue()&&n.longValue()>=0&&n.longValue()<=1000000000)usage.put(key,n.longValue());}return usage;}
 private static class JsonNumber{static Map<String,Number> zero(){Map<String,Number> v=new LinkedHashMap<>();v.put("totalTokens",0L);return v;}}
 private void pauseError(String reason){cancelPending();status="PAUSED";error=reason;revision++;}
 private void cancelPending(){for(int s=0;s<2;s++){if(pending[s]!=null){if(!models[s].equals("baseline"))unknownUsage=true;pending[s].cancel(true);}pending[s]=null;}}
 private static int rookieLevel(GrowthPokemon p){return Math.max(5,Math.min(8,p.level()-1));}
 private static Map<String,Object> preview(GrowthPokemon p){return Json.object("species",p.species,"name",p.view().get("name"),"level",p.level());}
 private static Map<String,Object> opponentPreviews(List<GrowthPokemon> catalog){List<Object> standard=new ArrayList<>();for(GrowthPokemon p:DuelBattle.demoTeam())standard.add(preview(p));Map<String,Object> rookie=new LinkedHashMap<>();for(GrowthPokemon p:catalog)rookie.put(p.captureId,preview(new GrowthPokemon(p.captureId,"POOCHYENA",rookieLevel(p))));return Json.object("standard",standard,"rookieByPartner",rookie);}
 public Map<String,Object> snapshot(){List<GrowthPokemon> catalog=owned.get();List<Object> choices=new ArrayList<>();for(GrowthPokemon p:catalog)choices.add(Json.object("captureId",p.captureId,"species",p.species,"name",p.view().get("name"),"level",p.level()));return Json.object("roomId",id,"taskId",taskId,"revision",revision,"status",status,"mode","DUEL","controlMode",mode,"difficulty",difficulty,"world",battle==null?Collections.emptyMap():battle.view(0),"trace",battle==null?Collections.emptyList():battle.trace(),"decisions",publicDecisions(),"models",new ArrayList<>(modelNames()),"leftModel",models[0],"rightModel",models[1],"teamOptions",choices,"opponentPreviews",opponentPreviews(catalog),"waitingLeft",pending[0]!=null,"waitingRight",pending[1]!=null,"calls",Arrays.asList(calls[0],calls[1]),"tokens",tokens,"usageIncomplete",unknownUsage,"errorCode",error,"storage",store==null?"MEMORY":"PERSISTENT");}
 private List<Object> publicDecisions(){List<Object> rows=new ArrayList<>();for(Map<String,Object> d:decisions){Map<String,Object> copy=new LinkedHashMap<>(d);if(!status.equals("COMPLETED")&&GrowthPokemon.num(copy.get("side"))==1){copy.remove("tool");copy.remove("arguments");}rows.add(copy);}return rows;}
 private boolean persist(){if(store==null)return true;try{List<Object> rr=new ArrayList<>();for(String key:payloads.keySet())rr.add(Json.object("id",key,"payload",payloads.get(key),"status",receipts.get(key).status,"body",receipts.get(key).body));store.save(owner,Json.object("schemaVersion",1,"difficulty",difficulty,"battle",battle==null?null:battle.export(),"taskId",taskId,"revision",revision,"status",status,"mode",mode,"models",Arrays.asList(models[0],models[1]),"calls",Arrays.asList(calls[0],calls[1]),"tokens",tokens,"unknownUsage",unknownUsage,"errorCode",error,"decisionsJson",Json.write(decisions),"receipts",rr));return true;}catch(RuntimeException e){cancelPending();status="STORAGE_ERROR";error=e instanceof StoreException?((StoreException)e).getCode().name():"UNKNOWN";revision++;return false;}}
 private void restore(Map<String,Object> v){Set<String> fields=new HashSet<>(Arrays.asList("schemaVersion","battle","taskId","revision","status","mode","models","calls","tokens","unknownUsage","errorCode","decisionsJson","receipts"));if(v.containsKey("difficulty"))fields.add("difficulty");if(!v.keySet().equals(fields)||GrowthPokemon.num(v.get("schemaVersion"))!=1)throw new IllegalArgumentException("INVALID_DUEL_SAVE");difficulty=(String)v.getOrDefault("difficulty","standard");if(!Arrays.asList("standard","rookie").contains(difficulty))throw new IllegalArgumentException("INVALID_DIFFICULTY");DuelBattle loaded=v.get("battle")==null?null:DuelBattle.restore(Json.asObject(v.get("battle")));String st=(String)v.get("status"),m=(String)v.get("mode");if(!Arrays.asList("IDLE","RUNNING","PAUSED","COMPLETED","CANCELLED").contains(st)||!Arrays.asList("manual","delegated","auto").contains(m))throw new IllegalArgumentException();String task=(String)v.get("taskId");if(!task.matches("[a-f0-9-]{36}"))throw new IllegalArgumentException();long rev=((Number)v.get("revision")).longValue(),tok=((Number)v.get("tokens")).longValue();if(rev<1||tok<0)throw new IllegalArgumentException();for(int s=0;s<2;s++){models[s]=(String)Json.asArray(v.get("models")).get(s);if(models[s]==null||!models[s].matches("[a-zA-Z0-9_.:-]{1,128}"))throw new IllegalArgumentException("INVALID_MODEL");calls[s]=GrowthPokemon.num(Json.asArray(v.get("calls")).get(s));if(calls[s]<0||calls[s]>120)throw new IllegalArgumentException();}List<Object> ds=Json.asArray(Json.read((String)v.get("decisionsJson"))),rs=Json.asArray(v.get("receipts"));if(ds.size()>120||rs.size()>64||calls[0]+calls[1]>120)throw new IllegalArgumentException();error=(String)v.get("errorCode");if(error!=null&&!error.matches("[A-Z_]{1,80}"))throw new IllegalArgumentException();battle=loaded;taskId=task;revision=rev+1;tokens=tok;unknownUsage=(Boolean)v.get("unknownUsage");status=st.equals("RUNNING")?"PAUSED":st;mode=m;decisions.clear();for(Object d:ds)decisions.add(Json.asObject(d));for(int side=0;side<2;side++){int recorded=0;for(Map<String,Object> d:decisions)if(GrowthPokemon.num(d.get("side"))==side)recorded++;if(!models[side].equals("baseline")&&calls[side]>recorded)unknownUsage=true;}payloads.clear();receipts.clear();for(Object r:rs){Map<String,Object> a=Json.asObject(r);String key=(String)a.get("id");if(payloads.put(key,(String)a.get("payload"))!=null)throw new IllegalArgumentException();receipts.put(key,new AgentRoom.Reply(GrowthPokemon.num(a.get("status")),Json.asObject(a.get("body"))));}}
 public void close(){cancelPending();}
}
