package game.agent.web;
import game.agent.persistence.WorldStore;import game.agent.llm.Json;import java.util.*;import java.security.*;import java.nio.charset.StandardCharsets;
/** Stable invited owners. Plaintext credentials exist only in one response; migration activates last. */
public final class PlayerIdentity {
 private static final String KEY="player-identities";private final WorldStore store;private final Set<String> invites;private Map<String,Object> index;private boolean storageError;
 public PlayerIdentity(WorldStore store,Set<String> invites){this.store=Objects.requireNonNull(store);this.invites=Set.copyOf(invites);Map<String,Object> loaded=store.load(KEY);index=loaded==null?Json.object("version",1,"players",new ArrayList<>(),"usedInvites",new ArrayList<>()):loaded;if(!index.keySet().equals(Set.of("version","players","usedInvites"))||((Number)index.get("version")).intValue()!=1)throw new IllegalStateException("IDENTITY_STORAGE_INVALID");}
 public static String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private List<Object> players(){return Json.asArray(index.get("players"));}
 private Map<String,Object> row(String owner){if(owner==null)return null;for(Object value:players()){Map<String,Object> row=Json.asObject(value);if(owner.equals(row.get("owner")))return row;}return null;}
 public synchronized boolean registered(String owner){return row(owner)!=null;}
 public synchronized String resolve(String device){if(device==null)return null;String h=hash(device);for(Object value:players()){Map<String,Object> p=Json.asObject(value);for(Object d:Json.asArray(p.get("devices"))){Map<String,Object> r=Json.asObject(d);if(h.equals(r.get("hash"))&&!Boolean.TRUE.equals(r.get("revoked")))return(String)p.get("owner");}}return null;}
 public synchronized boolean knownDevice(String device){if(device==null)return false;String h=hash(device);for(Object value:players())for(Object d:Json.asArray(Json.asObject(value).get("devices")))if(h.equals(Json.asObject(d).get("hash")))return true;return false;}
 public synchronized Map<String,Object> preview(String recovery){Map<String,Object> p=recovery(recovery);String owner=(String)p.get("owner");Map<String,Object> growth=store.load("growth:"+owner);Map<String,Object> w=growth==null?Map.of():Json.asObject(growth.get("world"));return Json.object("owner",owner,"hasGrowth",growth!=null,"teamCount",w.containsKey("team")?Json.asArray(w.get("team")).size():0);}
 private Map<String,Object> recovery(String secret){if(secret==null||!secret.matches("[a-f0-9]{64}"))throw new IllegalArgumentException("IDENTITY_CREDENTIAL_INVALID");String h=hash(secret);for(Object value:players()){Map<String,Object> p=Json.asObject(value);if(h.equals(p.get("recoveryHash")))return p;}throw new IllegalArgumentException("IDENTITY_CREDENTIAL_INVALID");}
 private String secret(){byte[] bytes=new byte[32];new SecureRandom().nextBytes(bytes);return HexFormat.of().formatHex(bytes);}
 private Map<String,Object> cloneIndex(){return Json.asObject(Json.read(Json.write(index)));}
 private void commit(Map<String,Object> next){if(storageError)throw new IllegalStateException("IDENTITY_STORAGE_ERROR");try{store.save(KEY,next);index=next;}catch(RuntimeException error){try{Map<String,Object> saved=store.load(KEY);if(saved!=null){if(!saved.keySet().equals(Set.of("version","players","usedInvites")))throw new IllegalStateException();index=saved;}}catch(RuntimeException unreadable){storageError=true;}throw error;}}
 public synchronized Map<String,Object> redeem(String oldOwner,String invite){return redeem(oldOwner,invite,UUID.randomUUID().toString(),UUID.randomUUID().toString(),secret());}
 public synchronized Map<String,Object> redeem(String oldOwner,String invite,String requestId,String device,String recovery){
  if(storageError)throw new IllegalStateException("IDENTITY_STORAGE_ERROR");
  if(oldOwner==null||requestId==null||!requestId.matches("[a-f0-9-]{36}")||device==null||!device.matches("[a-f0-9-]{36}")||recovery==null||!recovery.matches("[a-f0-9]{64}"))throw new IllegalArgumentException("IDENTITY_CREDENTIAL_INVALID");
  for(Object value:players()){Map<String,Object> prior=Json.asObject(value);if(!(prior.get("registration") instanceof Map))continue;Map<String,Object> registration=Json.asObject(prior.get("registration"));if(requestId.equals(registration.get("requestId"))){
   if(invite==null||!hash(invite).equals(registration.get("inviteHash"))||!hash(recovery).equals(prior.get("recoveryHash"))||!prior.get("owner").equals(resolve(device)))throw new IllegalArgumentException("IDENTITY_CREDENTIAL_INVALID");
   return Json.object("owner",prior.get("owner"),"device",device,"recovery",recovery);
  }}
  if(knownDevice(device))throw new IllegalArgumentException("IDENTITY_CREDENTIAL_INVALID");
  if(invite==null||invite.length()>128||!invites.contains(hash(invite))||Json.asArray(index.get("usedInvites")).contains(hash(invite)))throw new IllegalArgumentException("IDENTITY_CREDENTIAL_INVALID");if(registered(oldOwner))throw new IllegalStateException("IDENTITY_ALREADY_BOUND");if(players().size()>=32)throw new IllegalStateException("IDENTITY_LIMIT");
  String owner=UUID.randomUUID().toString();List<String> keys=migrationKeys(oldOwner);for(String key:keys){Map<String,Object> value=store.load(key);if(value!=null)store.save(key.replace(oldOwner,owner),value);}Map<String,Object> next=cloneIndex();Json.asArray(next.get("players")).add(Json.object("owner",owner,"recoveryHash",hash(recovery),"registration",Json.object("requestId",requestId,"oldOwnerHash",hash(oldOwner),"inviteHash",hash(invite)),"devices",new ArrayList<>(List.of(Json.object("id",UUID.randomUUID().toString(),"hash",hash(device),"revoked",false)))));Json.asArray(next.get("usedInvites")).add(hash(invite));commit(next);return Json.object("owner",owner,"device",device,"recovery",recovery);}
 private List<String> migrationKeys(String owner){List<String> keys=new ArrayList<>();for(String prefix:List.of("","battle:","collection:","growth:","duel:","evaluation:")){String key=prefix+owner;Map<String,Object> value=store.load(key);if(value==null)continue;if(Arrays.asList("RUNNING","REPLANNING","WAITING_APPROVAL","STORAGE_ERROR").contains(value.getOrDefault("phase",value.get("status"))))throw new IllegalStateException("IDENTITY_TASK_ACTIVE");keys.add(key);if(prefix.equals("evaluation:")){Set<String> cases=new LinkedHashSet<>();for(Object b:Json.asArray(value.containsKey("batchesJson")?Json.read((String)value.get("batchesJson")):value.get("batches"))){Map<String,Object> batch=Json.asObject(b);if(Arrays.asList("RUNNING","QUEUED").contains(batch.get("status")))throw new IllegalStateException("IDENTITY_TASK_ACTIVE");for(Object c:Json.asArray(batch.get("cases")))cases.add((String)Json.asObject(c).get("id"));}if(value.containsKey("purgeJson"))for(Object id:Json.asArray(Json.read((String)value.get("purgeJson"))))cases.add((String)id);for(String id:cases){if(!id.matches("[a-f0-9-]{36}"))throw new IllegalStateException("IDENTITY_STORAGE_INVALID");String run=key+":"+id,usage=run+":usage";Map<String,Object> ledger=store.load(usage);if(ledger!=null&&((Number)ledger.get("issued")).longValue()>Json.asArray(ledger.get("calls")).size())throw new IllegalStateException("IDENTITY_USAGE_PENDING");keys.add(run);keys.add(usage);}}}return keys;}
 public synchronized Map<String,Object> restoreDevice(String recovery){if(storageError)throw new IllegalStateException("IDENTITY_STORAGE_ERROR");Map<String,Object> target=recovery(recovery);String owner=(String)target.get("owner"),device=UUID.randomUUID().toString();Map<String,Object> next=cloneIndex();Map<String,Object> p=null;for(Object v:Json.asArray(next.get("players")))if(owner.equals(Json.asObject(v).get("owner")))p=Json.asObject(v);List<Object> devices=Json.asArray(p.get("devices"));if(devices.size()>=8)throw new IllegalStateException("IDENTITY_DEVICE_LIMIT");devices.add(Json.object("id",UUID.randomUUID().toString(),"hash",hash(device),"revoked",false));commit(next);return Json.object("owner",owner,"device",device);}
 public synchronized void revoke(String owner,String device){if(storageError)throw new IllegalStateException("IDENTITY_STORAGE_ERROR");Map<String,Object> next=cloneIndex();for(Object v:Json.asArray(next.get("players")))if(owner.equals(Json.asObject(v).get("owner")))for(Object d:Json.asArray(Json.asObject(v).get("devices")))if(hash(device).equals(Json.asObject(d).get("hash")))Json.asObject(d).put("revoked",true);commit(next);}
}
