package game.agent;
import game.agent.web.*;import game.agent.llm.*;import game.agent.tools.*;import game.agent.demo.*;import game.agent.persistence.*;import game.agent.action.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;
class CooperativeQuestTest {
 static ProviderSelection provider(){return new ProviderSelection("test","offline",1000,c->new ToolRequest(UUID.randomUUID().toString(),"observe_quest",Collections.emptyMap()),(text,q)->TaskIntent.of(q,EnumSet.of(TaskIntent.Constraint.NO_SPENDING),null,null));}
 static AgentRoom room(){AgentRoom r=new AgentRoom("coop",provider(),Runnable::run,true,null);assertEquals(200,r.command(AgentRoomTest.command(r,"COOP_START",Collections.emptyMap()),0).status);return r;}
 static AgentRoom.Reply player(AgentRoom r,String action,Map<String,Object> args){return r.command(AgentRoomTest.command(r,"PLAYER_ACTION",Json.object("action",action,"arguments",args)),10);}
 static void move(AgentRoom r,String direction){assertEquals(200,player(r,"move",Json.object("direction",direction)).status);}
 @Test void independentPlayerCanActWhileAiIsRunningWithoutTakingItsActor(){AgentRoom r=room();AgentRoomTest.start(r);Map<String,Object> before=Json.asObject(r.snapshot().get("world"));move(r,"E");assertEquals("RUNNING",r.snapshot().get("status"));assertEquals(before.get("x"),Json.asObject(r.snapshot().get("world")).get("x"));assertEquals(30,Json.asObject(r.snapshot().get("player")).get("x"));assertEquals("1",Json.asObject(r.snapshot().get("world")).get("turn"));}
 @Test void contributionIsIdempotentAndDeniedPickupCannotCreateResources(){AgentRoom r=room();move(r,"E");Map<String,Object> command=AgentRoomTest.command(r,"PLAYER_ACTION",Json.object("action","pickup","arguments",Json.object("x",31,"y",10,"quantity",1)));assertEquals(200,r.command(command,10).status);String ledger=Json.write(r.snapshot().get("sharedQuest"));assertEquals(200,r.command(command,11).status);assertEquals(ledger,Json.write(r.snapshot().get("sharedQuest")));assertEquals(1,Json.asObject(r.snapshot().get("player")).get("carriedBerry"));assertEquals(409,player(r,"pickup",Json.object("x",31,"y",10,"quantity",20)).status);assertEquals(1,Json.asObject(r.snapshot().get("player")).get("carriedBerry"));}
 @Test void playerAndAgentPartialDeliveriesSumToRealSharedCompletion(){GeminiQuestScenario s=new GeminiQuestScenario("partial",true);s.enableCooperative();s.start(TaskIntent.of(s.getSession().getQuestId(),EnumSet.noneOf(TaskIntent.Constraint.class),null,null),c->new ToolRequest("obs","observe_quest",Collections.emptyMap()),Runnable::run);
  assertEquals(ActionResult.Status.SUCCESS,s.playerAction("move",Json.object("direction","E")).getStatus());assertEquals(ActionResult.Status.SUCCESS,s.playerAction("pickup",Json.object("x",31,"y",10,"quantity",1)).getStatus());
  for(String d:Arrays.asList("W","W","N","N","N","E","N","N","W"))assertEquals(ActionResult.Status.SUCCESS,s.playerAction("move",Json.object("direction",d)).getStatus());
  assertEquals("SHARED_DELIVERED",s.playerAction("deliver",Collections.emptyMap()).getCode());assertEquals(1,s.getDelivered());assertNotEquals("COMPLETED",s.getSession().getQuestStatus().name());
  Map<String,Object> state=s.exportState();Map<String,Object> a=Json.asObject(state.get("actor"));a.put("x",29);a.put("y",6);state.put("carried",2);Map<String,Object> shared=Json.asObject(state.get("cooperative"));List<Object> rows=Json.asArray(shared.get("ledger"));rows.add(Json.object("sequence",3,"actor","AGENT","action","PICKUP","quantity",2,"turn",0,"x",31,"y",10));
  GeminiQuestScenario restored=GeminiQuestScenario.restore("partial",state);restored.restoreAgent(TaskIntent.of(restored.getSession().getQuestId(),EnumSet.noneOf(TaskIntent.Constraint.class),null,null),c->new ToolRequest("obs","observe_quest",Collections.emptyMap()),Runnable::run,1000);
  assertEquals("QUEST_COMPLETED",restored.getSession().deliver(restored.getSession().getQuestId(),"professor").getCode());assertEquals(3,restored.getDelivered());Map<String,Object> totals=Json.asObject(restored.sharedQuestView().get("contributions"));assertEquals(1,Json.asObject(totals.get("PLAYER")).get("delivered"));assertEquals(2,Json.asObject(totals.get("AGENT")).get("delivered"));
 }
 @Test void cooperationDoesNotUnlockManualControlOfAiCompanion(){AgentRoom r=room();AgentRoomTest.start(r);assertEquals("AI_CONTROLS_COMPANION",r.command(AgentRoomTest.command(r,"MANUAL",Json.object("action","wait","arguments",Collections.emptyMap())),10).body.get("reasonCode"));}
 @Test void fileRestoreKeepsBothActorsInventoryAndContribution(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);AgentRoom r=new AgentRoom("persist-coop",provider(),Runnable::run,true,store);r.command(AgentRoomTest.command(r,"COOP_START",Collections.emptyMap()),0);move(r,"E");player(r,"pickup",Json.object("x",31,"y",10,"quantity",1));String shared=Json.write(r.snapshot().get("sharedQuest"));r.close();AgentRoom loaded=new AgentRoom("persist-coop",provider(),Runnable::run,true,store);assertEquals(shared,Json.write(loaded.snapshot().get("sharedQuest")));assertEquals(1,Json.asObject(loaded.snapshot().get("player")).get("carriedBerry"));assertEquals(30,Json.asObject(loaded.snapshot().get("player")).get("x"));}

 static AgentRoom positioned(WorldStore store,String owner,ProviderSelection p,int ax,int ay,int px,int py){AgentRoom base=new AgentRoom(owner,p,Runnable::run,true,store);base.command(AgentRoomTest.command(base,"COOP_START",Collections.emptyMap()),0);base.close();Map<String,Object> saved=store.load(owner),scene=Json.asObject(saved.get("scene"));Map<String,Object> a=Json.asObject(scene.get("actor"));a.put("x",ax);a.put("y",ay);Map<String,Object> player=Json.asObject(Json.asObject(scene.get("cooperative")).get("player"));player.put("x",px);player.put("y",py);store.save(owner,saved);return new AgentRoom(owner,p,Runnable::run,true,store);}
 @Test void realPendingAgentPickupLosesToPlayerWithoutDuplicatingLastResources(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);Queue<Runnable> jobs=new ArrayDeque<>();ProviderSelection p=new ProviderSelection("test","offline",1000,c->new ToolRequest("pending-pickup","pickup",Json.object("itemId","BERRY","quantity",2)),(text,q)->TaskIntent.of(q,EnumSet.noneOf(TaskIntent.Constraint.class),null,null));positioned(store,"race",p,31,10,30,11).close();AgentRoom r=new AgentRoom("race",p,jobs::add,true,store);r.command(AgentRoomTest.command(r,"PARSE",Json.object("text","一起交付3个树果")),0);jobs.remove().run();r.tick(1);r.command(AgentRoomTest.command(r,"CONFIRM",Collections.emptyMap()),2);r.tick(3);assertEquals(200,player(r,"pickup",Json.object("x",31,"y",10,"quantity",2)).status);String turn=(String)Json.asObject(r.snapshot().get("world")).get("turn");jobs.remove().run();r.tick(11);assertEquals("REPLANNING",r.snapshot().get("status"));List<Object> trace=Json.asArray(r.snapshot().get("trace"));assertEquals("RESOURCE_NOT_AVAILABLE",Json.asObject(trace.get(trace.size()-1)).get("code"));assertEquals(turn,Json.asObject(r.snapshot().get("world")).get("turn"));assertEquals("0",Json.asObject(r.snapshot().get("world")).get("carriedBerry"));assertEquals(2,Json.asObject(r.snapshot().get("player")).get("carriedBerry"));assertEquals(1,Json.asArray(Json.asObject(r.snapshot().get("sharedQuest")).get("ledger")).size());}
 @Test void agentWinningResourceRacePreventsPlayerCopy(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection p=new ProviderSelection("test","offline",1000,c->new ToolRequest("pick","pickup",Json.object("itemId","BERRY","quantity",2)),(text,q)->TaskIntent.of(q,EnumSet.noneOf(TaskIntent.Constraint.class),null,null));AgentRoom r=positioned(store,"agent-wins",p,31,10,30,11);AgentRoomTest.start(r);r.tick(3);r.tick(4);assertEquals("2",Json.asObject(r.snapshot().get("world")).get("carriedBerry"));assertEquals("RESOURCE_NOT_AVAILABLE",player(r,"pickup",Json.object("x",31,"y",10,"quantity",1)).body.get("reasonCode"));assertEquals(0,Json.asObject(r.snapshot().get("player")).get("carriedBerry"));}
 @Test void approvalFreezesPlayerWorldActionsWithoutCreditingRejectedWork(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection p=new ProviderSelection("test","offline",1000,c->new ToolRequest("ask","request_player_approval",Json.object("itemId","BERRY","quantity",1,"actionType","PURCHASE_BERRY","reason","need")),(text,q)->TaskIntent.of(q,EnumSet.of(TaskIntent.Constraint.NO_SPENDING),null,null));AgentRoom r=positioned(store,"approval-coop",p,30,6,29,11);AgentRoomTest.start(r);r.tick(3);r.tick(4);assertEquals("WAITING_APPROVAL",r.snapshot().get("status"));assertEquals("APPROVAL_FREEZE",player(r,"move",Json.object("direction","E")).body.get("reasonCode"));assertEquals("0",Json.asObject(r.snapshot().get("world")).get("turn"));assertFalse((Boolean)r.snapshot().get("playerAllowed"));}
 @Test void sharedPlayerMovementAndPickupRespectConfirmedArea(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection p=new ProviderSelection("test","offline",1000, c->new ToolRequest("obs","observe_quest",Collections.emptyMap()),(text,q)->TaskIntent.of(q,EnumSet.of(TaskIntent.Constraint.AREA_RESTRICTED),"ORCHARD_AREA",null));AgentRoom r=positioned(store,"area-coop",p,29,10,33,10);AgentRoomTest.start(r);assertEquals("AREA_RESTRICTED",player(r,"move",Json.object("direction","E")).body.get("reasonCode"));assertEquals("AREA_RESTRICTED",player(r,"pickup",Json.object("x",34,"y",10,"quantity",1)).body.get("reasonCode"));assertEquals("0",Json.asObject(r.snapshot().get("world")).get("turn"));}
 @Test void sharedDeadlineRejectsLatePlayerContribution(){ProviderSelection p=new ProviderSelection("test","offline",1000,c->new ToolRequest("obs","observe_quest",Collections.emptyMap()),(text,q)->TaskIntent.of(q,EnumSet.of(TaskIntent.Constraint.DEADLINE),null,1L));AgentRoom r=new AgentRoom("coop-deadline",p,Runnable::run,true,null);r.command(AgentRoomTest.command(r,"COOP_START",Collections.emptyMap()),0);AgentRoomTest.start(r);move(r,"E");assertEquals("FAILED",r.snapshot().get("status"));assertEquals("QUEST_NOT_ACTIVE",player(r,"pickup",Json.object("x",31,"y",10,"quantity",1)).body.get("reasonCode"));}
 @Test void corruptedContributionCannotBeRestoredAsRealInventory(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);AgentRoom r=new AgentRoom("tamper-coop",provider(),Runnable::run,true,store);r.command(AgentRoomTest.command(r,"COOP_START",Collections.emptyMap()),0);move(r,"E");player(r,"pickup",Json.object("x",31,"y",10,"quantity",1));r.close();Map<String,Object> saved=store.load("tamper-coop");List<Object> rows=Json.asArray(Json.asObject(Json.asObject(saved.get("scene")).get("cooperative")).get("ledger"));Json.asObject(rows.get(0)).put("quantity",2);store.save("tamper-coop",saved);assertThrows(IllegalArgumentException.class,()->new AgentRoom("tamper-coop",provider(),Runnable::run,true,store));}
 @Test void unknownCommittedPlayerSaveFreezesThenRecoversInventoryAndLedgerTogether(@TempDir Path dir){FileWorldStore base=new FileWorldStore(dir);boolean[] fail={false};WorldStore store=new WorldStore(){public Map<String,Object> load(String owner){return base.load(owner);}public void save(String owner,Map<String,Object> saved){base.save(owner,saved);if(fail[0])throw new StoreException(StoreException.Code.IO_ERROR);}public void close(){}};AgentRoom r=new AgentRoom("unknown-coop",provider(),Runnable::run,true,store);r.command(AgentRoomTest.command(r,"COOP_START",Collections.emptyMap()),0);move(r,"E");fail[0]=true;assertEquals(503,player(r,"pickup",Json.object("x",31,"y",10,"quantity",1)).status);assertEquals("STORAGE_ERROR",r.snapshot().get("status"));assertEquals(503,player(r,"move",Json.object("direction","W")).status);fail[0]=false;assertEquals(200,r.command(AgentRoomTest.command(r,"RECOVER",Collections.emptyMap()),12).status);assertEquals(1,Json.asObject(r.snapshot().get("player")).get("carriedBerry"));assertEquals(1,Json.asArray(Json.asObject(r.snapshot().get("sharedQuest")).get("ledger")).size());}
 @Test void playerCompletingSharedQuestInvalidatesPendingAiMutation(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);Queue<Runnable> jobs=new ArrayDeque<>();ProviderSelection p=new ProviderSelection("test","offline",1000,c->new ToolRequest("late","pickup",Json.object("itemId","BERRY","quantity",1)),(text,q)->TaskIntent.of(q,EnumSet.noneOf(TaskIntent.Constraint.class),null,null));AgentRoom base=positioned(store,"finish-coop",p,31,10,29,6);Map<String,Object> saved=store.load("finish-coop"),scene=Json.asObject(saved.get("scene")),coop=Json.asObject(scene.get("cooperative"));Json.asObject(coop.get("player")).put("carried",3);Json.asArray(coop.get("ledger")).add(Json.object("sequence",1,"actor","PLAYER","action","PICKUP","quantity",3,"turn",0,"x",31,"y",10));store.save("finish-coop",saved);base.close();AgentRoom r=new AgentRoom("finish-coop",p,jobs::add,true,store);r.command(AgentRoomTest.command(r,"PARSE",Json.object("text","交付3树果")),0);jobs.remove().run();r.tick(1);r.command(AgentRoomTest.command(r,"CONFIRM",Collections.emptyMap()),2);r.tick(3);assertEquals(200,player(r,"deliver",Collections.emptyMap()).status);assertEquals("COMPLETED",r.snapshot().get("status"));assertEquals("1",Json.asObject(r.snapshot().get("world")).get("turn"));jobs.remove().run();r.tick(12);assertEquals("0",Json.asObject(r.snapshot().get("world")).get("carriedBerry"));assertEquals(3,r.snapshot().get("delivered"));}
 @Test void postgresSharedQuestRoundTripsIndependentInventoryAndLedger()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");String owner="cooperative-pg-"+UUID.randomUUID();try(WorldStore store=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){AgentRoom r=new AgentRoom(owner,provider(),Runnable::run,true,store);r.command(AgentRoomTest.command(r,"COOP_START",Collections.emptyMap()),0);move(r,"E");player(r,"pickup",Json.object("x",31,"y",10,"quantity",1));AgentRoomTest.start(r);r.command(AgentRoomTest.command(r,"PAUSE",Collections.emptyMap()),11);String shared=Json.write(r.snapshot().get("sharedQuest"));r.close();AgentRoom restored=new AgentRoom(owner,provider(),Runnable::run,true,store);assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals(shared,Json.write(restored.snapshot().get("sharedQuest")));assertEquals(1,Json.asObject(restored.snapshot().get("player")).get("carriedBerry"));}}
 @Test void agentApproachesDifferentProfessorNeighborWhenPlayerOccupiesLandmark(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection p=new ProviderSelection("test","offline",1000,c->new ToolRequest(UUID.randomUUID().toString(),"move_to",Json.object("locationId","laboratory")),(text,q)->TaskIntent.of(q,EnumSet.noneOf(TaskIntent.Constraint.class),null,null));AgentRoom r=positioned(store,"occupied-lab",p,31,10,28,6);AgentRoomTest.start(r);for(int i=3;i<28;i++)r.tick(i);assertEquals("true",Json.asObject(r.snapshot().get("world")).get("nearProfessor"));assertEquals(28,Json.asObject(r.snapshot().get("player")).get("x"));assertEquals(6,Json.asObject(r.snapshot().get("player")).get("y"));assertNotEquals("FAILED",r.snapshot().get("status"));}
}
