package game.agent.eval;
import game.agent.llm.Json;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class DuelEvaluationTest {
 static Map<String,Object> spec(int seed){return Json.object("id","battle-eval","scenario","battle","seed",seed,"model","baseline","starter","MUDKIP","repetition",1,"decisions",100,"wallMillis",60000,"price",Collections.emptyMap());}
 @Test void battleScenarioCompletesWithSeededReplayAndWinMetrics(){EvaluationRun a=new EvaluationRun(spec(11)),b=new EvaluationRun(spec(11));assertEquals(a.report(false).get("initialFingerprint"),b.report(false).get("initialFingerprint"));a.resume(EvaluationRun.baseline(),Runnable::run,1000);for(int n=1;n<400&&!a.terminal();n++)a.tick(n*10);assertTrue(a.terminal());assertEquals("COMPLETED",a.status());Map<String,Object> metrics=Json.asObject(a.report(true).get("metrics"));assertNotNull(metrics.get("battleResult"));assertNotNull(metrics.get("battleWin"));assertFalse(Json.asArray(a.report(true).get("trace")).isEmpty());}
 @Test void battleCheckpointAndResumePreserveLockedActionsAndRandomCursor(){EvaluationRun a=new EvaluationRun(spec(23));a.resume(EvaluationRun.baseline(),Runnable::run,1000);for(int n=1;n<7;n++)a.tick(n*10);a.pause();EvaluationRun restored=EvaluationRun.restore(Json.asObject(Json.read(Json.write(a.checkpoint()))));assertEquals(a.report(true).get("finalFingerprint"),restored.report(true).get("finalFingerprint"));restored.resume(EvaluationRun.baseline(),Runnable::run,1000);for(int n=1;n<400&&!restored.terminal();n++)restored.tick(n*10);assertEquals("COMPLETED",restored.status());}
 @Test void resumingForcedSwitchMustStillAllowMovesAfterReplacement(){EvaluationRun a=new EvaluationRun(spec(23));Map<String,Object> save=a.checkpoint(),world=Json.asObject(save.get("world"));Json.asObject(Json.asArray(Json.asArray(world.get("teams")).get(0)).get(0)).put("hp",0);EvaluationRun restored=EvaluationRun.restore(save);restored.resume(EvaluationRun.baseline(),Runnable::run,1000);for(int n=1;n<400&&!restored.terminal();n++)restored.tick(n*10);assertEquals("COMPLETED",restored.status(),Json.write(restored.report(false)));}
 @Test void resumingWithLockedChoiceMustAllowNextRoundTools(){EvaluationRun a=new EvaluationRun(spec(11));Map<String,Object> save=a.checkpoint(),world=Json.asObject(save.get("world"));game.agent.duel.DuelBattle battle=game.agent.duel.DuelBattle.restore(world);battle.submit(0,new game.agent.tools.ToolRequest("locked","battle_move",Json.object("moveId",battle.moves(0).get(0))));save.put("world",battle.export());EvaluationRun restored=EvaluationRun.restore(save);restored.resume(EvaluationRun.baseline(),Runnable::run,1000);for(int n=1;n<400&&!restored.terminal();n++)restored.tick(n*10);assertEquals("COMPLETED",restored.status(),Json.write(restored.report(false)));}
}
