package game.agent.duel;
import game.agent.growth.*;import game.agent.llm.Json;import game.agent.tools.*;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class DuelBattleTest {
 static ToolRequest move(String id){return new ToolRequest("move", "battle_move",Json.object("moveId",id));}
 static ToolRequest swap(int slot){return new ToolRequest("swap","battle_switch",Json.object("slot",slot));}
 @Test void choicesHiddenAndRejectedActionsDoNotAdvanceOrSpendPp(){DuelBattle d=new DuelBattle(DuelBattle.demoTeam(),DuelBattle.demoTeam(),11);assertEquals("MOVE_UNAVAILABLE",d.submit(0,move("HYPER_BEAM")));assertEquals(0,d.round());assertFalse(d.observation(0).get("opponentActive").contains("pp"));assertFalse(d.observation(0).get("ownTeam").contains("captureId"));assertTrue(d.observation(0).get("opponentRevealed").contains("hidden"));assertEquals("CHOICE_ACCEPTED",d.submit(1,move(d.moves(1).get(0))));assertFalse(d.view(0).containsKey("choices"));assertEquals(0,d.round());assertEquals("CHOICE_NOT_ALLOWED",d.submit(1,move(d.moves(1).get(0))));assertEquals("CHOICE_ACCEPTED",d.submit(0,move(d.moves(0).get(0))));assertEquals(1,d.round());}
 @Test void fixedSeedAndReloadContinueIdenticalResolution(){DuelBattle a=new DuelBattle(DuelBattle.demoTeam(),DuelBattle.demoTeam(),23),b=new DuelBattle(DuelBattle.demoTeam(),DuelBattle.demoTeam(),23);for(int n=0;n<20&&a.result().equals("ACTIVE");n++){for(int s=0;s<2;s++)if(a.needsChoice(s)){ToolRequest choice=a.moves(s).isEmpty()?swap(a.switches(s).get(0)):move(a.moves(s).get(0));a.submit(s,choice);b.submit(s,choice);}b=DuelBattle.restore(Json.asObject(Json.read(Json.write(b.export()))));assertEquals(Json.write(a.export()),Json.write(b.export()));}}
 @Test void startingBattleNeverMutatesOwnedPartner(){List<GrowthPokemon> owned=DuelBattle.demoTeam();owned.get(0).hurt(8);owned.get(0).pp.put(owned.get(0).pp.keySet().iterator().next(),0);String original=Json.write(owned.get(0).export());new DuelBattle(owned,DuelBattle.demoTeam(),35);assertEquals(original,Json.write(owned.get(0).export()));}
 @Test void invalidSwitchAndCrossSideRejected(){DuelBattle d=new DuelBattle(DuelBattle.demoTeam(),DuelBattle.demoTeam(),11);assertEquals("SWITCH_UNAVAILABLE",d.submit(0,swap(0)));assertThrows(IllegalArgumentException.class,()->d.submit(2,swap(1)));assertEquals("INVALID_BATTLE_ACTION",d.submit(0,new ToolRequest("bad","battle_move",Json.object("moveId","TACKLE","side",1))));}
 @Test void depletedPpOnlyAllowsStruggleAndForcedSwitchIsFree(){List<GrowthPokemon> a=DuelBattle.demoTeam();for(GrowthPokemon p:a)for(String id:p.pp.keySet())p.pp.put(id,0);DuelBattle d=new DuelBattle(a,DuelBattle.demoTeam(),11);Map<String,Object> save=d.export();List<Object> team=Json.asArray(Json.asArray(save.get("teams")).get(0));Map<String,Object> first=Json.asObject(team.get(0));for(String id:Json.asObject(first.get("pp")).keySet())Json.asObject(first.get("pp")).put(id,0);d=DuelBattle.restore(save);assertEquals(Collections.singletonList("STRUGGLE"),d.moves(0));first.put("hp",0);d=DuelBattle.restore(save);assertTrue(d.needsChoice(0));assertFalse(d.needsChoice(1));assertEquals("CHOICE_ACCEPTED",d.submit(0,swap(1)));assertEquals(0,d.round());assertEquals(1,d.trace().size());}
}
