package game.agent.web;
import game.agent.llm.*;import game.agent.eval.*;import game.agent.persistence.*;import game.agent.tools.*;import java.nio.file.Path;import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import static org.junit.jupiter.api.Assertions.*;
class DuelRoomTest {
 @Test void preparationMetadataMatchesRealBattleAndPreservesOwnedPokemon(){
  game.agent.growth.GrowthPokemon p=new game.agent.growth.GrowthPokemon(UUID.randomUUID().toString(),"MUDKIP",20);String before=Json.write(p.export());
  DuelRoom r=new DuelRoom("preview",offline(),providers(),Runnable::run,null,()->Collections.singletonList(p));Map<String,Object> idle=r.snapshot();
  assertEquals("MUDKIP",Json.asObject(Json.asArray(idle.get("teamOptions")).get(0)).get("species"));
  Map<String,Object> previews=Json.asObject(idle.get("opponentPreviews"));assertEquals(3,Json.asArray(previews.get("standard")).size());
  Map<String,Object> rookie=Json.asObject(Json.asObject(previews.get("rookieByPartner")).get(p.captureId));assertEquals("POOCHYENA",rookie.get("species"));assertEquals(8,rookie.get("level"));assertFalse(rookie.containsKey("moves"));
  Map<String,Object> config=start("manual");config.put("difficulty","rookie");config.put("teamIds",Collections.singletonList(p.captureId));assertEquals(200,r.command(request(r,"START",config),0).status);
  Map<String,Object> active=Json.asObject(Json.asObject(r.snapshot().get("world")).get("opponentActive"));assertEquals(rookie.get("species"),active.get("species"));assertEquals(rookie.get("level"),active.get("level"));assertEquals(before,Json.write(p.export()));
 }
 static ProviderSelection offline(){return new ProviderSelection("disabled","unavailable",1000,null,null);}
 static EvaluationProviders providers(){return new EvaluationProviders(Collections.singletonList("baseline"),1000,m->DuelRoom::baseline);}
 static Map<String,Object> request(DuelRoom r,String c,Map<String,Object> p){return Json.object("requestId",UUID.randomUUID().toString(),"taskId",r.snapshot().get("taskId"),"expectedRevision",r.snapshot().get("revision"),"command",c,"params",p);}
 static Map<String,Object> start(String mode){return Json.object("mode",mode,"seed",11,"leftModel","baseline","rightModel","baseline","teamIds",Collections.emptyList());}
 @Test void autoBattleCompletesAndFileRestartPreservesTrace(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);DuelRoom room=new DuelRoom("file",offline(),providers(),Runnable::run,store,Collections::emptyList);Map<String,Object> initial=request(room,"START",start("auto"));assertEquals(200,room.command(initial,0).status);for(int n=0;n<300&&room.snapshot().get("status").equals("RUNNING");n++)room.tick(n*100);assertEquals("COMPLETED",room.snapshot().get("status"));DuelRoom loaded=new DuelRoom("file",offline(),providers(),Runnable::run,store,Collections::emptyList);assertEquals(Json.write(room.snapshot().get("trace")),Json.write(loaded.snapshot().get("trace")));assertEquals(200,loaded.command(initial,50000).status);}
 @Test void repeatedCommandCannotRepeatBattleAction(){DuelRoom r=new DuelRoom("idem",offline(),providers(),Runnable::run,null,Collections::emptyList);r.command(request(r,"START",start("manual")),0);Map<String,Object> command=request(r,"ACTION",Json.object("tool","battle_move","arguments",Json.object("moveId",Json.asArray(Json.asObject(r.snapshot().get("world")).get("legalMoves")).get(0))));assertEquals(200,r.command(command,1).status);String view=Json.write(r.snapshot().get("world"));assertEquals(200,r.command(command,1).status);assertEquals(view,Json.write(r.snapshot().get("world")));}
 @Test void timeoutPausesAndLateDecisionCannotChangeBattle(){List<Runnable> work=new ArrayList<>();ProviderSelection p=new ProviderSelection("fake","slow",1000,c->DuelRoom.baseline(c),null);DuelRoom r=new DuelRoom("late",p,providers(),work::add,null,Collections::emptyList);Map<String,Object> params=start("auto");params.put("leftModel","slow");r.command(request(r,"START",params),0);r.tick(0);r.tick(3000);assertEquals("PAUSED",r.snapshot().get("status"));String before=Json.write(r.snapshot().get("world"));for(Runnable job:work)job.run();r.tick(4000);assertEquals(before,Json.write(r.snapshot().get("world")));assertEquals(200,r.command(request(r,"MANUAL",Collections.emptyMap()),5000).status);}
 @Test void opponentPendingActionIsNotExposedBeforeRoundResolution(){DuelRoom r=new DuelRoom("privacy",offline(),providers(),Runnable::run,null,Collections::emptyList);r.command(request(r,"START",start("manual")),0);r.tick(0);r.tick(1);Map<String,Object> decision=Json.asObject(Json.asArray(r.snapshot().get("decisions")).get(0));assertFalse(decision.containsKey("arguments"));assertFalse(decision.containsKey("tool"));}
 @Test void runningRestartRequiresExplicitResume(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);DuelRoom r=new DuelRoom("pause",offline(),providers(),Runnable::run,store,Collections::emptyList);r.command(request(r,"START",start("auto")),0);DuelRoom reload=new DuelRoom("pause",offline(),providers(),Runnable::run,store,Collections::emptyList);assertEquals("PAUSED",reload.snapshot().get("status"));assertEquals(200,reload.command(request(reload,"RESUME",Collections.emptyMap()),0).status);}
 @Test void failedCommandCannotBeAcknowledgedAsSavedByRetryAndRecoveryUsesCommittedState(){
  class Store implements WorldStore {Map<String,Object> saved;boolean fail;public Map<String,Object> load(String owner){return saved==null?null:Json.asObject(Json.read(Json.write(saved)));}public void save(String owner,Map<String,Object> v){if(fail)throw new StoreException(StoreException.Code.IO_ERROR);saved=Json.asObject(Json.read(Json.write(v)));}public void close(){}}
  Store store=new Store();DuelRoom r=new DuelRoom("failure",offline(),providers(),Runnable::run,store,Collections::emptyList);store.fail=true;Map<String,Object> command=request(r,"START",start("auto"));assertEquals(503,r.command(command,0).status);assertEquals(503,r.command(command,0).status);store.fail=false;assertEquals(200,r.command(request(r,"RECOVER",Collections.emptyMap()),1).status);assertEquals("IDLE",r.snapshot().get("status"));assertEquals(200,r.command(request(r,"START",start("auto")),2).status);
 }
 @Test void unavailableSavedProviderRestoresThenPausesWithoutLosingBattle(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection old=new ProviderSelection("fake","retired",1000,c->DuelRoom.baseline(c),null);DuelRoom r=new DuelRoom("retired",old,providers(),Runnable::run,store,Collections::emptyList);Map<String,Object> config=start("auto");config.put("leftModel","retired");r.command(request(r,"START",config),0);DuelRoom reload=new DuelRoom("retired",offline(),providers(),Runnable::run,store,Collections::emptyList);assertEquals("PAUSED",reload.snapshot().get("status"));reload.command(request(reload,"RESUME",Collections.emptyMap()),0);reload.tick(1);assertEquals("PAUSED",reload.snapshot().get("status"));assertEquals("PROVIDER_CONFIGURATION",reload.snapshot().get("errorCode"));}
 @Test void malformedModelActionsPauseAfterThreeFailuresInsteadOfCrashingWorld(){LlmGateway bad=c->new ToolRequest("bad","battle_move",Json.object("moveId","INVALID"));ProviderSelection p=new ProviderSelection("fake","bad",1000,bad,null);DuelRoom r=new DuelRoom("bad",p,providers(),Runnable::run,null,Collections::emptyList);Map<String,Object> config=start("auto");config.put("leftModel","bad");r.command(request(r,"START",config),0);for(int i=0;i<10;i++)r.tick(i);assertEquals("PAUSED",r.snapshot().get("status"));assertNotEquals("COMPLETED",r.snapshot().get("status"));}
 @Test void cancellingInFlightRealRequestMarksUsageIncompleteAndBlocksPaidResume(){List<Runnable> work=new ArrayList<>();ProviderSelection p=new ProviderSelection("fake","slow",1000,c->DuelRoom.baseline(c),null);DuelRoom r=new DuelRoom("cost",p,providers(),work::add,null,Collections::emptyList);Map<String,Object> params=start("auto");params.put("leftModel","slow");r.command(request(r,"START",params),0);r.tick(0);assertEquals(200,r.command(request(r,"PAUSE",Collections.emptyMap()),1).status);assertEquals(true,r.snapshot().get("usageIncomplete"));assertEquals(409,r.command(request(r,"RESUME",Collections.emptyMap()),2).status);assertEquals(200,r.command(request(r,"MANUAL",Collections.emptyMap()),3).status);}
 @Test void reloadedOpponentLockedChoiceRemainsHidden(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);DuelRoom r=new DuelRoom("hidden-reload",offline(),providers(),Runnable::run,store,Collections::emptyList);r.command(request(r,"START",start("manual")),0);r.tick(0);r.tick(1);r.command(request(r,"PAUSE",Collections.emptyMap()),2);DuelRoom restored=new DuelRoom("hidden-reload",offline(),providers(),Runnable::run,store,Collections::emptyList);Map<String,Object> decision=Json.asObject(Json.asArray(restored.snapshot().get("decisions")).get(0));assertFalse(decision.containsKey("arguments"));assertFalse(decision.containsKey("tool"));}
 @Test void stoppingCurrentTaskAcceptsOlderSnapshotButNeverFutureOrOtherTask(){DuelRoom r=new DuelRoom("stop",offline(),providers(),Runnable::run,null,Collections::emptyList);r.command(request(r,"START",start("auto")),0);Map<String,Object> pause=request(r,"PAUSE",Collections.emptyMap());r.tick(1);assertEquals(200,r.command(pause,2).status);Map<String,Object> future=request(r,"CANCEL",Collections.emptyMap());future.put("expectedRevision",999999);assertEquals(409,r.command(future,3).status);Map<String,Object> other=request(r,"CANCEL",Collections.emptyMap());other.put("taskId",UUID.randomUUID().toString());assertEquals(409,r.command(other,3).status);}

 @Test void rookieMatchUsesOwnedStarterAgainstOneLowLevelOpponentAndNoPaidCalls(){
  game.agent.growth.GrowthPokemon p=new game.agent.growth.GrowthPokemon(UUID.randomUUID().toString(),"MUDKIP",6);String before=Json.write(p.export());
  DuelRoom r=new DuelRoom("rookie",offline(),providers(),Runnable::run,null,()->Collections.singletonList(p));Map<String,Object> config=start("manual");config.put("difficulty","rookie");config.put("teamIds",Collections.singletonList(p.captureId));
  assertEquals(200,r.command(request(r,"START",config),0).status);Map<String,Object> world=Json.asObject(r.snapshot().get("world"));assertEquals(1,Json.asArray(world.get("ownTeam")).size());assertEquals(p.captureId,Json.asObject(Json.asArray(world.get("ownTeam")).get(0)).get("captureId"));assertEquals(5,Json.asObject(world.get("opponentActive")).get("level"));
  for(int i=0;i<150&&"RUNNING".equals(r.snapshot().get("status"));i++){r.tick(i*10);Map<String,Object> w=Json.asObject(r.snapshot().get("world"));if(Boolean.TRUE.equals(w.get("canChoose")))r.command(request(r,"ACTION",Json.object("tool","battle_move","arguments",Json.object("moveId",Json.asArray(w.get("legalMoves")).get(0)))),i*10);}
  assertEquals("COMPLETED",r.snapshot().get("status"));assertEquals(before,Json.write(p.export()));assertEquals(0,((Number)r.snapshot().get("tokens")).intValue());
  config.put("mode","auto");assertEquals(400,r.command(request(r,"START",config),2000).status);
 }
}
