package game.agent.web;
import game.agent.growth.*;import game.agent.combat.*;import game.agent.llm.*;import game.agent.persistence.*;import game.agent.tools.*;import game.items.balls.Pokeball;
import edu.monash.fit2099.engine.positions.*;import game.environments.Dirt;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;import java.util.*;import static org.junit.jupiter.api.Assertions.*;

class FieldGrowthTest {
 static GrowthPokemon mon(String species,int level){return new GrowthPokemon(UUID.randomUUID().toString(),species,level);}
 static GameMap flat(){GameMap map=new GameMap(new FancyGroundFactory(new Dirt()),Collections.nCopies(15,String.join("",Collections.nCopies(40,"."))));new World(new edu.monash.fit2099.engine.displays.Display()).addGameMap(map);return map;}
 static AgentRoom.Reply send(AgentRoom r,String command,Map<String,Object> params){Map<String,Object> v=r.snapshot();return r.command(Json.object("requestId",UUID.randomUUID().toString(),"taskId",v.get("taskId"),"expectedRevision",v.get("revision"),"command",command,"params",params),0);}
 static AgentRoom.Reply skill(AgentRoom r,String target,String move){return send(r,"WILD_ACTION",Json.object("action","use_skill","arguments",Json.object("targetId",target,"moveId",move)));}
 static AgentRoom prepare(WorldStore s,String owner,GrowthPokemon p){assertEquals("ACCEPTED",new PokemonCollection(owner,s).receive(p.captureId,new Pokeball().capturePokemon(p)));AgentRoom r=new AgentRoom(owner,GrowthCarryTest.offline(),Runnable::run,true,s);assertEquals(200,send(r,"EXPLORE",Collections.emptyMap()).status);assertEquals(200,send(r,"SUMMON",Json.object("captureId",p.captureId,"direction","E")).status);assertEquals(200,send(r,"PARTNER",Json.object("captureId",p.captureId)).status);assertEquals(200,send(r,"WILD_ACTION",Json.object("action","move","arguments",Json.object("direction","E"))).status);return r;}
 static Map<String,Object> profile(AgentRoom r){return Json.asObject(Json.asObject(r.snapshot().get("summoned")).get("growth"));}
 @Test void rejectedSkillsNeverConvertTargetsSpendPPOrGrantExperience(){GameMap map=flat();WildEncounter w=WildEncounter.spawn(map,()->0);GrowthPokemon p=mon("MUDKIP",16);map.addActor(p,map.at(30,10));String before=Json.write(w.exportState()),original=Json.write(p.export());assertEquals("OUT_OF_REACH",w.useSkill(p,"field-torchic","WATER_GUN",false,l->true).getCode());map.moveActor(p,map.at(35,10));assertEquals("NO_ACTIVE_BATTLE",w.useSkill(p,"field-torchic","WATER_GUN",true,l->true).getCode());assertEquals("AREA_RESTRICTED",w.useSkill(p,"field-torchic","WATER_GUN",false,l->false).getCode());assertEquals("MOVE_NOT_EQUIPPED",w.useSkill(p,"field-torchic","EMBER",false,l->true).getCode());assertEquals(before,Json.write(w.exportState()));assertEquals(original,Json.write(p.export()));p.pp.put("WATER_GUN",0);assertEquals("NO_PP",w.useSkill(p,"field-torchic","WATER_GUN",false,l->true).getCode());assertEquals(before,Json.write(w.exportState()));}
 @Test void defeatSettlesRealExperienceOnceAndLegacyAttackCannotBypassPP(){GameMap map=flat();WildEncounter w=WildEncounter.spawn(map,()->0);GrowthPokemon p=mon("MUDKIP",16);map.addActor(p,map.at(35,10));int xp=p.experience,pp=p.pp.get("WATER_GUN");assertEquals("USE_SKILL_REQUIRED",w.action(p,"attack","field-torchic",false,l->true,0).getCode());assertEquals("TARGET_DEFEATED",w.useSkill(p,"field-torchic","WATER_GUN",false,l->true).getCode());assertEquals(pp-1,p.pp.get("WATER_GUN"));assertEquals(xp+GrowthRules.reward("TORCHIC",5),p.experience);assertEquals("TARGET_UNAVAILABLE",w.useSkill(p,"field-torchic","WATER_GUN",false,l->true).getCode());assertEquals(xp+GrowthRules.reward("TORCHIC",5),p.experience);Map<String,Object> save=Json.asObject(Json.read(Json.write(w.exportState())));WildEncounter restored=WildEncounter.restore(flat(),save);assertEquals("DEFEATED",restored.state("field-torchic").get("state"));}
 @Test void statusAndConvertedTargetPPPersistWithoutFreeCaptureExperience(){GameMap map=flat();WildEncounter w=WildEncounter.spawn(map,()->0);GrowthPokemon p=mon("MUDKIP",5);map.addActor(p,map.at(31,10));p.burned=true;int hp=p.getHitPoints(),xp=p.experience;assertEquals("SKILL_USED",w.useSkill(p,"field-treecko","GROWL",false,l->true).getCode());Map<String,Object> row=w.state("field-treecko");assertEquals(5,row.get("level"));assertEquals(-1,Json.asObject(row.get("growth")).get("attackStage"));assertTrue(p.getHitPoints()<hp);WildEncounter restored=WildEncounter.restore(flat(),Json.asObject(Json.read(Json.write(w.exportState()))));assertEquals(row,restored.state("field-treecko"));map.moveActor(p,map.at(32,10));assertEquals("CAPTURED",w.action(p,"capture","field-treecko",false,l->true,0).getCode());assertEquals(xp,p.experience);assertTrue(w.ball("field-treecko").getPokemon() instanceof GrowthPokemon);map.moveActor(p,map.at(35,10));assertEquals("NOT_CAPTURABLE",w.action(p,"capture","field-torchic",false,l->true,0).getCode());}
 static void recoverProfile(WorldStore store,String owner){GrowthPokemon p=mon("MUDKIP",16);p.pp.put("WATER_GUN",3);p.burned=true;AgentRoom r=prepare(store,owner,p);assertEquals(200,skill(r,"field-treecko","WATER_GUN").status);Map<String,Object> expected=profile(r);assertEquals(2,Json.asObject(expected.get("pp")).get("WATER_GUN"));r.close();r=new AgentRoom(owner,GrowthCarryTest.offline(),Runnable::run,true,store);assertEquals(expected,profile(r));assertEquals(200,send(r,"RECALL",Json.object("captureId",p.captureId)).status);assertEquals(expected,((GrowthPokemon)new PokemonCollection(owner,store).ball(p.captureId).getPokemon()).export());GrowthRoom growth=new GrowthRoom(owner,GrowthCarryTest.offline(),Runnable::run,store,()->0);assertEquals(200,GrowthReturnTest.command(growth,"RETURN_GROWTH",p.captureId).status);Map<String,Object> returned=Json.asObject(Json.asObject(growth.snapshot().get("world")).get("partner"));GrowthPokemon evolved=GrowthPokemon.restore(expected);assertEquals("EVOLVED",evolved.evolve());assertEquals("MARSHTOMP",returned.get("species"));for(String k:expected.keySet())assertEquals(evolved.export().get(k),returned.get(k));}
 @Test void completeGrowthProfileSurvivesFieldRestartRecallAndReturn(@TempDir Path dir){recoverProfile(new FileWorldStore(dir),"field-file");}
 @Test void faintedDeployedGrowthPartnerRestoresAndCanBeRecalled(@TempDir Path dir){WorldStore s=new FileWorldStore(dir);GrowthPokemon p=mon("MUDKIP",5);p.hurt(p.maxHp()-1);AgentRoom r=prepare(s,"faint",p);assertEquals(200,skill(r,"field-treecko","GROWL").status);assertEquals(0,profile(r).get("hp"));r.close();r=new AgentRoom("faint",GrowthCarryTest.offline(),Runnable::run,true,s);assertEquals(0,profile(r).get("hp"));assertEquals(200,send(r,"RECALL",Json.object("captureId",p.captureId)).status);}
 @Test void failedBattleCheckpointRollsBackProfileAndTargetTogether(@TempDir Path dir){FileWorldStore base=new FileWorldStore(dir);boolean[] fail={false};WorldStore s=new WorldStore(){public Map<String,Object> load(String o){return base.load(o);}public void save(String o,Map<String,Object> v){if(fail[0]&&o.equals("fault"))throw new StoreException(StoreException.Code.IO_ERROR);base.save(o,v);}public void close(){}};AgentRoom r=prepare(s,"fault",mon("MUDKIP",16));Map<String,Object> before=profile(r);String wild=Json.write(r.snapshot().get("wild"));fail[0]=true;assertEquals(503,skill(r,"field-treecko","WATER_GUN").status);fail[0]=false;assertEquals(200,send(r,"RECOVER",Collections.emptyMap()).status);assertEquals(before,profile(r));assertEquals(wild,Json.write(r.snapshot().get("wild")));}
 @Test void postgresKeepsCompleteGrowthProfileAcrossScenes()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");try(WorldStore s=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){recoverProfile(s,"field-pg-"+UUID.randomUUID());}}
 static void aiRun(WorldStore store,String owner,boolean mixed){
  GrowthPokemon p=mon("MUDKIP",16);assertEquals("ACCEPTED",new PokemonCollection(owner,store).receive(p.captureId,new Pokeball().capturePokemon(p)));
  List<Map<String,Object>> steps=mixed?Arrays.asList(Json.object("kind","COMPLETE_QUEST","targetId",null),Json.object("kind","DEFEAT","targetId","field-torchic")):Arrays.asList(Json.object("kind","DEFEAT","targetId","field-treecko"),Json.object("kind","DEFEAT","targetId","field-torchic"));
  ProviderSelection provider=new ProviderSelection("test","offline",1000,c->{Map<String,String> o=c.getObservation();String op=o.get("suggestedAction");Map<String,Object> args;
   if("COMPLETE_QUEST".equals(o.get("goalType"))){int carried=Integer.parseInt(o.get("carriedBerry")),visible=Integer.parseInt(o.get("visibleBerry"));if(carried>=3&&"true".equals(o.get("nearProfessor"))){op="deliver";args=Json.object("questId",o.get("questId"),"targetNpcId","professor");}else if(carried<3&&visible>0){op="pickup";args=Json.object("itemId","BERRY","quantity",Math.min(3-carried,visible));}else{op="move_to_location";args=Json.object("locationId",carried>=3?"laboratory":carried>=2?"alternative":"orchard");}}
   else{args=Json.object("targetId",o.get("goalTarget"));if("use_skill".equals(op)){assertNotNull(o.get("growthPartner"));args.put("moveId","field-torchic".equals(o.get("goalTarget"))?"WATER_GUN":"TACKLE");}}
   return new ToolRequest(UUID.randomUUID().toString(),op,args);
  },(text,q)->mixed?TaskIntent.ofMixed(q,steps,EnumSet.of(TaskIntent.Constraint.NO_SPENDING),null,null):TaskIntent.ofSequence(q,steps,EnumSet.of(TaskIntent.Constraint.NO_SPENDING),null,null));
  AgentRoom room=new AgentRoom(owner,provider,Runnable::run,true,store);assertEquals(200,send(room,"PARSE",Json.object("text","ordered growth battle","captureId",p.captureId)).status);room.tick(1);assertEquals("READY",room.snapshot().get("status"));assertEquals(200,send(room,"CONFIRM",Collections.emptyMap()).status);
  for(int n=2;n<220&&!Arrays.asList("COMPLETED","FAILED","PAUSED").contains(room.snapshot().get("status"));n++)room.tick(n);
  assertEquals("COMPLETED",room.snapshot().get("status"),Json.write(room.snapshot()));assertEquals(mixed?3:0,room.snapshot().get("delivered"));assertEquals("5",Json.asObject(room.snapshot().get("world")).get("coins"));
  Map<String,Object> after=profile(room);assertTrue(((Number)after.get("experience")).intValue()>GrowthRules.experienceAt(16));assertTrue(((Number)Json.asObject(after.get("pp")).get("WATER_GUN")).intValue()<25);assertTrue(Json.write(room.snapshot().get("stepTrace")).contains("use_skill"));
  room.close();assertEquals(after,profile(new AgentRoom(owner,provider,Runnable::run,true,store)));
 }
 @Test void aiGrowthPartnerCompletesOrderedDefeatsAndRestores(@TempDir Path dir){aiRun(new FileWorldStore(dir),"sequence-growth",false);}
 @Test void aiGrowthPartnerSwitchesToLeaderForBerriesAndBackForSkills(@TempDir Path dir){aiRun(new FileWorldStore(dir),"mixed-growth",true);}
 @Test void legacyPartnerFinishingConvertedTargetClearsBattleCheckpoint(){GameMap map=flat();WildEncounter wild=WildEncounter.spawn(map,()->0);GrowthPokemon grown=mon("MUDKIP",5);map.addActor(grown,map.at(31,10));wild.useSkill(grown,"field-treecko","GROWL",false,l->true);map.removeActor(grown);game.actors.pokemon.Pokemon legacy=PokemonSpecies.create("MUDKIP");map.addActor(legacy,map.at(31,10));for(int n=0;n<25&&"WILD".equals(wild.state("field-treecko").get("state"));n++)wild.action(legacy,"attack","field-treecko",false,l->true,0);assertEquals("DEFEATED",wild.state("field-treecko").get("state"));assertNull(wild.exportState().get("battleTarget"));WildEncounter.restore(flat(),Json.asObject(Json.read(Json.write(wild.exportState()))));}
}
