package game.agent;
import game.agent.web.*;import game.agent.llm.*;import game.agent.tools.*;import game.agent.runtime.*;import game.agent.demo.*;import game.agent.persistence.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import static org.junit.jupiter.api.Assertions.*;
class FieldAgentTest {
 static TaskIntent intent(String kind,String target,TaskIntent.Constraint...cs){return TaskIntent.ofGoal("unused",kind,target,cs.length==0?EnumSet.noneOf(TaskIntent.Constraint.class):EnumSet.copyOf(Arrays.asList(cs)),null,null);}
 static ProviderSelection provider(String kind,String target,Set<TaskIntent.Constraint> cs,String area,Long deadline, AtomicInteger calls){
  LlmGateway gateway=context->{calls.incrementAndGet();Map<String,String> obs=context.getObservation();assertTrue(obs.containsKey("targets"));
   Map<String,Object> row=null;for(Object value:Json.asArray(Json.read(obs.get("targets")))){Map<String,Object> t=Json.asObject(value);if(target.equals(t.get("id")))row=t;}assertNotNull(row);
   int x=Integer.parseInt(obs.get("x")),y=Integer.parseInt(obs.get("y"));boolean close=Math.max(Math.abs(x-((Number)row.get("x")).intValue()),Math.abs(y-((Number)row.get("y")).intValue()))==1;
   return new ToolRequest(UUID.randomUUID().toString(),close?("CAPTURE".equals(kind)?"capture":"attack"):"move_to",Json.object("targetId",target));};
  return new ProviderSelection("test","offline",1000,gateway,(text,quest)->TaskIntent.ofGoal(quest,kind,target,cs,area,deadline));
 }
 static void parse(AgentRoom room){assertEquals(200,room.command(AgentRoomTest.command(room,"PARSE",Json.object("text","目标")),0).status);room.tick(1);assertEquals("READY",room.snapshot().get("status"));}
 static void start(AgentRoom room){parse(room);assertEquals(200,room.command(AgentRoomTest.command(room,"CONFIRM",Collections.emptyMap()),2).status);}
 static Map<String,Object> target(AgentRoom room,String id){return Json.asArray(room.snapshot().get("wild")).stream().map(Json::asObject).filter(t->id.equals(t.get("id"))).findFirst().get();}
 @Test void parsingDoesNotSpawnAndConfirmedCaptureCompletesFromNativeStateWithoutBerryDelivery(){AtomicInteger calls=new AtomicInteger();AgentRoom room=new AgentRoom("field",provider("CAPTURE","field-treecko",EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE,TaskIntent.Constraint.NO_SPENDING),null,null,calls),Runnable::run,true,null);parse(room);assertEquals(0,Json.asArray(room.snapshot().get("wild")).size());assertEquals("0",Json.asObject(room.snapshot().get("world")).get("turn"));assertEquals("CAPTURE",room.snapshot().get("taskKind"));assertEquals(200,room.command(AgentRoomTest.command(room,"CONFIRM",Collections.emptyMap()),2).status);
  for(int i=3;i<35&&!"COMPLETED".equals(room.snapshot().get("status"));i++)room.tick(i);assertEquals("COMPLETED",room.snapshot().get("status"));assertEquals("CAPTURED",target(room,"field-treecko").get("state"));assertEquals(0,room.snapshot().get("delivered"));assertEquals("5",Json.asObject(room.snapshot().get("world")).get("coins"));String turn=(String)Json.asObject(room.snapshot().get("world")).get("turn");room.tick(40);assertEquals(turn,Json.asObject(room.snapshot().get("world")).get("turn"));
  assertEquals(200,room.command(AgentRoomTest.command(room,"STORE_WILD",Json.object("targetId","field-treecko")),41).status);
 }
 @Test void observationAndAlreadyAdjacentNavigationNeverConsumeWorldTurns(){GeminiQuestScenario scene=new GeminiQuestScenario("obs",true);TaskIntent t=TaskIntent.ofGoal(scene.getSession().getQuestId(),"CAPTURE","field-treecko",EnumSet.noneOf(TaskIntent.Constraint.class),null,null);AgentLoop loop=scene.start(t,context->new ToolRequest("observe","observe",Collections.emptyMap()),Runnable::run);loop.tick(1);assertEquals("FIELD_OBSERVED",loop.tick(2).getCode());assertEquals(0,scene.getSession().getTurn());}
 @Test void fieldWhitelistNeverExposesPurchasesBerryDeliveryOrAttacksUnderNoBattle(){GeminiQuestScenario scene=new GeminiQuestScenario("white",true);TaskIntent t=TaskIntent.ofGoal(scene.getSession().getQuestId(),"CAPTURE","field-treecko",EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE),null,null);AtomicReference<List<String>> tools=new AtomicReference<>();AgentLoop loop=scene.start(t,c->{List<String> names=new ArrayList<>();c.getTools().forEach(d->names.add(d.getName()));tools.set(names);return new ToolRequest("attack","attack",Json.object("targetId","field-treecko"));},Runnable::run);loop.tick(1);assertEquals("UNKNOWN_TOOL",loop.tick(2).getCode());assertEquals(Arrays.asList("observe","move_to","capture"),tools.get());}
 @Test void wrongGoalTargetCannotBeAttackedOrCaptured(){GeminiQuestScenario scene=new GeminiQuestScenario("target",true);AgentLoop loop=scene.start(TaskIntent.ofGoal(scene.getSession().getQuestId(),"CAPTURE","field-treecko",EnumSet.noneOf(TaskIntent.Constraint.class),null,null),c->new ToolRequest("wrong","capture",Json.object("targetId","field-mudkip")),Runnable::run);loop.tick(1);assertEquals("TARGET_NOT_IN_TASK",loop.tick(2).getCode());assertEquals(0,scene.getSession().getTurn());}
 @Test void regionAndAlreadyExpiredDeadlineRejectConfirmationWithoutSpawning(){for(boolean area:new boolean[]{true,false}){AgentRoom room=new AgentRoom("invalid"+area,provider("CAPTURE","field-mudkip",area?EnumSet.of(TaskIntent.Constraint.AREA_RESTRICTED):EnumSet.of(TaskIntent.Constraint.DEADLINE),area?"ORCHARD_AREA":null,area?null:1L,new AtomicInteger()),Runnable::run,true,null);
   if(!area){room.command(AgentRoomTest.command(room,"MANUAL",Json.object("action","wait","arguments",Collections.emptyMap())),0);}parse(room);AgentRoom.Reply reply=room.command(AgentRoomTest.command(room,"CONFIRM",Collections.emptyMap()),2);assertEquals(409,reply.status);assertEquals(area?"AREA_RESTRICTED":"INVALID_DEADLINE",reply.body.get("reasonCode"));assertEquals(0,Json.asArray(room.snapshot().get("wild")).size());
  }}
 @Test void worldDeadlineStopsFieldTaskWithoutClaimingCapture(){AgentRoom room=new AgentRoom("deadline",provider("CAPTURE","field-torchic",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger()),Runnable::run,true,null);assertThrows(IllegalArgumentException.class,()->TaskIntent.ofGoal("q","CAPTURE","field-torchic",EnumSet.noneOf(TaskIntent.Constraint.class),null,null));
  room=new AgentRoom("deadline2",provider("CAPTURE","field-treecko",EnumSet.of(TaskIntent.Constraint.DEADLINE),null,1L,new AtomicInteger()),Runnable::run,true,null);start(room);for(int i=3;i<10;i++)room.tick(i);assertEquals("FAILED",room.snapshot().get("status"));assertEquals("WILD",target(room,"field-treecko").get("state"));
 }
 @Test void capturedGoalCannotBeReinterpretedAsDefeatedAndCompactSceneCannotConfirmFieldTask(){AgentRoom room=new AgentRoom("compact",provider("CAPTURE","field-treecko",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger()),Runnable::run,false,null);parse(room);assertEquals("ORIGINAL_MAP_REQUIRED",room.command(AgentRoomTest.command(room,"CONFIRM",Collections.emptyMap()),2).body.get("reasonCode"));}
 @Test void fileRestorePreservesFieldGoalPausedProgressAndCompletedResult(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection p=provider("CAPTURE","field-mudkip",EnumSet.of(TaskIntent.Constraint.NO_SPENDING),null,null,new AtomicInteger());AgentRoom room=new AgentRoom("save",p,Runnable::run,true,store);start(room);room.tick(3);room.tick(4);room.command(AgentRoomTest.command(room,"PAUSE",Collections.emptyMap()),5);String turn=(String)Json.asObject(room.snapshot().get("world")).get("turn");room.close();AgentRoom restored=new AgentRoom("save",p,Runnable::run,true,store);assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals("CAPTURE",restored.snapshot().get("taskKind"));assertEquals("field-mudkip",restored.snapshot().get("targetId"));assertEquals(turn,Json.asObject(restored.snapshot().get("world")).get("turn"));assertEquals(200,restored.command(AgentRoomTest.command(restored,"RESUME",Collections.emptyMap()),6).status);for(int i=7;i<45&&!"COMPLETED".equals(restored.snapshot().get("status"));i++)restored.tick(i);assertEquals("COMPLETED",restored.snapshot().get("status"));restored.close();assertEquals("COMPLETED",new AgentRoom("save",p,Runnable::run,true,store).snapshot().get("status"));}

 @Test void nativeTorchicDefeatCompletesWithoutOfferingCaptureTool(){AtomicInteger calls=new AtomicInteger();AgentRoom room=new AgentRoom("defeat",provider("DEFEAT","field-torchic",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,calls),Runnable::run,true,null);start(room);for(int i=3;i<140&&!Arrays.asList("COMPLETED","FAILED").contains(room.snapshot().get("status"));i++)room.tick(i);assertEquals("COMPLETED",room.snapshot().get("status"));assertEquals("DEFEATED",target(room,"field-torchic").get("state"));assertEquals(0,((Number)target(room,"field-torchic").get("hp")).intValue());}
 @Test void captureCompletesEvenIfTheLastValidTurnLeavesLeaderNeedingRescue(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection p=provider("CAPTURE","field-treecko",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger());new AgentRoom("rescue",p,Runnable::run,true,store).close();Map<String,Object> checkpoint=store.load("rescue");Json.asObject(Json.asObject(checkpoint.get("scene")).get("actor")).put("hp",60);store.save("rescue",checkpoint);AgentRoom room=new AgentRoom("rescue",p,Runnable::run,true,store);start(room);for(int i=3;i<35&&!Arrays.asList("COMPLETED","FAILED").contains(room.snapshot().get("status"));i++)room.tick(i);assertEquals("CAPTURED",target(room,"field-treecko").get("state"));assertEquals("COMPLETED",room.snapshot().get("status"));}
 @Test void pauseInvalidatesLateFieldDecisionAndResetNeverExecutesIt(){Queue<Runnable> jobs=new ArrayDeque<>();ProviderSelection p=provider("CAPTURE","field-treecko",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger());AgentRoom room=new AgentRoom("late-field",p,jobs::add,true,null);assertEquals(200,room.command(AgentRoomTest.command(room,"PARSE",Json.object("text","捕捉")),0).status);jobs.remove().run();room.tick(1);room.command(AgentRoomTest.command(room,"CONFIRM",Collections.emptyMap()),2);room.tick(3);room.command(AgentRoomTest.command(room,"PAUSE",Collections.emptyMap()),4);jobs.remove().run();room.tick(5);assertEquals("0",Json.asObject(room.snapshot().get("world")).get("turn"));room.command(AgentRoomTest.command(room,"CANCEL",Collections.emptyMap()),6);room.command(AgentRoomTest.command(room,"RESET",Collections.emptyMap()),7);room.tick(8);assertEquals("IDLE",room.snapshot().get("status"));assertEquals(0,Json.asArray(room.snapshot().get("wild")).size());}

 @Test void restartBeforeConfirmationPreservesReadyAndDoesNotSpawnOrStart(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection p=provider("CAPTURE","field-treecko",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger());AgentRoom room=new AgentRoom("ready",p,Runnable::run,true,store);parse(room);room.close();AgentRoom restored=new AgentRoom("ready",p,Runnable::run,true,store);assertEquals("READY",restored.snapshot().get("status"));assertEquals(0,Json.asArray(restored.snapshot().get("wild")).size());restored.tick(10);assertEquals("0",Json.asObject(restored.snapshot().get("world")).get("turn"));assertEquals(200,restored.command(AgentRoomTest.command(restored,"CONFIRM",Collections.emptyMap()),11).status);}
 @Test void captureOnLastAllowedActionCompletesAndRetainsItsTurnIncrement(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);ProviderSelection p=provider("CAPTURE","field-treecko",EnumSet.of(TaskIntent.Constraint.DEADLINE),null,1L,new AtomicInteger());new AgentRoom("last",p,Runnable::run,true,store).close();Map<String,Object> checkpoint=store.load("last");Map<String,Object> actor=Json.asObject(Json.asObject(checkpoint.get("scene")).get("actor"));actor.put("x",31);actor.put("y",11);store.save("last",checkpoint);AgentRoom room=new AgentRoom("last",p,Runnable::run,true,store);start(room);room.tick(3);room.tick(4);assertEquals("CAPTURED",target(room,"field-treecko").get("state"));assertEquals("COMPLETED",room.snapshot().get("status"));assertEquals("1",Json.asObject(room.snapshot().get("world")).get("turn"));room.close();AgentRoom restored=new AgentRoom("last",p,Runnable::run,true,store);assertEquals("COMPLETED",restored.snapshot().get("status"));assertEquals("1",Json.asObject(restored.snapshot().get("world")).get("turn"));}

 @Test void postgresFieldReadyAndCompletedCheckpointsRoundTrip()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");String owner="field-pg-"+UUID.randomUUID();ProviderSelection p=provider("CAPTURE","field-treecko",EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE),null,null,new AtomicInteger());try(WorldStore store=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){AgentRoom room=new AgentRoom(owner,p,Runnable::run,true,store);parse(room);room.close();AgentRoom ready=new AgentRoom(owner,p,Runnable::run,true,store);assertEquals("READY",ready.snapshot().get("status"));ready.command(AgentRoomTest.command(ready,"CONFIRM",Collections.emptyMap()),2);for(int i=3;i<35&&!"COMPLETED".equals(ready.snapshot().get("status"));i++)ready.tick(i);assertEquals("COMPLETED",ready.snapshot().get("status"));ready.close();AgentRoom restored=new AgentRoom(owner,p,Runnable::run,true,store);assertEquals("CAPTURE",restored.snapshot().get("taskKind"));assertEquals("COMPLETED",restored.snapshot().get("status"));assertEquals("CAPTURED",target(restored,"field-treecko").get("state"));}}
 @Test void unknownFieldSaveCommitFreezesActionsAndRecoveryRestoresConfirmedGoal(@TempDir Path dir){FileWorldStore base=new FileWorldStore(dir);boolean[] broken={false};WorldStore store=new WorldStore(){public Map<String,Object> load(String owner){return base.load(owner);}public void save(String owner,Map<String,Object> value){if(broken[0])throw new StoreException(StoreException.Code.IO_ERROR);base.save(owner,value);}public void close(){base.close();}};ProviderSelection p=provider("CAPTURE","field-mudkip",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger());AgentRoom room=new AgentRoom("failure",p,Runnable::run,true,store);start(room);broken[0]=true;room.tick(3);room.tick(4);assertEquals("STORAGE_ERROR",room.snapshot().get("status"));String turn=(String)Json.asObject(room.snapshot().get("world")).get("turn");room.tick(5);assertEquals(turn,Json.asObject(room.snapshot().get("world")).get("turn"));broken[0]=false;assertEquals(200,room.command(AgentRoomTest.command(room,"RECOVER",Collections.emptyMap()),6).status);assertEquals("PAUSED",room.snapshot().get("status"));assertEquals("CAPTURE",room.snapshot().get("taskKind"));assertEquals("field-mudkip",room.snapshot().get("targetId"));}

 @Test void everyFieldDecisionIncludesCurrentAdjacencyAndDirectCaptureHint(){GeminiQuestScenario scene=new GeminiQuestScenario("hints",true);AgentLoop loop=scene.start(TaskIntent.ofGoal(scene.getSession().getQuestId(),"CAPTURE","field-mudkip",EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE),null,null),context->{assertEquals("false",context.getObservation().get("targetAdjacent"));assertEquals("move_to",context.getObservation().get("suggestedAction"));assertTrue(context.getObservation().get("captureRules").contains("not active battle"));return new ToolRequest("read","observe",Collections.emptyMap());},Runnable::run);loop.tick(1);assertEquals("FIELD_OBSERVED",loop.tick(2).getCode());}
}
