package game.agent;
import game.agent.web.*;import game.agent.llm.*;import game.agent.persistence.*;
import java.util.*;import java.nio.file.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import static org.junit.jupiter.api.Assertions.*;
class GameplayCompletionTest {
 @TempDir Path directory;
 static Map<String,Object> view(AgentWebServerTest.Browser b,String q)throws Exception{return PokemonCarryTest.view(b,q);}
 static void send(AgentWebServerTest.Browser b,String q,String action,Map<String,Object> args)throws Exception{PokemonCarryTest.send(b,q,action,args);}
 static void wild(AgentWebServerTest.Browser b,String q,String action,String value)throws Exception{send(b,q,"WILD_ACTION",Json.object("action",action,"arguments",Json.object(action.equals("move")?"direction":"targetId",value)));}
 static Map<String,Object> target(Map<String,Object> v,String id){for(Object x:Json.asArray(v.get("wild")))if(id.equals(Json.asObject(x).get("id")))return Json.asObject(x);throw new AssertionError(id);}
 @Test void originalWildMudkipCanBeCapturedStoredSummonedAndSelectedAsBattlePartner()throws Exception{
  try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,null)){
   s.start();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(s.getPort());String q=PokemonCarryTest.room(b,"quest");
   assertEquals(200,b.post(q+"/commands",Json.write(PokemonCarryTest.command(view(b,q),"EXPLORE",Collections.emptyMap())),b.base,b.csrf).getResponseCode());
   for(String d:Arrays.asList("E","E","E","E"))PokemonFollowTest.move(b,q,d);
   wild(b,q,"capture","field-mudkip");assertEquals("CAPTURED",target(view(b,q),"field-mudkip").get("state"));send(b,q,"STORE_WILD",Json.object("targetId","field-mudkip"));
   Map<String,Object> row=Json.asObject(PokemonCarryTest.collection(view(b,q)).get(0));assertEquals("MUDKIP",row.get("species"));assertEquals("TRANSFERRED",target(view(b,q),"field-mudkip").get("state"));
   String id=(String)row.get("captureId");send(b,q,"SUMMON",Json.object("captureId",id,"direction","E"));send(b,q,"PARTNER",Json.object("captureId",id));assertEquals(id,view(b,q).get("combatPartner"));assertEquals("MUDKIP",Json.asObject(view(b,q).get("summoned")).get("species"));
  }
 }

 static String capturedMudkip(AgentWebServerTest.Browser b,String q)throws Exception{send(b,q,"EXPLORE",Collections.emptyMap());for(int j=0;j<4;j++)PokemonFollowTest.move(b,q,"E");wild(b,q,"capture","field-mudkip");return (String)target(view(b,q),"field-mudkip").get("captureId");}
 @Test void repeatedStoreAndOwnedBattleMovementUseActualActorWithoutDoubleFollow()throws Exception{
  try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,null)){
   s.start();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(s.getPort());String q=PokemonCarryTest.room(b,"quest"),id=capturedMudkip(b,q);Map<String,Object> payload=PokemonCarryTest.command(view(b,q),"STORE_WILD",Json.object("targetId","field-mudkip"));b.post(q+"/commands",payload);b.post(q+"/commands",payload);assertEquals(1,PokemonCarryTest.collection(view(b,q)).size());assertEquals("5",Json.asObject(view(b,q).get("world")).get("turn"));
   send(b,q,"SUMMON",Json.object("captureId",id,"direction","E"));send(b,q,"FOLLOW",PokemonFollowTest.toggle(id,true));send(b,q,"PARTNER",Json.object("captureId",id));wild(b,q,"move","E");Map<String,Object> v=view(b,q),owned=Json.asObject(v.get("summoned"));assertEquals(35,PokemonFollowTest.coord(owned,"x"));assertEquals(10,PokemonFollowTest.coord(owned,"y"));assertEquals(false,owned.get("following"));assertEquals("33",Json.asObject(v.get("world")).get("x"));assertEquals("6",Json.asObject(v.get("world")).get("turn"));
   assertEquals(409,PokemonSummonTest.rejected(b,q,"WILD_ACTION",Json.object("action","capture","arguments",Json.object("targetId","field-torchic"))));assertEquals("6",Json.asObject(view(b,q).get("world")).get("turn"));
   Map<String,Object> before=target(view(b,q),"field-torchic");wild(b,q,"attack","field-torchic");Map<String,Object> after=view(b,q),last=Json.asObject(Json.asArray(after.get("trace")).get(Json.asArray(after.get("trace")).size()-1)),data=Json.asObject(last.get("data"));
   assertEquals(100-Integer.parseInt((String)data.get("retaliationDamage")),PokemonFollowTest.coord(Json.asObject(after.get("summoned")),"hp"));assertEquals(PokemonFollowTest.coord(before,"hp")-Integer.parseInt((String)data.get("damage")),PokemonFollowTest.coord(target(after,"field-torchic"),"hp"));assertEquals("7",Json.asObject(after.get("world")).get("turn"));
   send(b,q,"RECALL",Json.object("captureId",id));assertEquals("mudkip",view(b,q).get("combatPartner"));
  }
 }
 @Test void failedOrUnknownCollectionStoreAndSourceWriteRecoverUniqueWildReceipt()throws Exception{
  for(String prefix:Arrays.asList("collection:","world"))for(boolean committed:Arrays.asList(false,true)){
   PokemonCarryTest.FaultStore store=new PokemonCarryTest.FaultStore();try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,store)){
    s.start();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(s.getPort());String q=PokemonCarryTest.room(b,"quest"),id=capturedMudkip(b,q);store.failPrefix=prefix.equals("world")?store.values.keySet().stream().filter(k->!k.contains(":")).findFirst().get():prefix;store.afterCommit=committed;
    assertEquals(503,PokemonSummonTest.rejected(b,q,"STORE_WILD",Json.object("targetId","field-mudkip")));assertEquals("STORAGE_ERROR",view(b,q).get("status"));store.failPrefix=null;send(b,q,"RECOVER",Collections.emptyMap());
    if(prefix.equals("collection:")&&!committed){assertEquals("CAPTURED",target(view(b,q),"field-mudkip").get("state"));send(b,q,"STORE_WILD",Json.object("targetId","field-mudkip"));}
    Map<String,Object> v=view(b,q);assertEquals(1,PokemonCarryTest.collection(v).size());assertEquals(id,Json.asObject(PokemonCarryTest.collection(v).get(0)).get("captureId"));assertEquals("TRANSFERRED",target(v,"field-mudkip").get("state"));assertEquals("5",Json.asObject(v.get("world")).get("turn"));
   }
  }
 }
 @Test void fileRestartRestoresWildInventoryOwnedSpeciesHpAndSelectedPartner()throws Exception{
  int port;String cookie,id;Map<String,Object> out;
  try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,new FileWorldStore(directory))){s.start();port=s.getPort();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(port);cookie=b.cookie;String q=PokemonCarryTest.room(b,"quest");id=capturedMudkip(b,q);send(b,q,"STORE_WILD",Json.object("targetId","field-mudkip"));send(b,q,"SUMMON",Json.object("captureId",id,"direction","E"));send(b,q,"PARTNER",Json.object("captureId",id));wild(b,q,"move","E");wild(b,q,"attack","field-torchic");out=Json.asObject(view(b,q).get("summoned"));}
  try(AgentWebServer s=new AgentWebServer(port,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,new FileWorldStore(directory))){s.start();AgentWebServerTest.Browser b=PokemonFollowTest.restoredBrowser(port,cookie);String t=PokemonCarryTest.room(b,"training");Map<String,Object> row=Json.asObject(PokemonCarryTest.collection(view(b,t)).get(0));assertEquals(out.get("hp"),row.get("hp"));assertEquals("MUDKIP",row.get("species"));String q=PokemonCarryTest.room(b,"quest");assertEquals(out,Json.asObject(view(b,q).get("summoned")));assertEquals(id,view(b,q).get("combatPartner"));assertEquals("TRANSFERRED",target(view(b,q),"field-mudkip").get("state"));send(b,q,"RESET",Collections.emptyMap());assertTrue(Json.asArray(view(b,q).get("wild")).isEmpty());assertEquals(1,PokemonCarryTest.collection(view(b,q)).size());assertEquals("mudkip",view(b,q).get("combatPartner"));}
 }
 static BattleRoomTest.Memory seeded(String owner,String id,int hp){BattleRoomTest.Memory store=new BattleRoomTest.Memory();store.save("collection:"+owner,Json.object("schemaVersion",1,"kind","POKEMON_COLLECTION","pokemon",Arrays.asList(Json.object("captureId",id,"species","MUDKIP","hp",hp,"maxHp",100))));return store;}
 @Test void deployedHpIsWorldAuthorityAndRecalledRestHealsActualNativePokemon(){
  String id=UUID.randomUUID().toString();BattleRoomTest.Memory store=seeded("health",id,85);AgentRoom room=new AgentRoom("health",ProviderSelection.fromEnvironment(Collections.emptyMap()),Runnable::run,true,store);assertEquals(200,room.command(AgentRoomTest.command(room,"SUMMON",Json.object("captureId",id,"direction","E")),0).status);
  Map<String,Object> checkpoint=store.load("health");Json.asObject(checkpoint.get("summoned")).put("hp",37);room=new AgentRoom("health",ProviderSelection.fromEnvironment(Collections.emptyMap()),Runnable::run,true,store);assertEquals(37,PokemonFollowTest.coord(Json.asObject(room.snapshot().get("summoned")),"hp"));assertEquals(200,room.command(AgentRoomTest.command(room,"RECALL",Json.object("captureId",id)),1).status);assertEquals(37,PokemonFollowTest.coord(Json.asObject(Json.asArray(store.load("collection:health").get("pokemon")).get(0)),"hp"));
  checkpoint=store.load("health");Map<String,Object> actor=Json.asObject(Json.asObject(checkpoint.get("scene")).get("actor"));actor.put("x",29);actor.put("y",6);room=new AgentRoom("health",ProviderSelection.fromEnvironment(Collections.emptyMap()),Runnable::run,true,store);assertEquals(200,room.command(AgentRoomTest.command(room,"REST",Json.object("captureId",id)),2).status);assertEquals(100,PokemonFollowTest.coord(Json.asObject(Json.asArray(store.load("collection:health").get("pokemon")).get(0)),"hp"));assertEquals(200,room.command(AgentRoomTest.command(room,"SUMMON",Json.object("captureId",id,"direction","E")),3).status);assertEquals(100,PokemonFollowTest.coord(Json.asObject(room.snapshot().get("summoned")),"hp"));assertEquals(409,room.command(AgentRoomTest.command(room,"REST",Json.object("captureId",id)),4).status);assertEquals("0",Json.asObject(room.snapshot().get("world")).get("turn"));
 }
 @Test void currentTaskBattleRestrictionAndNativeCaptureRulesHold(){
  game.agent.demo.GeminiQuestScenario initial=new game.agent.demo.GeminiQuestScenario("rules",true);initial.explore();Map<String,Object> saved=initial.exportState();Map<String,Object> pos=Json.asObject(saved.get("actor"));pos.put("x",31);pos.put("y",11);game.agent.demo.GeminiQuestScenario scene=game.agent.demo.GeminiQuestScenario.restore("rules",saved);scene.start(TaskIntent.of(scene.getSession().getQuestId(),EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE),null,null),c->{throw new IllegalStateException("not called");},Runnable::run);scene.restoreLifecycle("PAUSED");assertEquals("NO_ACTIVE_BATTLE",scene.wildManual(false,"attack",Json.object("targetId","field-treecko")).getCode());assertEquals("CAPTURED",scene.wildManual(false,"capture",Json.object("targetId","field-treecko")).getCode());assertEquals("UNKNOWN_TARGET",scene.wildManual(false,"attack",Json.object("targetId","treecko")).getCode());
 }
 @Test void lowHealthPartnerRefusesPotentialLethalCounterAndInvalidSpeciesIsRejected(){
  game.agent.demo.GeminiQuestScenario initial=new game.agent.demo.GeminiQuestScenario("low",true);initial.explore();Map<String,Object> saved=initial.exportState();game.agent.demo.GeminiQuestScenario scene=game.agent.demo.GeminiQuestScenario.restore("low",saved);game.actors.pokemon.Mudkip partner=new game.actors.pokemon.Mudkip();partner.hurt(99);scene.synchronizeSummoned(partner,Json.object("x",35,"y",10));assertEquals("PARTNER_EXHAUSTED",scene.wildManual(true,"attack",Json.object("targetId","field-torchic")).getCode());assertEquals(1,partner.getHitPoints());assertEquals(100,PokemonFollowTest.coord(target(Json.object("wild",scene.wildStates()),"field-torchic"),"hp"));
  String id=UUID.randomUUID().toString();BattleRoomTest.Memory store=seeded("bad",id,85);Json.asObject(Json.asArray(store.load("collection:bad").get("pokemon")).get(0)).put("species","TORCHIC");assertThrows(IllegalArgumentException.class,()->new AgentRoom("bad",ProviderSelection.fromEnvironment(Collections.emptyMap()),Runnable::run,true,store));
 }
 @Test void lowHealthExplorationDoesNotReserveRemovedDayDamage(){
  game.agent.demo.GeminiQuestScenario initial=new game.agent.demo.GeminiQuestScenario("day",true);initial.explore();Map<String,Object>saved=initial.exportState();Map<String,Object>actor=Json.asObject(saved.get("actor"));actor.put("hp",16);actor.put("x",31);actor.put("y",11);game.agent.demo.GeminiQuestScenario scene=game.agent.demo.GeminiQuestScenario.restore("day",saved);assertEquals("CAPTURED",scene.wildManual(false,"capture",Json.object("targetId","field-treecko")).getCode());scene.advanceTurn();assertEquals(16,PokemonFollowTest.coord(scene.partnerState(false),"hp"));assertTrue(scene.canAdvanceSafely());assertEquals(100,PokemonFollowTest.coord(target(Json.object("wild",scene.wildStates()),"field-torchic"),"hp"));
 }
 @Test void emergencyLeaderRestPreservesRemoteWildProgressAndResumesMovement(){
  BattleRoomTest.Memory store=new BattleRoomTest.Memory();AgentRoom room=new AgentRoom("rescue",ProviderSelection.fromEnvironment(Collections.emptyMap()),Runnable::run,true,store);room.command(AgentRoomTest.command(room,"EXPLORE",Collections.emptyMap()),0);Map<String,Object> checkpoint=store.load("rescue");Json.asObject(Json.asObject(checkpoint.get("scene")).get("actor")).put("hp",0);room=new AgentRoom("rescue",ProviderSelection.fromEnvironment(Collections.emptyMap()),Runnable::run,true,store);assertTrue((Boolean)room.snapshot().get("emergencyRest"));Object wild=room.snapshot().get("wild");assertEquals(200,room.command(AgentRoomTest.command(room,"REST",Json.object("captureId","mudkip")),1).status);assertEquals(wild,room.snapshot().get("wild"));assertEquals("0",Json.asObject(room.snapshot().get("world")).get("turn"));assertEquals(1000,PokemonFollowTest.coord(Json.asObject(room.snapshot().get("combatPartnerState")),"hp"));assertEquals(200,room.command(AgentRoomTest.command(room,"WILD_ACTION",Json.object("action","move","arguments",Json.object("direction","E"))),2).status);assertEquals("1",Json.asObject(room.snapshot().get("world")).get("turn"));
 }
 @Test void cancelledAndRestoredCancelledTaskReleasesFieldRestrictions(){
  for(boolean restart:new boolean[]{false,true}){
   game.agent.demo.GeminiQuestScenario original=new game.agent.demo.GeminiQuestScenario("cancel-field",true);original.explore();Map<String,Object> saved=original.exportState();Map<String,Object> actor=Json.asObject(saved.get("actor"));actor.put("x",33);actor.put("y",11);game.agent.demo.GeminiQuestScenario scene=game.agent.demo.GeminiQuestScenario.restore("cancel-field",saved);TaskIntent intent=TaskIntent.of(scene.getSession().getQuestId(),EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE,TaskIntent.Constraint.AREA_RESTRICTED),"ORCHARD_AREA",null);game.agent.runtime.AgentLoop loop=scene.start(intent,c->{throw new IllegalStateException("not called");},Runnable::run);loop.pause();assertEquals("AREA_RESTRICTED",scene.wildManual(false,"move",Json.object("direction","E")).getCode());assertEquals("NO_ACTIVE_BATTLE",scene.wildManual(false,"attack",Json.object("targetId","field-treecko")).getCode());loop.cancel();if(restart){scene=game.agent.demo.GeminiQuestScenario.restore("cancel-field",scene.exportState());scene.restoreAgent(intent,c->{throw new IllegalStateException("not called");},Runnable::run,35000);scene.restoreLifecycle("CANCELLED");}assertFalse(scene.battleForbidden());assertEquals(game.agent.action.ActionResult.Status.SUCCESS,scene.wildManual(false,"move",Json.object("direction","E")).getStatus());
  }
 }
 @Test void missingCollectionAuthorityKeepsTransferredWildWorldFrozen()throws Exception{
  PokemonCarryTest.FaultStore store=new PokemonCarryTest.FaultStore();String cookie;int port;try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,store)){s.start();port=s.getPort();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(port);cookie=b.cookie;String q=PokemonCarryTest.room(b,"quest");capturedMudkip(b,q);send(b,q,"STORE_WILD",Json.object("targetId","field-mudkip"));}store.values.keySet().removeIf(k->k.startsWith("collection:"));try(AgentWebServer s=new AgentWebServer(port,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,store)){s.start();AgentWebServerTest.Browser b=PokemonFollowTest.restoredBrowser(port,cookie);String q=PokemonCarryTest.room(b,"quest");assertEquals("STORAGE_ERROR",view(b,q).get("status"));assertEquals(503,PokemonSummonTest.rejected(b,q,"RECOVER",Collections.emptyMap()));}
 }
 @Test void explorationAndPartnerCommandsRespectUnselectedTabStaleRevisionAndOwnership()throws Exception{
  try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,null)){
   s.start();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(s.getPort());String q=PokemonCarryTest.room(b,"quest");Map<String,Object> stale=PokemonCarryTest.command(view(b,q),"PARTNER",Json.object("captureId","mudkip"));send(b,q,"EXPLORE",Collections.emptyMap());assertEquals(409,b.post(q+"/commands",Json.write(stale),b.base,b.csrf).getResponseCode());assertEquals(409,PokemonSummonTest.rejected(b,q,"PARTNER",Json.object("captureId",UUID.randomUUID().toString())));assertEquals(409,PokemonSummonTest.rejected(b,q,"STORE_WILD",Json.object("targetId","field-mudkip")));PokemonCarryTest.room(b,"training");for(String command:Arrays.asList("EXPLORE","PARTNER","REST","STORE_WILD","WILD_ACTION")){Map<String,Object> params=command.equals("EXPLORE")?Collections.emptyMap():command.equals("STORE_WILD")?Json.object("targetId","field-mudkip"):command.equals("WILD_ACTION")?Json.object("action","attack","arguments",Json.object("targetId","field-mudkip")):Json.object("captureId","mudkip");assertEquals(409,PokemonSummonTest.rejected(b,q,command,params));}
  }
 }
 @Test void unknownBattleCommitRestoresTargetPartnerHealthAndTurnTogether()throws Exception{
  for(boolean committed:Arrays.asList(false,true)){
   PokemonCarryTest.FaultStore store=new PokemonCarryTest.FaultStore();try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,store)){
    s.start();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(s.getPort());String q=PokemonCarryTest.room(b,"quest"),id=capturedMudkip(b,q);send(b,q,"STORE_WILD",Json.object("targetId","field-mudkip"));send(b,q,"SUMMON",Json.object("captureId",id,"direction","E"));send(b,q,"PARTNER",Json.object("captureId",id));wild(b,q,"move","E");Map<String,Object> before=view(b,q);
    store.failPrefix=store.values.keySet().stream().filter(k->!k.contains(":")).findFirst().get();store.afterCommit=committed;assertEquals(503,PokemonSummonTest.rejected(b,q,"WILD_ACTION",Json.object("action","attack","arguments",Json.object("targetId","field-torchic"))));Map<String,Object> after=view(b,q);store.failPrefix=null;send(b,q,"RECOVER",Collections.emptyMap());Map<String,Object> restored=view(b,q),expected=committed?after:before;assertEquals(expected.get("summoned"),restored.get("summoned"));assertEquals(expected.get("wild"),restored.get("wild"));assertEquals(committed?"7":"6",Json.asObject(restored.get("world")).get("turn"));assertEquals(id,restored.get("combatPartner"));
   }
  }
 }
 @Test void crossRoomCollectionReloadRetainsDeployedHealthAndBattlePartner()throws Exception{
  PokemonCarryTest.FaultStore store=new PokemonCarryTest.FaultStore();try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,store)){
   s.start();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(s.getPort());String q=PokemonCarryTest.room(b,"quest"),id=capturedMudkip(b,q);send(b,q,"STORE_WILD",Json.object("targetId","field-mudkip"));send(b,q,"SUMMON",Json.object("captureId",id,"direction","E"));send(b,q,"PARTNER",Json.object("captureId",id));String owner=store.values.keySet().stream().filter(k->!k.contains(":")).findFirst().get();Json.asObject(store.load(owner).get("summoned")).put("hp",37);store.failPrefix=owner;assertEquals(503,PokemonSummonTest.rejected(b,q,"FOLLOW",PokemonFollowTest.toggle(id,false)));store.failPrefix=null;send(b,q,"RECOVER",Collections.emptyMap());assertEquals(37,PokemonFollowTest.coord(Json.asObject(view(b,q).get("summoned")),"hp"));
   String t=PokemonCarryTest.room(b,"training");store.failPrefix="battle:";assertEquals(503,PokemonSummonTest.rejected(b,t,"MANUAL",Json.object("action","move","arguments",Json.object("direction","E"))));store.failPrefix=null;send(b,t,"RECOVER",Collections.emptyMap());PokemonCarryTest.room(b,"quest");assertEquals(37,PokemonFollowTest.coord(Json.asObject(view(b,q).get("summoned")),"hp"));assertEquals(id,view(b,q).get("combatPartner"));send(b,q,"RECALL",Json.object("captureId",id));assertEquals(37,PokemonFollowTest.coord(Json.asObject(PokemonCarryTest.collection(view(b,q)).get(0)),"hp"));
  }
 }
 @Test void restUnknownCollectionCommitRecoversDurableHpWithoutExtraTurn(){
  for(boolean committed:Arrays.asList(false,true)){
   String id=UUID.randomUUID().toString();PokemonCarryTest.FaultStore store=new PokemonCarryTest.FaultStore();store.save("collection:rest-fault",Json.object("schemaVersion",1,"kind","POKEMON_COLLECTION","pokemon",Arrays.asList(Json.object("captureId",id,"species","MUDKIP","hp",37,"maxHp",100))));AgentRoom room=new AgentRoom("rest-fault",ProviderSelection.fromEnvironment(Collections.emptyMap()),Runnable::run,true,store);Map<String,Object> actor=Json.asObject(Json.asObject(store.load("rest-fault").get("scene")).get("actor"));actor.put("x",29);actor.put("y",6);room=new AgentRoom("rest-fault",ProviderSelection.fromEnvironment(Collections.emptyMap()),Runnable::run,true,store);store.failPrefix="collection:";store.afterCommit=committed;assertEquals(503,room.command(AgentRoomTest.command(room,"REST",Json.object("captureId",id)),0).status);store.failPrefix=null;assertEquals(200,room.command(AgentRoomTest.command(room,"RECOVER",Collections.emptyMap()),1).status);assertEquals(200,room.command(AgentRoomTest.command(room,"SUMMON",Json.object("captureId",id,"direction","E")),2).status);assertEquals(committed?100:37,PokemonFollowTest.coord(Json.asObject(room.snapshot().get("summoned")),"hp"));assertEquals("0",Json.asObject(room.snapshot().get("world")).get("turn"));
  }
 }
 @Test void postgresRestoresAdditionalSpeciesAndSelectedBattlePartner()throws Exception{
  String jdbc=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(jdbc!=null,"PostgreSQL opt-in");String user=System.getProperty("pokemon.test.jdbcUser","postgres"),password=System.getProperty("pokemon.test.jdbcPassword","");int port;String cookie,id;
  try(AgentWebServer s=new AgentWebServer(0,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,new JdbcWorldStore(()->java.sql.DriverManager.getConnection(jdbc,user,password)))){s.start();port=s.getPort();AgentWebServerTest.Browser b=new AgentWebServerTest.Browser(port);cookie=b.cookie;String q=PokemonCarryTest.room(b,"quest");id=capturedMudkip(b,q);send(b,q,"STORE_WILD",Json.object("targetId","field-mudkip"));send(b,q,"SUMMON",Json.object("captureId",id,"direction","E"));send(b,q,"PARTNER",Json.object("captureId",id));}
  try(AgentWebServer s=new AgentWebServer(port,ProviderSelection.fromEnvironment(Collections.emptyMap()),null,true,new JdbcWorldStore(()->java.sql.DriverManager.getConnection(jdbc,user,password)))){s.start();AgentWebServerTest.Browser b=PokemonFollowTest.restoredBrowser(port,cookie);String q=PokemonCarryTest.room(b,"quest");assertEquals(id,view(b,q).get("combatPartner"));assertEquals("MUDKIP",Json.asObject(PokemonCarryTest.collection(view(b,q)).get(0)).get("species"));assertEquals("TRANSFERRED",target(view(b,q),"field-mudkip").get("state"));}
 }
}
