package game.agent.web;
import game.agent.llm.Json;import game.agent.persistence.*;import game.agent.tools.ToolRequest;import java.nio.file.Path;import java.util.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import static org.junit.jupiter.api.Assertions.*;
class GrowthExpansionRoomTest {
 private ProviderSelection provider(){return new ProviderSelection("test","scripted",1000,c->new ToolRequest("nav","go_to_region",Json.object("regionId","forest")),null);}
 private Map<String,Object> world(GrowthRoom r){return Json.asObject(r.snapshot().get("world"));}
 private AgentRoom.Reply send(GrowthRoom r,String kind,Map<String,Object> p){Map<String,Object> v=r.snapshot();return r.command(Json.object("requestId",UUID.randomUUID().toString(),"taskId",v.get("taskId"),"expectedRevision",v.get("revision"),"command",kind,"params",p),10);}
 private void verify(WorldStore store){String owner="expansion-"+UUID.randomUUID();GrowthRoom r=new GrowthRoom(owner,provider(),Runnable::run,store,()->0);assertEquals(200,send(r,"START_ADVENTURE",Collections.emptyMap()).status);send(r,"STARTER",Json.object("species","TREECKO"));assertEquals("POOCHYENA",Json.asObject(Json.asArray(world(r).get("encounters")).get(0)).get("species"));String before=Json.write(world(r));assertEquals("REGION_LOCKED",send(r,"AI_TRAIN",Json.object("targetLevel",6,"regionId","mountain")).body.get("reasonCode"));assertEquals(before,Json.write(world(r)));GrowthRoom restored=new GrowthRoom(owner,provider(),Runnable::run,store,()->0);assertEquals(before,Json.write(world(restored)));assertEquals(true,Json.asObject(world(restored).get("adventure")).get("enabled"));restored.close();r.close();}
 @Test void fileRestoresCampaignDexAndTraits(@TempDir Path dir){try(WorldStore store=new FileWorldStore(dir)){verify(store);}}
 @Test void realPostgresRestoresCampaignDexAndTraits()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");try(WorldStore store=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){verify(store);}}
 @Test void failedCampaignWriteRecoversPreviouslyCommittedWorld(){GrowthRoomTest.Store store=new GrowthRoomTest.Store();GrowthRoom r=new GrowthRoom("expansion-fail",provider(),Runnable::run,store,()->0);send(r,"STARTER",Json.object("species","MUDKIP"));String before=Json.write(world(r));store.fail=true;assertEquals(503,send(r,"START_ADVENTURE",Collections.emptyMap()).status);store.fail=false;assertEquals(200,send(r,"RECOVER",Collections.emptyMap()).status);assertEquals(before,Json.write(world(r)));assertEquals(200,send(r,"START_ADVENTURE",Collections.emptyMap()).status);r.close();}
 @Test void campaignStartReceiptPreventsReplayingNewWildIndividuals(){GrowthRoom r=new GrowthRoom("expansion-receipt",provider(),Runnable::run,null,()->0);send(r,"STARTER",Json.object("species","MUDKIP"));Map<String,Object> v=r.snapshot();Map<String,Object> input=Json.object("requestId","campaign-receipt","taskId",v.get("taskId"),"expectedRevision",v.get("revision"),"command","START_ADVENTURE","params",Collections.emptyMap());assertEquals(200,r.command(input,10).status);String before=Json.write(world(r));assertEquals(200,r.command(input,11).status);assertEquals(before,Json.write(world(r)));r.close();}
}
