package game.agent.web;
import game.agent.growth.*;import game.agent.llm.*;import game.agent.persistence.*;import game.items.balls.Pokeball;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class GrowthReturnTest {
 static GrowthRoom room(WorldStore s,String o){return GrowthCarryTest.started(o,s);}
 static String id(GrowthRoom r){return (String)Json.asObject(Json.asObject(r.snapshot().get("world")).get("partner")).get("captureId");}
 static AgentRoom.Reply command(GrowthRoom r,String kind,String id){Map<String,Object> in=GrowthCarryTest.input(r,kind);if(id!=null)in.put("params",Json.object("captureId",id));return r.command(in,0);}
 @Test void repeatedRoundTripsPreserveOneIndividualAndEveryProfileField(@TempDir Path d){WorldStore s=new FileWorldStore(d);GrowthRoom r=room(s,"roundtrip");String id=id(r);Map<String,Object> original=Json.asObject(Json.asObject(r.snapshot().get("world")).get("partner"));for(int n=0;n<3;n++){assertEquals(200,command(r,"CARRY",null).status);assertEquals(200,command(r,"RETURN_GROWTH",id).status);assertEquals(id,id(r));assertEquals(original,Json.asObject(Json.asObject(r.snapshot().get("world")).get("partner")));assertTrue(Json.asArray(r.snapshot().get("collection")).isEmpty());r=new GrowthRoom("roundtrip",GrowthCarryTest.offline(),Runnable::run,s,()->0);assertEquals(id,id(r));}assertEquals(1,Json.asArray(Json.asObject(r.snapshot().get("world")).get("team")).size());}
 @Test void returnUsesReceiptAndDoesNotSpawnAnotherStarter(@TempDir Path d){WorldStore s=new FileWorldStore(d);GrowthRoom r=room(s,"repeat-return");String id=id(r);command(r,"CARRY",null);Map<String,Object> input=GrowthCarryTest.input(r,"RETURN_GROWTH");input.put("params",Json.object("captureId",id));assertEquals(200,r.command(input,0).status);assertEquals(200,r.command(input,0).status);assertEquals(1,Json.asArray(Json.asObject(r.snapshot().get("world")).get("team")).size());}
 @Test void deployedIndividualsMustBeRecalledBeforeMigration(@TempDir Path d){WorldStore s=new FileWorldStore(d);GrowthRoom r=room(s,"guard-return");String id=id(r);command(r,"CARRY",null);PokemonCollection c=new PokemonCollection("guard-return",s);assertEquals("ACCEPTED",c.summon(id,Json.object("x",30,"y",10)));assertEquals("RECALL_BEFORE_TRAINING",c.returnToGrowth(id));assertEquals("ACCEPTED",c.recall(id));String legacy=UUID.randomUUID().toString();assertEquals("ACCEPTED",c.receive(legacy,new Pokeball().capturePokemon(game.agent.combat.PokemonSpecies.create("TREECKO"))));assertEquals("ACCEPTED",c.summon(legacy,Json.object("x",30,"y",10)));assertEquals("RECALL_BEFORE_TRAINING",c.returnToGrowth(legacy));assertEquals(100,c.ball(legacy).getPokemon().getHitPoints());}
 @Test void returnCollectionCommitFailureDoesNotRemoveSource(@TempDir Path d){FileWorldStore base=new FileWorldStore(d);boolean[] fail={false};WorldStore s=new WorldStore(){public Map<String,Object> load(String o){return base.load(o);}public void save(String o,Map<String,Object> v){if(fail[0]&&o.startsWith("collection:"))throw new StoreException(StoreException.Code.IO_ERROR);base.save(o,v);}public void close(){}};GrowthRoom r=room(s,"return-fail");String id=id(r);command(r,"CARRY",null);fail[0]=true;assertEquals(503,command(r,"RETURN_GROWTH",id).status);assertEquals(1,Json.asArray(r.snapshot().get("collection")).size());fail[0]=false;assertEquals(200,command(r,"RECOVER",null).status);assertEquals(200,command(r,"RETURN_GROWTH",id).status);}
 @Test void destinationFailureRecoversFromDurableTrainingRecord(@TempDir Path d){FileWorldStore base=new FileWorldStore(d);boolean[] fail={false};WorldStore s=new WorldStore(){public Map<String,Object> load(String o){return base.load(o);}public void save(String o,Map<String,Object> v){if(fail[0]&&o.startsWith("growth:"))throw new StoreException(StoreException.Code.IO_ERROR);base.save(o,v);}public void close(){}};GrowthRoom r=room(s,"return-dest");String id=id(r);command(r,"CARRY",null);fail[0]=true;assertEquals(503,command(r,"RETURN_GROWTH",id).status);fail[0]=false;GrowthRoom restored=new GrowthRoom("return-dest",GrowthCarryTest.offline(),Runnable::run,s,()->0);assertEquals(id,id(restored));assertTrue(Json.asArray(restored.snapshot().get("collection")).isEmpty());assertEquals(200,command(restored,"CARRY",null).status);assertEquals(1,new PokemonCollection("return-dest",s).snapshot().size());assertTrue(new PokemonCollection("return-dest",s).trainingProfiles().isEmpty());}
 @Test void changedProgressionReplacesOldProfileOnNextCarry(@TempDir Path d){WorldStore s=new FileWorldStore(d);PokemonCollection c=new PokemonCollection("updated",s);GrowthPokemon p=new GrowthPokemon(UUID.randomUUID().toString(),"MUDKIP",16);p.evolve();assertEquals("ACCEPTED",c.receive(p.captureId,new Pokeball().capturePokemon(p)));assertEquals("ACCEPTED",c.returnToGrowth(p.captureId));p.gainExperience(300);p.pp.put(p.pp.keySet().iterator().next(),2);assertEquals("ACCEPTED",c.receive(p.captureId,new Pokeball().capturePokemon(p)));assertEquals(p.export(),((GrowthPokemon)new PokemonCollection("updated",s).ball(p.captureId).getPokemon()).export());}
 @Test void unknownReturnDoesNotCreateAnIndividual(@TempDir Path d){WorldStore s=new FileWorldStore(d);GrowthRoom r=room(s,"unknown-return");assertEquals("NOT_OWNED",command(r,"RETURN_GROWTH",UUID.randomUUID().toString()).body.get("reasonCode"));assertEquals(1,Json.asArray(Json.asObject(r.snapshot().get("world")).get("team")).size());}
 @Test void postgresRoundTripKeepsOwnershipAndGrowth()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");String owner="return-pg-"+UUID.randomUUID();try(WorldStore s=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){GrowthRoom r=room(s,owner);String id=id(r);command(r,"CARRY",null);assertEquals(200,command(r,"RETURN_GROWTH",id).status);GrowthRoom restored=new GrowthRoom(owner,GrowthCarryTest.offline(),Runnable::run,s,()->0);assertEquals(id,id(restored));assertTrue(new PokemonCollection(owner,s).snapshot().isEmpty());}}
}
