package game.agent.web;
import game.agent.growth.*;import game.agent.llm.*;import game.agent.persistence.*;import game.items.balls.Pokeball;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class GrowthCarryTest {
 static ProviderSelection offline(){return new ProviderSelection("none","offline",1000,null,null);}
 static Map<String,Object> input(GrowthRoom r,String cmd){Map<String,Object> s=r.snapshot();return Json.object("requestId",UUID.randomUUID().toString(),"taskId",s.get("taskId"),"expectedRevision",s.get("revision"),"command",cmd,"params",Collections.emptyMap());}
 static GrowthRoom started(String owner,WorldStore store){GrowthRoom r=new GrowthRoom(owner,offline(),Runnable::run,store,()->0);Map<String,Object> in=input(r,"STARTER");in.put("params",Json.object("species","MUDKIP"));assertEquals(200,r.command(in,0).status);return r;}
 @Test void carryTransfersIndividualWithoutFreeReplacementAndRestartDuplicates(@TempDir Path d){WorldStore s=new FileWorldStore(d);GrowthRoom r=started("carry",s);String id=(String)Json.asObject(Json.asObject(r.snapshot().get("world")).get("partner")).get("captureId");Map<String,Object> in=input(r,"CARRY");assertEquals(200,r.command(in,0).status);assertEquals(200,r.command(in,0).status);GrowthRoom restored=new GrowthRoom("carry",offline(),Runnable::run,s,()->0);assertNull(Json.asObject(restored.snapshot().get("world")).get("partner"));assertEquals(false,Json.asObject(restored.snapshot().get("world")).get("starterAvailable"));PokemonCollection c=new PokemonCollection("carry",s);assertEquals(1,c.snapshot().size());assertEquals(id,c.snapshot().get(0).get("captureId"));assertEquals(135,((GrowthPokemon)c.ball(id).getPokemon()).experience);Map<String,Object> start=input(restored,"STARTER");start.put("params",Json.object("species","TREECKO"));assertEquals("STARTER_ALREADY_CHOSEN",restored.command(start,0).body.get("reasonCode"));}
 @Test void evolvedHighHpProfileRetainsSkillsAndRestoresActualMax(@TempDir Path d){WorldStore s=new FileWorldStore(d);PokemonCollection c=new PokemonCollection("profile",s);GrowthPokemon p=new GrowthPokemon(UUID.randomUUID().toString(),"SWAMPERT",40);p.learn("MUDDY_WATER",p.pp.keySet().iterator().next());p.pp.put("MUDDY_WATER",3);p.hurt(7);assertTrue(p.maxHp()>100);assertEquals("ACCEPTED",c.receive(p.captureId,new Pokeball().capturePokemon(p)));PokemonCollection restored=new PokemonCollection("profile",s);GrowthPokemon q=(GrowthPokemon)restored.ball(p.captureId).getPokemon();assertEquals(p.export(),q.export());assertEquals("ACCEPTED",restored.heal(p.captureId));q=(GrowthPokemon)new PokemonCollection("profile",s).ball(p.captureId).getPokemon();assertEquals(q.maxHp(),q.getHitPoints());assertEquals(GrowthRules.move("MUDDY_WATER").pp,q.pp.get("MUDDY_WATER"));}
 @Test void receiverCommitFailureLeavesSourceFrozenButUnmoved(@TempDir Path d){FileWorldStore base=new FileWorldStore(d);boolean[] fail={false};WorldStore s=new WorldStore(){public Map<String,Object> load(String o){return base.load(o);}public void save(String o,Map<String,Object> v){if(fail[0]&&o.startsWith("collection:"))throw new StoreException(StoreException.Code.IO_ERROR);base.save(o,v);}public void close(){}};GrowthRoom r=started("receiver",s);fail[0]=true;assertEquals(503,r.command(input(r,"CARRY"),0).status);assertNotNull(Json.asObject(r.snapshot().get("world")).get("partner"));fail[0]=false;assertEquals(200,r.command(input(r,"RECOVER"),0).status);assertEquals(200,r.command(input(r,"CARRY"),0).status);}
 @Test void sourceCommitFailureReconcilesAgainstDurableReceiver(@TempDir Path d){FileWorldStore base=new FileWorldStore(d);boolean[] fail={false};WorldStore s=new WorldStore(){public Map<String,Object> load(String o){return base.load(o);}public void save(String o,Map<String,Object> v){if(fail[0]&&o.startsWith("growth:"))throw new StoreException(StoreException.Code.IO_ERROR);base.save(o,v);}public void close(){}};GrowthRoom r=started("source",s);fail[0]=true;assertEquals(503,r.command(input(r,"CARRY"),0).status);fail[0]=false;GrowthRoom restored=new GrowthRoom("source",offline(),Runnable::run,s,()->0);assertNull(Json.asObject(restored.snapshot().get("world")).get("partner"));assertEquals(1,new PokemonCollection("source",s).snapshot().size());}
 @Test void legacyGrowthCheckpointWithoutStarterFlagStillMigrates(@TempDir Path d){WorldStore s=new FileWorldStore(d);GrowthRoom r=started("legacy",s);Map<String,Object> saved=s.load("growth:legacy");Json.asObject(saved.get("world")).remove("starterChosen");s.save("growth:legacy",saved);GrowthRoom restored=new GrowthRoom("legacy",offline(),Runnable::run,s,()->0);assertEquals(200,restored.command(input(restored,"CARRY"),0).status);}
 @Test void forgedProfileIdCannotReceiveOrRestore(@TempDir Path d){WorldStore s=new FileWorldStore(d);PokemonCollection c=new PokemonCollection("invalid",s);GrowthPokemon p=new GrowthPokemon(UUID.randomUUID().toString(),"TREECKO",5);assertEquals("NOT_CAPTURED",c.receive(UUID.randomUUID().toString(),new Pokeball().capturePokemon(p)));assertEquals("ACCEPTED",c.receive(p.captureId,new Pokeball().capturePokemon(p)));Map<String,Object> saved=s.load("collection:invalid");Json.asObject(Json.asArray(saved.get("pokemon")).get(0)).put("maxHp",100);s.save("collection:invalid",saved);assertThrows(IllegalArgumentException.class,()->new PokemonCollection("invalid",s));}

 static AgentRoom.Reply send(AgentRoom r,String cmd,Map<String,Object> params){Map<String,Object> v=r.snapshot();return r.command(Json.object("requestId",UUID.randomUUID().toString(),"taskId",v.get("taskId"),"expectedRevision",v.get("revision"),"command",cmd,"params",params),0);}
 @Test void evolvedActorCanBeSummonedAndRestoredWithHpAbove100(@TempDir Path d){WorldStore s=new FileWorldStore(d);PokemonCollection c=new PokemonCollection("summon-grown",s);GrowthPokemon p=new GrowthPokemon(UUID.randomUUID().toString(),"SWAMPERT",40);assertEquals("ACCEPTED",c.receive(p.captureId,new Pokeball().capturePokemon(p)));AgentRoom room=new AgentRoom("summon-grown",offline(),Runnable::run,true,s,c);assertEquals(200,send(room,"SUMMON",Json.object("captureId",p.captureId,"direction","E")).status);assertEquals(p.maxHp(),Json.asObject(room.snapshot().get("summoned")).get("maxHp"));room.close();AgentRoom restored=new AgentRoom("summon-grown",offline(),Runnable::run,true,s);assertEquals(p.maxHp(),Json.asObject(restored.snapshot().get("summoned")).get("hp"));assertEquals("SWAMPERT",Json.asObject(restored.snapshot().get("summoned")).get("species"));}
 @Test void carriedStarterCanExecuteActualAiCaptureTools(@TempDir Path d){WorldStore s=new FileWorldStore(d);GrowthRoom growth=started("grown-ai",s);String id=(String)Json.asObject(Json.asObject(growth.snapshot().get("world")).get("partner")).get("captureId");assertEquals(200,growth.command(input(growth,"CARRY"),0).status);ProviderSelection ai=new ProviderSelection("test","offline",1000,c->{Map<String,String> o=c.getObservation();return new game.agent.tools.ToolRequest(UUID.randomUUID().toString(),"true".equals(o.get("targetAdjacent"))?"capture":"move_to",Json.object("targetId",o.get("goalTarget")));},(text,q)->TaskIntent.ofGoal(q,"CAPTURE","field-mudkip",EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE),null,null));AgentRoom room=new AgentRoom("grown-ai",ai,Runnable::run,true,s);assertEquals(200,send(room,"PARSE",Json.object("text","捕捉水跃鱼","captureId",id)).status);room.tick(1);assertEquals("READY",room.snapshot().get("status"));assertEquals(200,send(room,"CONFIRM",Collections.emptyMap()).status);for(int n=2;n<60&&!"COMPLETED".equals(room.snapshot().get("status"));n++)room.tick(n);assertEquals("COMPLETED",room.snapshot().get("status"));assertEquals(id,room.snapshot().get("combatPartner"));assertEquals("MUDKIP",Json.asObject(room.snapshot().get("summoned")).get("species"));}
 @Test void postgresCarryAuthorityAndGrowthCheckpointRestore()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");String owner="carry-pg-"+UUID.randomUUID();try(WorldStore s=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){GrowthRoom g=started(owner,s);assertEquals(200,g.command(input(g,"CARRY"),0).status);assertNull(Json.asObject(new GrowthRoom(owner,offline(),Runnable::run,s).snapshot().get("world")).get("partner"));assertEquals(1,new PokemonCollection(owner,s).snapshot().size());}}
}
