package game.agent.web;
import game.agent.growth.*;import game.agent.llm.Json;import game.agent.tools.ToolRequest;import game.agent.persistence.*;import java.util.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.Path;import static org.junit.jupiter.api.Assertions.*;
class GrowthAdventureMigrationTest {
 private AgentRoom.Reply send(GrowthRoom r,String kind,Map<String,Object> params){Map<String,Object>s=r.snapshot();return r.command(Json.object("requestId",UUID.randomUUID().toString(),"taskId",s.get("taskId"),"expectedRevision",s.get("revision"),"command",kind,"params",params),10);}
 private void go(GrowthWorld w,String id){for(int n=0;n<160&&!id.equals(w.region());n++)w.execute("go_to_region",Json.object("regionId",id));assertEquals(id,w.region());}
 @Test void progressedFreeWorldCanConvertAtLabWithoutLosingOwnedProgress(){GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");go(w,"mountain");go(w,"lab");GrowthPokemon extra=new GrowthPokemon(UUID.randomUUID().toString(),"TREECKO",5);w.acceptTraining(extra.export());String team=Json.write(w.view().get("team"));int turn=w.turn();assertEquals(true,w.view().get("adventureAvailable"));assertEquals("ADVENTURE_STARTED",w.startAdventure().getCode());assertEquals(team,Json.write(w.view().get("team")));assertEquals(turn,w.turn());assertEquals("forest",w.expeditionRegion());assertFalse(w.regionUnlocked("river"));assertEquals("POOCHYENA",Json.asObject(Json.asArray(w.view().get("encounters")).get(0)).get("species"));assertEquals(Json.write(w.export()),Json.write(GrowthWorld.restore(w.export(),()->0).export()));String once=Json.write(w.export());assertEquals("ADVENTURE_ALREADY_STARTED",w.startAdventure().getCode());assertEquals(once,Json.write(w.export()));}
 @Test void fieldConversionIsRejectedWithoutMutation(){GrowthWorld w=new GrowthWorld(()->0);w.starter("MUDKIP");go(w,"forest");String before=Json.write(w.export());assertEquals("LAB_REQUIRED",w.startAdventure().getCode());assertEquals(before,Json.write(w.export()));}
 @Test void pausedTrainingMustBeCancelledAndConversionSurvivesRealFileReopen(@TempDir Path directory){try(WorldStore s=new FileWorldStore(directory)){ProviderSelection p=new ProviderSelection("test","test",1000,c->new ToolRequest("test","rest",Collections.emptyMap()),null);GrowthRoom r=new GrowthRoom("conversion",p,Runnable::run,s,()->0);send(r,"STARTER",Json.object("species","MUDKIP"));send(r,"AI_TRAIN",Json.object("targetLevel",17));send(r,"PAUSE",Collections.emptyMap());assertEquals("TRAINING_TASK_PENDING",send(r,"START_ADVENTURE",Collections.emptyMap()).body.get("reasonCode"));assertEquals(200,send(r,"CANCEL",Collections.emptyMap()).status);assertEquals(200,send(r,"START_ADVENTURE",Collections.emptyMap()).status);assertEquals("IDLE",r.snapshot().get("status"));assertEquals(0,r.snapshot().get("targetLevel"));GrowthRoom re=new GrowthRoom("conversion",p,Runnable::run,s,()->0);assertEquals(true,Json.asObject(Json.asObject(re.snapshot().get("world")).get("adventure")).get("enabled"));assertEquals("MUDKIP",Json.asObject(Json.asObject(re.snapshot().get("world")).get("partner")).get("species"));r.close();re.close();}}
}
