package game.agent.web;
import game.agent.growth.*;import game.agent.llm.Json;import game.agent.persistence.*;import game.agent.tools.ToolRequest;import java.util.*;import java.nio.file.Path;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import static org.junit.jupiter.api.Assertions.*;
class GrowthRegionRoomTest {
 private ProviderSelection offline(){return new ProviderSelection("none","offline",1000,null,null);}
 private Map<String,Object> view(GrowthRoom r){return Json.asObject(r.snapshot().get("world"));}
 private AgentRoom.Reply send(GrowthRoom r,String kind,Map<String,Object> params){Map<String,Object> v=r.snapshot();return r.command(Json.object("requestId",UUID.randomUUID().toString(),"taskId",v.get("taskId"),"expectedRevision",v.get("revision"),"command",kind,"params",params),10);}
 private void go(GrowthRoom r,String id){for(int n=0;n<160&&!id.equals(view(r).get("region"));n++)assertEquals(200,send(r,"MANUAL",Json.object("action","go_to_region","arguments",Json.object("regionId",id))).status);assertEquals(id,view(r).get("region"));}
 private void verifyStore(WorldStore store){String owner="regions-"+UUID.randomUUID();GrowthRoom r=new GrowthRoom(owner,offline(),Runnable::run,store,()->0);assertEquals(200,send(r,"STARTER",Json.object("species","TREECKO")).status);go(r,"mountain");Map<String,Object> before=store.load("growth:"+owner);GrowthRoom restored=new GrowthRoom(owner,offline(),Runnable::run,store,()->0);assertEquals(Json.write(before.get("world")),Json.write(store.load("growth:"+owner).get("world")));assertEquals("mountain",view(restored).get("region"));assertEquals(3,Json.asArray(view(restored).get("encounters")).size());go(restored,"river");go(restored,"lab");}
 @Test void realFilePreservesThreeRegionStateAcrossReopen(@TempDir Path d){try(WorldStore s=new FileWorldStore(d)){verifyStore(s);}}
 @Test void realPostgresPreservesThreeRegionStateAcrossReopen()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");try(WorldStore s=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){verifyStore(s);}}
 @Test void chosenAiRegionPersistsAndInvalidRegionCannotStartOrMutate(){GrowthRoomTest.Store s=new GrowthRoomTest.Store();ProviderSelection ai=new ProviderSelection("test","test",1000,c->new ToolRequest("nav","go_to_region",Json.object("regionId",c.getObservation().get("expeditionRegion"))),null);GrowthRoom r=new GrowthRoom("region-ai",ai,Runnable::run,s,()->0);send(r,"STARTER",Json.object("species","TREECKO"));String before=Json.write(view(r));assertEquals("UNKNOWN_REGION",send(r,"AI_TRAIN",Json.object("targetLevel",6,"regionId","lab")).body.get("reasonCode"));assertEquals(before,Json.write(view(r)));assertEquals(200,send(r,"AI_TRAIN",Json.object("targetLevel",6,"regionId","mountain")).status);assertEquals("mountain",view(r).get("expeditionRegion"));send(r,"PAUSE",Collections.emptyMap());GrowthRoom restored=new GrowthRoom("region-ai",ai,Runnable::run,s,()->0);assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals("mountain",view(restored).get("expeditionRegion"));assertEquals(200,send(restored,"RESUME",Collections.emptyMap()).status);for(int n=11;n<160&&!"mountain".equals(view(restored).get("region"));n++)restored.tick(n);assertEquals("mountain",view(restored).get("region"));restored.close();}
 @Test void regionTransitionSaveFailureRecoversCommittedMapWithoutNewWildIds(){GrowthRoomTest.Store s=new GrowthRoomTest.Store();GrowthRoom r=new GrowthRoom("region-fail",offline(),Runnable::run,s,()->0);send(r,"STARTER",Json.object("species","TREECKO"));String before=Json.write(view(r));s.fail=true;assertEquals(503,send(r,"MANUAL",Json.object("action","go_to_region","arguments",Json.object("regionId","river"))).status);assertEquals("STORAGE_ERROR",r.snapshot().get("status"));s.fail=false;assertEquals(200,send(r,"RECOVER",Collections.emptyMap()).status);assertEquals(before,Json.write(view(r)));go(r,"river");}
 @Test void pausedManualTravelCannotReplaceThePersistedAiDestination(){GrowthRoomTest.Store s=new GrowthRoomTest.Store();ProviderSelection ai=new ProviderSelection("test","test",1000,c->new ToolRequest("nav","go_to_region",Json.object("regionId",c.getObservation().get("expeditionRegion"))),null);GrowthRoom r=new GrowthRoom("fixed-region",ai,Runnable::run,s,()->0);send(r,"STARTER",Json.object("species","TREECKO"));send(r,"AI_TRAIN",Json.object("targetLevel",6,"regionId","mountain"));send(r,"PAUSE",Collections.emptyMap());go(r,"river");assertEquals("river",view(r).get("expeditionRegion"));GrowthRoom restored=new GrowthRoom("fixed-region",ai,Runnable::run,s,()->0);assertEquals("mountain",restored.snapshot().get("targetRegion"));assertEquals(200,send(restored,"RESUME",Collections.emptyMap()).status);assertEquals("mountain",view(restored).get("expeditionRegion"));restored.close();}
 @Test void manualEntranceTransitionIsSavedAndReopenedAtArrival(@TempDir Path d){try(WorldStore s=new FileWorldStore(d)){String owner="manual-entrance";GrowthRoom r=new GrowthRoom(owner,offline(),Runnable::run,s,()->0);send(r,"STARTER",Json.object("species","TREECKO"));AgentRoom.Reply reply=send(r,"MANUAL",Json.object("action","move","arguments",Json.object("direction","S")));assertEquals(200,reply.status);assertEquals("forest",view(r).get("region"));assertEquals(9,view(r).get("x"));assertEquals(9,view(r).get("y"));assertEquals(1,view(r).get("turn"));String before=Json.write(view(r));GrowthRoom restored=new GrowthRoom(owner,offline(),Runnable::run,s,()->0);assertEquals(before,Json.write(view(restored)));assertEquals(200,send(restored,"MANUAL",Json.object("action","move","arguments",Json.object("direction","S"))).status);assertEquals("lab",view(restored).get("region"));assertEquals(2,view(restored).get("turn"));}}
 @Test void manualEntranceSaveFailureRestoresTheCommittedRegion(){GrowthRoomTest.Store s=new GrowthRoomTest.Store();GrowthRoom r=new GrowthRoom("manual-entrance-fail",offline(),Runnable::run,s,()->0);send(r,"STARTER",Json.object("species","TREECKO"));String before=Json.write(view(r));s.fail=true;assertEquals(503,send(r,"MANUAL",Json.object("action","move","arguments",Json.object("direction","S"))).status);assertEquals("STORAGE_ERROR",r.snapshot().get("status"));s.fail=false;assertEquals(200,send(r,"RECOVER",Collections.emptyMap()).status);assertEquals(before,Json.write(view(r)));assertEquals("lab",view(r).get("region"));}
}
