package game.agent.web;
import game.agent.llm.Json;import game.agent.persistence.*;import game.agent.tools.ToolRequest;import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class GrowthRoomTest {
 static class Store implements WorldStore{Map<String,Map<String,Object>> values=new HashMap<>();boolean fail,commitThenFail;public void save(String owner,Map<String,Object> checkpoint){if(!fail||commitThenFail)values.put(owner,Json.asObject(Json.read(Json.write(checkpoint))));if(fail)throw new IllegalStateException();}public Map<String,Object> load(String owner){return values.get(owner);}public void close(){}}
 private static ProviderSelection offline(){return new ProviderSelection("openai","unavailable",1000,null,null);}
 private static Map<String,Object> input(GrowthRoom r,String kind,Map<String,Object> params){Map<String,Object> s=r.snapshot();return Json.object("requestId",UUID.randomUUID().toString(),"taskId",s.get("taskId"),"expectedRevision",s.get("revision"),"command",kind,"params",params);}
 private static AgentRoom.Reply command(GrowthRoom r,String kind,Map<String,Object> params){return r.command(input(r,kind,params),10);}
 @Test void persistentReceiptPreventsDuplicateRewardAcrossRestart(){Store store=new Store();GrowthRoom r=new GrowthRoom("owner",offline(),Runnable::run,store,()->0);Map<String,Object> choose=input(r,"STARTER",Json.object("species","MUDKIP"));assertEquals(200,r.command(choose,10).status);GrowthRoom restored=new GrowthRoom("owner",offline(),Runnable::run,store,()->0);assertEquals(200,restored.command(choose,10).status);assertEquals(1,Json.asArray(Json.asObject(restored.snapshot().get("world")).get("team")).size());Map<String,Object> conflict=new LinkedHashMap<>(choose);conflict.put("params",Json.object("species","TORCHIC"));assertEquals("REQUEST_ID_CONFLICT",restored.command(conflict,10).body.get("reasonCode"));GrowthRoom other=new GrowthRoom("other",offline(),Runnable::run,store);assertNull(Json.asObject(other.snapshot().get("world")).get("partner"));}
 @Test void failedSaveFreezesAndRecoveryLoadsOnlyCommittedWorld(){Store store=new Store();GrowthRoom r=new GrowthRoom("owner",offline(),Runnable::run,store,()->0);store.fail=true;assertEquals(503,command(r,"STARTER",Json.object("species","MUDKIP")).status);assertEquals("STORAGE_ERROR",r.snapshot().get("status"));assertEquals(503,command(r,"REST",Collections.emptyMap()).status);assertEquals(200,command(r,"CANCEL",Collections.emptyMap()).status);store.fail=false;assertEquals(200,command(r,"RECOVER",Collections.emptyMap()).status);assertNull(Json.asObject(r.snapshot().get("world")).get("partner"));}
 @Test void uncertainCommitRecoveryRetainsReceiptAndChosenIndividual(){Store store=new Store();GrowthRoom r=new GrowthRoom("owner",offline(),Runnable::run,store,()->0);store.fail=store.commitThenFail=true;Map<String,Object> choose=input(r,"STARTER",Json.object("species","MUDKIP"));assertEquals(503,r.command(choose,10).status);store.fail=false;assertEquals(200,command(r,"RECOVER",Collections.emptyMap()).status);assertEquals(200,r.command(choose,10).status);assertNotNull(Json.asObject(r.snapshot().get("world")).get("partner"));}
 @Test void authorityAndStrictParametersRejectStaleOrUnselectedCommands(){GrowthRoom r=new GrowthRoom("owner",offline(),Runnable::run,null);Map<String,Object> choose=input(r,"STARTER",Json.object("species","MUDKIP"));assertEquals("MODE_NOT_SELECTED",r.command(choose,10,"MODE_NOT_SELECTED").body.get("reasonCode"));assertEquals(200,r.command(choose,10).status);assertEquals(400,command(r,"REST",Json.object("unexpected",true)).status);Map<String,Object> stale=input(r,"REST",Collections.emptyMap());stale.put("expectedRevision",1);assertEquals("STALE_REVISION",r.command(stale,10).body.get("reasonCode"));assertEquals("PROVIDER_CONFIGURATION",command(r,"AI_TRAIN",Json.object("targetLevel",6)).body.get("reasonCode"));}
 @Test void aiPendingPauseAndRestartCannotCommitLateDecisions(){List<Runnable> jobs=new ArrayList<>();ProviderSelection ai=new ProviderSelection("openai","test",1000,c->new ToolRequest("provider","go_to_region",Json.object("regionId","forest")),null);Store store=new Store();GrowthRoom r=new GrowthRoom("owner",ai,jobs::add,store,()->0);command(r,"STARTER",Json.object("species","MUDKIP"));assertEquals(200,command(r,"AI_TRAIN",Json.object("targetLevel",6)).status);r.tick(11);assertEquals(1,jobs.size());assertEquals(200,command(r,"PAUSE",Collections.emptyMap()).status);jobs.get(0).run();r.tick(15);assertEquals("lab",Json.asObject(r.snapshot().get("world")).get("region"));GrowthRoom restored=new GrowthRoom("owner",ai,jobs::add,store,()->0);assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals(200,command(restored,"RESUME",Collections.emptyMap()).status);restored.tick(30);assertEquals("RUNNING",restored.snapshot().get("status"));}
 @Test void boundedReceiptsDoNotPermanentlyLockProgressAndExpiredReplayCannotMutate(){GrowthRoom r=new GrowthRoom("owner",offline(),Runnable::run,null,()->0);Map<String,Object> first=input(r,"STARTER",Json.object("species","MUDKIP"));assertEquals(200,r.command(first,10).status);Map<String,Object> last=null;for(int i=0;i<1030;i++){last=input(r,"REST",Collections.emptyMap());assertEquals(200,r.command(last,10).status,"REST "+i);}assertEquals(200,r.command(last,10).status);assertEquals("STALE_REVISION",r.command(first,10).body.get("reasonCode"));assertEquals(1,Json.asArray(Json.asObject(r.snapshot().get("world")).get("team")).size());}
 @Test void pendingDispatchAndElapsedBudgetArePersistedBeforeProviderReturns(){List<Runnable> jobs=new ArrayList<>();Store store=new Store();ProviderSelection ai=new ProviderSelection("openai","test",15000,c->new ToolRequest("provider","rest",Collections.emptyMap()),null);GrowthRoom r=new GrowthRoom("owner",ai,jobs::add,store,()->0);command(r,"STARTER",Json.object("species","MUDKIP"));command(r,"AI_TRAIN",Json.object("targetLevel",6));r.tick(11);Map<String,Object> saved=store.load("growth:owner");assertEquals(1,((Number)Json.asObject(saved.get("metrics")).get("decisionCount")).intValue());r.tick(1511);assertTrue(((Number)store.load("growth:owner").get("activeMillis")).longValue()>=1500);GrowthRoom restored=new GrowthRoom("owner",ai,jobs::add,store,()->0);assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals(1,((Number)Json.asObject(restored.snapshot().get("metrics")).get("decisionCount")).intValue());}
 @Test void delayedStopFromOldTrainingCannotStopNewTraining(){ProviderSelection ai=new ProviderSelection("openai","test",1000,c->new ToolRequest("provider","rest",Collections.emptyMap()),null);GrowthRoom r=new GrowthRoom("owner",ai,Runnable::run,null,()->0);command(r,"STARTER",Json.object("species","MUDKIP"));command(r,"AI_TRAIN",Json.object("targetLevel",6));Map<String,Object> delayed=input(r,"CANCEL",Collections.emptyMap());command(r,"CANCEL",Collections.emptyMap());command(r,"AI_TRAIN",Json.object("targetLevel",7));assertEquals("STALE_TASK",r.command(delayed,10).body.get("reasonCode"));assertEquals("RUNNING",r.snapshot().get("status"));}
 @Test void realPostgresRestoresGrowthRoom()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");JdbcWorldStore.ConnectionFactory connection=()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),"");String owner=UUID.randomUUID().toString();try(WorldStore store=new JdbcWorldStore(connection)){GrowthRoom r=new GrowthRoom(owner,offline(),Runnable::run,store,()->0);assertEquals(200,command(r,"STARTER",Json.object("species","TREECKO")).status);}try(WorldStore store=new JdbcWorldStore(connection)){GrowthRoom r=new GrowthRoom(owner,offline(),Runnable::run,store,()->0);assertEquals("TREECKO",Json.asObject(Json.asObject(r.snapshot().get("world")).get("partner")).get("species"));assertEquals(true,r.snapshot().get("recovered"));}}

 @Test void higherTrainingGoalsPersistAcrossPauseAndReloadButRejectAboveCap(){
  Store store=new Store();ProviderSelection ai=new ProviderSelection("openai","test",1000,c->new ToolRequest("provider","rest",Collections.emptyMap()),null);GrowthRoom r=new GrowthRoom("high",ai,Runnable::run,store,()->0);command(r,"STARTER",Json.object("species","TORCHIC"));
  assertEquals("INVALID_TARGET_LEVEL",command(r,"AI_TRAIN",Json.object("targetLevel",41)).body.get("reasonCode"));assertEquals(200,command(r,"AI_TRAIN",Json.object("targetLevel",36)).status);command(r,"PAUSE",Collections.emptyMap());GrowthRoom restored=new GrowthRoom("high",ai,Runnable::run,store,()->0);assertEquals(36,restored.snapshot().get("targetLevel"));assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals(200,command(restored,"RESUME",Collections.emptyMap()).status);
 }

 @Test void realFileCheckpointStaysWithinBudgetDuringLongPlayAndLegacyReceiptLoad(@org.junit.jupiter.api.io.TempDir java.nio.file.Path directory){
  try(WorldStore store=new FileWorldStore(directory)){
   GrowthRoom r=new GrowthRoom("long-file",offline(),Runnable::run,store,()->0);Map<String,Object> first=input(r,"STARTER",Json.object("species","MUDKIP"));assertEquals(200,r.command(first,10).status);
   for(int n=0;n<620;n++)assertEquals(200,command(r,"REST",Collections.emptyMap()).status,"actual file save "+n);
   assertEquals(64,Json.asArray(store.load("growth:long-file").get("receipts")).size());GrowthRoom restored=new GrowthRoom("long-file",offline(),Runnable::run,store,()->0);assertEquals("STALE_REVISION",restored.command(first,10).body.get("reasonCode"));assertEquals(200,command(restored,"REST",Collections.emptyMap()).status);
  }
  Store legacy=new Store();GrowthRoom source=new GrowthRoom("legacy",offline(),Runnable::run,legacy,()->0);command(source,"STARTER",Json.object("species","MUDKIP"));Map<String,Object> saved=legacy.load("growth:legacy");List<Object> receipts=Json.asArray(saved.get("receipts"));Map<String,Object> example=Json.asObject(receipts.get(0));for(int n=0;n<130;n++){Map<String,Object> copy=new LinkedHashMap<>(example);copy.put("id","legacy-"+n);receipts.add(copy);}GrowthRoom restored=new GrowthRoom("legacy",offline(),Runnable::run,legacy,()->0);assertEquals(200,command(restored,"REST",Collections.emptyMap()).status);assertEquals(64,Json.asArray(legacy.load("growth:legacy").get("receipts")).size());
 }
}
