package game.agent;
import game.agent.web.*;import game.agent.llm.*;import game.agent.tools.*;import game.agent.persistence.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class MixedAgentTest {
 static Map<String,Object> berry(){return Json.object("kind","COMPLETE_QUEST","targetId",null);}
 static Map<String,Object> capture(){return Json.object("kind","CAPTURE","targetId","field-treecko");}
 static Map<String,Object> defeat(){return Json.object("kind","DEFEAT","targetId","field-torchic");}
 static ProviderSelection provider(List<Map<String,Object>> steps,Long deadline){return new ProviderSelection("test","offline",1000,c->{Map<String,String> o=c.getObservation();String op;Map<String,Object> args;
  if("COMPLETE_QUEST".equals(o.get("goalType"))){int carried=Integer.parseInt(o.get("carriedBerry")),visible=Integer.parseInt(o.get("visibleBerry"));
   if(carried>=3&&"true".equals(o.get("nearProfessor"))){op="deliver";args=Json.object("questId",o.get("questId"),"targetNpcId","professor");}
   else if(carried<3&&visible>0){op="pickup";args=Json.object("itemId","BERRY","quantity",Math.min(3-carried,visible));}
   else{op="move_to_location";args=Json.object("locationId",carried>=3?"laboratory":carried>=2?"alternative":"orchard");}}
  else{op="true".equals(o.get("targetAdjacent"))?("CAPTURE".equals(o.get("goalType"))?"capture":"attack"):"move_to";args=Json.object("targetId",o.get("goalTarget"));}
  return new ToolRequest(UUID.randomUUID().toString(),op,args);
 },(text,q)->TaskIntent.ofMixed(q,steps,deadline==null?EnumSet.of(TaskIntent.Constraint.NO_SPENDING):EnumSet.of(TaskIntent.Constraint.NO_SPENDING,TaskIntent.Constraint.DEADLINE),null,deadline));}
 static AgentRoom room(String owner,List<Map<String,Object>> steps,WorldStore store){return new AgentRoom(owner,provider(steps,null),Runnable::run,true,store);}
 static void run(AgentRoom r,int start){for(int i=start;i<250&&!Arrays.asList("COMPLETED","FAILED","PAUSED").contains(r.snapshot().get("status"));i++)r.tick(i);assertEquals("COMPLETED",r.snapshot().get("status"),Json.write(r.snapshot()));}
 @Test void allThreeBerryPositionsCompleteOnlyAfterEveryRealStage(){for(List<Map<String,Object>> steps:Arrays.asList(Arrays.asList(berry(),capture(),defeat()),Arrays.asList(capture(),berry(),defeat()),Arrays.asList(capture(),defeat(),berry()))){AgentRoom r=room("mixed-"+UUID.randomUUID(),steps,null);FieldAgentTest.start(r);boolean intermediate=false;for(int i=3;i<250&&!"COMPLETED".equals(r.snapshot().get("status"));i++){r.tick(i);if(((Number)r.snapshot().get("delivered")).intValue()==3&&!"DEFEATED".equals(FieldAgentTest.target(r,"field-torchic").get("state"))){intermediate=true;assertNotEquals("COMPLETED",r.snapshot().get("status"));}}assertEquals("COMPLETED",r.snapshot().get("status"),Json.write(r.snapshot()));assertEquals(3,r.snapshot().get("delivered"));assertEquals("CAPTURED",FieldAgentTest.target(r,"field-treecko").get("state"));assertEquals("DEFEATED",FieldAgentTest.target(r,"field-torchic").get("state"));assertEquals("5",Json.asObject(r.snapshot().get("world")).get("coins"));if(!"COMPLETE_QUEST".equals(steps.get(2).get("kind")))assertTrue(intermediate);}}
 @Test void rejectsRepeatedBerriesMissingBerriesAndGlobalBattleConflict(){for(List<Map<String,Object>> rows:Arrays.asList(Arrays.asList(berry(),berry()),Arrays.asList(capture(),defeat()),Arrays.asList(berry(),capture(),capture())))assertThrows(IllegalArgumentException.class,()->TaskIntent.ofMixed("q",rows,EnumSet.noneOf(TaskIntent.Constraint.class),null,null));assertThrows(IllegalArgumentException.class,()->TaskIntent.ofMixed("q",Arrays.asList(berry(),defeat()),EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE),null,null));}
 @Test void phaseGuardRejectsFieldActionsDuringBerryAndBerryActionsDuringField(){game.agent.demo.GeminiQuestScenario s=new game.agent.demo.GeminiQuestScenario("guard",true);game.agent.runtime.AgentLoop loop=s.start(TaskIntent.ofMixed(s.getSession().getQuestId(),Arrays.asList(berry(),capture()),EnumSet.noneOf(TaskIntent.Constraint.class),null,null),c->new ToolRequest("wrong","capture",Json.object("targetId","field-treecko")),Runnable::run);loop.tick(1);assertEquals("STAGE_OPERATION_NOT_ALLOWED",loop.tick(2).getCode());assertEquals(0,s.getSession().getTurn());AgentRoom r=room("manual-mixed",Arrays.asList(capture(),berry()),null);FieldAgentTest.start(r);OwnedAgentTest.send(r,"PAUSE",Collections.emptyMap());assertEquals("STAGE_OPERATION_NOT_ALLOWED",OwnedAgentTest.send(r,"MANUAL",Json.object("action","pickup","arguments",Json.object("quantity",1))).body.get("reasonCode"));}
 @Test void restoreAfterBerryDeliveryKeepsWildStageAndNeverDeliversTwice(@TempDir Path d){recover(new FileWorldStore(d),"mixed-file-"+UUID.randomUUID());}
 static void recover(WorldStore store,String owner){List<Map<String,Object>> steps=Arrays.asList(berry(),capture());AgentRoom r=room(owner,steps,store);FieldAgentTest.start(r);int n=3;while(n<180&&((Number)r.snapshot().get("delivered")).intValue()<3)r.tick(n++);assertEquals(3,r.snapshot().get("delivered"),Json.write(r.snapshot()));assertNotEquals("COMPLETED",r.snapshot().get("status"));OwnedAgentTest.send(r,"PAUSE",Collections.emptyMap());r.close();AgentRoom restored=room(owner,steps,store);assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals("MIXED",restored.snapshot().get("taskKind"));assertEquals(3,restored.snapshot().get("delivered"));assertEquals(200,OwnedAgentTest.send(restored,"RESUME",Collections.emptyMap()).status);run(restored,n);assertEquals(3,restored.snapshot().get("delivered"));restored.close();assertEquals("COMPLETED",room(owner,steps,store).snapshot().get("status"));}
 @Test void ownedWildActorSwitchesToLeaderForBerryAndBack(@TempDir Path d){WorldStore store=new FileWorldStore(d);String owner="mixed-owned";OwnedAgentTest.seed(store,owner,"MUDKIP",100);AgentRoom r=room(owner,Arrays.asList(capture(),berry(),defeat()),store);OwnedAgentTest.parse(r);assertEquals(200,OwnedAgentTest.send(r,"CONFIRM",Collections.emptyMap()).status);run(r,3);assertEquals(3,r.snapshot().get("delivered"));assertEquals(OwnedAgentTest.ID,r.snapshot().get("combatPartner"));assertTrue(((Number)Json.asObject(r.snapshot().get("summoned")).get("hp")).intValue()>0);String trace=Json.write(r.snapshot().get("stepTrace"));assertTrue(trace.contains(OwnedAgentTest.ID));assertTrue(trace.contains("mudkip"));}
 @Test void shortDeadlineFailsMixedWithoutInventingLaterResult(){AgentRoom r=new AgentRoom("mixed-deadline",provider(Arrays.asList(capture(),berry()),3L),Runnable::run,true,null);FieldAgentTest.start(r);for(int i=3;i<40&&!"FAILED".equals(r.snapshot().get("status"));i++)r.tick(i);assertEquals("FAILED",r.snapshot().get("status"));assertEquals(0,r.snapshot().get("delivered"));}
 @Test void parserAcceptsExplicitMixedOrderedSteps(){String body=OpenAiGatewayTest.text(Json.write(Json.object("status","SUPPORTED","goal","MIXED","questId","q","targetId",null,"steps",Arrays.asList(berry(),capture()),"constraints",Collections.emptyList(),"areaId",null,"deadlineTurn",null,"unsupportedClauses",Collections.emptyList())));TaskIntent t=OpenAiGatewayTest.gateway((m,k,b,time)->new JsonTransport.Response(200,body)).parse("先树果再捕捉","q");assertTrue(t.isMixed());assertNull(t.getSteps().get(0).getTargetId());}
 @Test void postgresRestoresBetweenBerryAndWildStage()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");try(WorldStore store=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){recover(store,"mixed-pg-"+UUID.randomUUID());}}
 @Test void mixedObserveDoesNotSpendWorldTurn(){ProviderSelection p=new ProviderSelection("test","offline",1000,c->new ToolRequest(UUID.randomUUID().toString(),"observe",Collections.emptyMap()),(text,q)->TaskIntent.ofMixed(q,Arrays.asList(berry(),capture()),EnumSet.noneOf(TaskIntent.Constraint.class),null,null));AgentRoom r=new AgentRoom("mixed-observe",p,Runnable::run,true,null);FieldAgentTest.start(r);r.tick(3);r.tick(4);assertEquals("0",Json.asObject(r.snapshot().get("world")).get("turn"));assertEquals("RUNNING",r.snapshot().get("status"));}
}
