package game.agent;
import game.agent.multi.*;import game.agent.multi.MultiAgentFoundation.Role;
import game.agent.llm.*;import game.agent.tools.*;import game.agent.action.*;import game.agent.web.*;import game.agent.persistence.*;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;import java.util.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;
class NpcAgentRuntimeTest {
 Map<String,String> observation(Role role){Map<String,String> map=new LinkedHashMap<>();map.put("turn","0");map.put("facts",Json.write(Arrays.asList(Json.object("id","fact","subject","BERRY","x",31,"y",10,"quantity",2))));return map;}
 LlmGateway sender(){return c->new ToolRequest("untrusted-id","send_message",Json.object("recipient","mudkip","factId","fact"));}
 NpcAgentRuntime runtime(LlmGateway gateway,java.util.concurrent.Executor executor){return new NpcAgentRuntime("world",gateway,executor,10,this::observation,(r,t)->ActionResult.success("NPC_OBSERVED"));}
 @Test void eachNpcCallsModelAndOnlyObservedFactsBecomeMessages(){List<String> roles=new ArrayList<>();NpcAgentRuntime r=runtime(c->{roles.add(c.getObservation().get("inbox"));return sender().decide(c);},Runnable::run);for(int i=0;i<6;i++)assertTrue(r.tick(0,0,0));assertEquals(3,roles.size());assertEquals(3,r.inbox(Role.MUDKIP,0).size());assertEquals("torchic",r.inbox(Role.MUDKIP,0).get(0).get("sender"));}
 @Test void forgedFactCannotBecomeMemory(){NpcAgentRuntime r=runtime(c->new ToolRequest("bad","send_message",Json.object("recipient","mudkip","factId","not-visible")),Runnable::run);r.tick(0,0,0);r.tick(1,0,0);assertTrue(r.inbox(Role.MUDKIP,0).isEmpty());assertEquals("FACT_NOT_OBSERVED",Json.asObject(Json.asArray(r.view(0).get("trace")).get(0)).get("code"));}
 @Test void staleModelResultCannotSendMessage(){NpcAgentRuntime r=runtime(sender(),Runnable::run);r.tick(0,0,0);r.tick(1,0,1);assertTrue(r.inbox(Role.MUDKIP,0).isEmpty());assertEquals("STALE_OBSERVATION",Json.asObject(Json.asArray(r.view(0).get("trace")).get(0)).get("code"));}
 @Test void timeoutDiscardsLateResultAndNextNpcStillRuns(){Queue<Runnable> jobs=new ArrayDeque<>();NpcAgentRuntime r=runtime(sender(),jobs::add);r.tick(0,0,0);r.tick(11,0,0);jobs.remove().run();assertTrue(r.inbox(Role.MUDKIP,0).isEmpty());r.tick(12,0,0);jobs.remove().run();r.tick(13,0,0);assertEquals("professor",r.inbox(Role.MUDKIP,0).get(0).get("sender"));}
 @Test void pauseAndCancelInvalidatePendingWorker(){Queue<Runnable> jobs=new ArrayDeque<>();NpcAgentRuntime r=runtime(sender(),jobs::add);r.tick(0,0,0);r.pause();jobs.remove().run();assertFalse(r.tick(1,0,0));r.resume();r.tick(2,0,0);r.cancel();jobs.remove().run();assertFalse(r.tick(3,0,0));assertTrue(r.inbox(Role.MUDKIP,0).isEmpty());}
 @Test void invalidToolCannotReachEngine(){int[] actions={0};NpcAgentRuntime r=new NpcAgentRuntime("world",c->new ToolRequest("bad","purchase",Collections.emptyMap()),Runnable::run,10,this::observation,(role,t)->{actions[0]++;return ActionResult.success("BAD");});r.tick(0,0,0);r.tick(1,0,0);assertEquals(0,actions[0]);}
 @Test void rejectedExecutorDoesNotLeaveStuckLease(){NpcAgentRuntime r=runtime(sender(),job->{throw new RejectedExecutionException();});for(int i=0;i<20;i++)r.tick(i,0,0);assertEquals("COMPLETED",r.view(0).get("status"));}
 @Test void restorePausesAndPreservesMessages(){NpcAgentRuntime r=runtime(sender(),Runnable::run);r.tick(0,0,0);r.tick(1,0,0);NpcAgentRuntime restored=runtime(sender(),Runnable::run);restored.restore(r.checkpoint(),"world");assertEquals("PAUSED",restored.view(0).get("status"));assertEquals(r.inbox(Role.MUDKIP,0),restored.inbox(Role.MUDKIP,0));assertThrows(IllegalArgumentException.class,()->restored.restore(r.checkpoint(),"other-world"));}
 ProviderSelection provider(){return new ProviderSelection("test","offline",1000,c->{if(c.getTools().get(0).getName().equals("reflect_plan"))return V3CognitionTest.plan(c,"SEND_FACT");List<Object> facts=Json.asArray(Json.read(c.getObservation().getOrDefault("facts","[]")));return new ToolRequest("offline","send_message",Json.object("recipient","mudkip","factId",Json.asObject(facts.get(0)).get("id")));},(text,q)->TaskIntent.of(q,EnumSet.noneOf(TaskIntent.Constraint.class),null,null));}
 void start(AgentRoom r){assertEquals(200,r.command(AgentRoomTest.command(r,"NPC_START",Collections.emptyMap()),0).status);}
 @Test void originalMapNpcFactsAreScopedAndMessagingDoesNotAdvanceWorld(){AgentRoom r=new AgentRoom("npc",provider(),Runnable::run,true,null);start(r);assertTrue(Json.asObject(r.snapshot().get("npcs")).containsKey("torchic"));for(int i=0;i<12;i++)r.tick(i);Map<String,Object> v=r.snapshot();assertEquals("0",Json.asObject(v.get("world")).get("turn"));assertEquals(3,Json.asArray(Json.asObject(v.get("npcAgents")).get("messages")).size());}
 @Test void roomRestartPreservesNpcsMessagesAndPausesCalls(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);AgentRoom r=new AgentRoom("npc",provider(),Runnable::run,true,store);start(r);r.tick(0);r.tick(1);Map<String,Object> expected=Json.asObject(r.snapshot().get("npcAgents"));r.close();AgentRoom loaded=new AgentRoom("npc",provider(),Runnable::run,true,store);Map<String,Object> actual=Json.asObject(loaded.snapshot().get("npcAgents"));assertEquals("PAUSED",actual.get("status"));assertEquals(expected.get("messages"),actual.get("messages"));assertTrue(Json.asObject(loaded.snapshot().get("npcs")).containsKey("torchic"));}
 @Test void worldMovesTorchicWithoutMovingMudkip(){game.agent.demo.GeminiQuestScenario s=new game.agent.demo.GeminiQuestScenario("npc",true);s.enableNpcAgents();Object leader=s.partnerState(false);Map<String,String> professor=s.npcObservation(Role.PROFESSOR);assertFalse(professor.get("facts").contains("BERRY_"));ActionResult result=s.npcAction(Role.TORCHIC,new ToolRequest("move","move",Json.object("direction","E")));assertEquals(ActionResult.Status.SUCCESS,result.getStatus());assertEquals(Json.asObject(leader).get("x"),s.partnerState(false).get("x"));assertEquals(Json.asObject(leader).get("y"),s.partnerState(false).get("y"));assertEquals(34,Json.asObject(s.getNpcPositions().get("torchic")).get("x"));assertEquals(1,s.getSession().getTurn());}
 @Test void databaseRestoresNpcMessageAndLifecycle()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");String owner="npc-pg-"+UUID.randomUUID();try(WorldStore store=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){AgentRoom r=new AgentRoom(owner,provider(),Runnable::run,true,store);start(r);r.tick(0);r.tick(1);Object messages=Json.asObject(r.snapshot().get("npcAgents")).get("messages");r.close();AgentRoom loaded=new AgentRoom(owner,provider(),Runnable::run,true,store);assertEquals(messages,Json.asObject(loaded.snapshot().get("npcAgents")).get("messages"));assertEquals("PAUSED",Json.asObject(loaded.snapshot().get("npcAgents")).get("status"));}}
}
