package game.agent;
import game.agent.multi.*;import game.agent.multi.MultiAgentFoundation.Role;import game.agent.llm.*;import game.agent.tools.*;import game.agent.action.*;
import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class NpcKnowledgeTest {
 Map<String,String> observation(int n,int turn){Map<String,String> o=new LinkedHashMap<>();o.put("turn",""+turn);o.put("position","{\"x\":33,\"y\":10}");o.put("facts",Json.write(Arrays.asList(Json.object("id","berry","subject","BERRY","x",31,"y",10,"quantity",n))));return o;}
 @Test void unchangedObservationsDoNotDuplicateHistory(){NpcKnowledge k=new NpcKnowledge();assertTrue(k.observe(Role.TORCHIC,observation(2,0)));assertFalse(k.observe(Role.TORCHIC,observation(2,1)));assertEquals(1,Json.asArray(k.view(Role.TORCHIC).get("observations")).size());}
 @Test void changedObservationProducesEvidenceBackedSummary(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,observation(2,0));k.observe(Role.TORCHIC,observation(1,1));assertEquals(2,Json.asArray(Json.asObject(k.view(Role.TORCHIC).get("reflection")).get("evidenceIds")).size());assertEquals("RULE_BASED",Json.asObject(k.view(Role.TORCHIC).get("reflection")).get("kind"));}
 @Test void historiesAreScopedAndBounded(){NpcKnowledge k=new NpcKnowledge();for(int i=0;i<30;i++)k.observe(Role.TORCHIC,observation(i,i));assertEquals(16,Json.asArray(k.view(Role.TORCHIC).get("observations")).size());assertTrue(Json.asArray(k.view(Role.MERCHANT).get("observations")).isEmpty());}
 @Test void checkpointRoundTripPreservesEvidence(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,observation(2,0));assertEquals(k.view(Role.TORCHIC),NpcKnowledge.restore(k.checkpoint()).view(Role.TORCHIC));}
 @Test void invalidSourceAndFutureRewindAreRejected(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,observation(2,2));assertThrows(IllegalArgumentException.class,()->k.observe(Role.TORCHIC,observation(1,1)));Map<String,Object> saved=k.checkpoint();Json.asObject(Json.asArray(saved.get("torchic")).get(0)).put("source","MODEL_CLAIM");assertThrows(IllegalArgumentException.class,()->NpcKnowledge.restore(saved));}
 @Test void snapshotsCannotOverwriteMemory(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,observation(2,0));Json.asObject(Json.asArray(k.view(Role.TORCHIC).get("observations")).get(0)).put("source","forged");assertEquals("SELF_OBSERVATION",Json.asObject(Json.asArray(k.view(Role.TORCHIC).get("observations")).get(0)).get("source"));}
 @Test void unchangedSuccessfulRolesDoNotCallModelAgain(){int[] calls={0};NpcAgentRuntime r=new NpcAgentRuntime("world",c->{calls[0]++;return new ToolRequest("decision","send_message",Json.object("recipient","mudkip","factId","berry"));},Runnable::run,10,role->observation(2,0),(role,t)->ActionResult.success("NPC_OBSERVED"));for(int i=0;i<25;i++)r.tick(0,0,0);assertEquals(3,calls[0]);assertEquals(3,r.inbox(Role.MUDKIP,0).size());}
 @Test void failedCallsRemainEligibleForRetry(){int[] calls={0};NpcAgentRuntime r=new NpcAgentRuntime("world",c->{calls[0]++;throw new ProviderException(ProviderException.Code.UNAVAILABLE);},Runnable::run,10,role->observation(2,0),(role,t)->ActionResult.success("NPC_OBSERVED"));for(int i=0;i<25;i++)r.tick(0,0,0);assertEquals(12,calls[0]);}
}
