package game.agent;
import game.agent.web.*;import game.agent.llm.*;import game.agent.tools.*;import game.agent.persistence.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import java.util.concurrent.atomic.*;import static org.junit.jupiter.api.Assertions.*;
class OwnedAgentTest {
 static final String ID="11111111-1111-1111-1111-111111111111";
 static void seed(WorldStore store,String owner,String species,int hp){store.save("collection:"+owner,Json.object("schemaVersion",1,"kind","POKEMON_COLLECTION","pokemon",Arrays.asList(Json.object("captureId",ID,"species",species,"hp",hp,"maxHp",100)),"deployment",null));}
 static AgentRoom room(WorldStore store,String owner,String kind,String target){seed(store,owner,"TREECKO",100);return new AgentRoom(owner,FieldAgentTest.provider(kind,target,EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger()),Runnable::run,true,store);}
 static AgentRoom.Reply send(AgentRoom r,String command,Map<String,Object> p){return r.command(AgentRoomTest.command(r,command,p),0);}
 static void parse(AgentRoom r){assertEquals(200,send(r,"PARSE",Json.object("text","捕捉一只野生水跃鱼","captureId",ID)).status);r.tick(1);assertEquals("READY",r.snapshot().get("status"));}
 static void run(AgentRoom r){for(int i=3;i<70&&!"COMPLETED".equals(r.snapshot().get("status"));i++)r.tick(i);}
 @Test void confirmedOwnedActorAutomaticallySummonsAndCapturesWithoutMovingLeader(@TempDir Path d){AgentRoom r=room(new FileWorldStore(d),"owned","CAPTURE","field-mudkip");parse(r);assertNull(r.snapshot().get("summoned"));assertEquals(ID,r.snapshot().get("aiPartner"));assertEquals(200,send(r,"CONFIRM",Collections.emptyMap()).status);assertEquals(ID,r.snapshot().get("combatPartner"));assertEquals("0",Json.asObject(r.snapshot().get("world")).get("turn"));run(r);assertEquals("COMPLETED",r.snapshot().get("status"));assertEquals("CAPTURED",FieldAgentTest.target(r,"field-mudkip").get("state"));assertEquals("29",Json.asObject(r.snapshot().get("world")).get("x"));assertEquals("10",Json.asObject(r.snapshot().get("world")).get("y"));assertEquals(100,Json.asObject(r.snapshot().get("summoned")).get("hp"));assertEquals("TREECKO",Json.asObject(r.snapshot().get("aiPartnerState")).get("species"));}
 @Test void unownedSelectionIsRejectedBeforeProviderOrWorldMutation(@TempDir Path d){AgentRoom r=room(new FileWorldStore(d),"ownership","CAPTURE","field-mudkip");assertEquals("NOT_OWNED",send(r,"PARSE",Json.object("text","捕捉水跃鱼","captureId",UUID.randomUUID().toString())).body.get("reasonCode"));assertEquals("IDLE",r.snapshot().get("status"));assertNull(r.snapshot().get("summoned"));}
 @Test void ownedSelectionCannotSilentlyExecuteBerryOrCooperativeTask(@TempDir Path d){WorldStore store=new FileWorldStore(d);seed(store,"berries","MUDKIP",100);AgentRoom r=new AgentRoom("berries",new ProviderSelection("test","offline",1000,c->new ToolRequest("o","observe",Collections.emptyMap()),(text,q)->TaskIntent.of(q,EnumSet.noneOf(TaskIntent.Constraint.class),null,null)),Runnable::run,true,store);parse(r);assertEquals("OWNED_FIELD_ONLY",send(r,"CONFIRM",Collections.emptyMap()).body.get("reasonCode"));assertNull(r.snapshot().get("summoned"));}
 @Test void readyCheckpointPreservesChosenOwnedIndividualUntilConfirmation(@TempDir Path d){WorldStore store=new FileWorldStore(d);AgentRoom r=room(store,"ready-owned","CAPTURE","field-mudkip");parse(r);r.close();AgentRoom restored=new AgentRoom("ready-owned",FieldAgentTest.provider("CAPTURE","field-mudkip",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger()),Runnable::run,true,store);assertEquals(ID,restored.snapshot().get("aiPartner"));assertNull(restored.snapshot().get("summoned"));assertEquals(200,send(restored,"CONFIRM",Collections.emptyMap()).status);run(restored);assertEquals("COMPLETED",restored.snapshot().get("status"));}
 @Test void runningOwnedTaskRestoresPausedWithCorrectActorAndCanResume(@TempDir Path d){WorldStore store=new FileWorldStore(d);AgentRoom r=room(store,"running-owned","CAPTURE","field-mudkip");parse(r);send(r,"CONFIRM",Collections.emptyMap());r.tick(3);r.tick(4);String position=Json.write(r.snapshot().get("summoned"));r.close();AgentRoom restored=new AgentRoom("running-owned",FieldAgentTest.provider("CAPTURE","field-mudkip",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger()),Runnable::run,true,store);assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals(position,Json.write(restored.snapshot().get("summoned")));assertEquals(ID,restored.snapshot().get("combatPartner"));assertEquals(200,send(restored,"RESUME",Collections.emptyMap()).status);run(restored);assertEquals("COMPLETED",restored.snapshot().get("status"));}
 @Test void ownedTaskLocksManualRecallAndPartnerChangesWhileRunning(@TempDir Path d){AgentRoom r=room(new FileWorldStore(d),"lock-owned","CAPTURE","field-mudkip");parse(r);send(r,"CONFIRM",Collections.emptyMap());for(String cmd:Arrays.asList("RECALL","PARTNER"))assertEquals("AI_CONTROLS_COMPANION",send(r,cmd,Json.object("captureId",ID)).body.get("reasonCode"));send(r,"PAUSE",Collections.emptyMap());assertEquals(200,send(r,"RECALL",Json.object("captureId",ID)).status);assertEquals("AI_PARTNER_NOT_SUMMONED",send(r,"RESUME",Collections.emptyMap()).body.get("reasonCode"));}
 @Test void corruptUnknownOwnedBindingCannotBeRestored(@TempDir Path d){WorldStore store=new FileWorldStore(d);AgentRoom r=room(store,"corrupt-owned","CAPTURE","field-mudkip");parse(r);Map<String,Object> cp=store.load("corrupt-owned");cp.put("aiPartner",UUID.randomUUID().toString());store.save("corrupt-owned",cp);assertThrows(IllegalArgumentException.class,()->new AgentRoom("corrupt-owned",FieldAgentTest.provider("CAPTURE","field-mudkip",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger()),Runnable::run,true,store));}
 @Test void ownedSummonCommitFailureFreezesBeforeAiStarts(@TempDir Path d){FileWorldStore base=new FileWorldStore(d);boolean[] fail={false};WorldStore store=new WorldStore(){public Map<String,Object> load(String o){return base.load(o);}public void save(String o,Map<String,Object> v){if(fail[0]&&o.startsWith("collection:"))throw new StoreException(StoreException.Code.IO_ERROR);base.save(o,v);}public void close(){}};AgentRoom r=room(store,"fail-owned","CAPTURE","field-mudkip");parse(r);fail[0]=true;assertEquals(503,send(r,"CONFIRM",Collections.emptyMap()).status);assertEquals("STORAGE_ERROR",r.snapshot().get("status"));fail[0]=false;assertEquals(200,send(r,"RECOVER",Collections.emptyMap()).status);assertEquals("READY",r.snapshot().get("status"));assertNull(r.snapshot().get("summoned"));assertEquals(200,send(r,"CONFIRM",Collections.emptyMap()).status);run(r);assertEquals("COMPLETED",r.snapshot().get("status"));}
 @Test void ownedAttackWithLowHpPausesWithoutRiskingRealPokemon(@TempDir Path d){WorldStore store=new FileWorldStore(d);seed(store,"low-owned","MUDKIP",1);AgentRoom r=new AgentRoom("low-owned",FieldAgentTest.provider("DEFEAT","field-torchic",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger()),Runnable::run,true,store);parse(r);send(r,"CONFIRM",Collections.emptyMap());for(int i=3;i<60&&!"PAUSED".equals(r.snapshot().get("status"));i++)r.tick(i);assertEquals("PAUSED",r.snapshot().get("status"));assertEquals("PARTNER_EXHAUSTED",r.snapshot().get("errorCode"));assertEquals(1,Json.asObject(r.snapshot().get("summoned")).get("hp"));assertEquals("WILD",FieldAgentTest.target(r,"field-torchic").get("state"));}
 @Test void ownedActorExecutesEveryStageOfOrderedCapturePlan(@TempDir Path d){WorldStore store=new FileWorldStore(d);seed(store,"sequence-owned","MUDKIP",100);ProviderSelection provider=new ProviderSelection("test","offline",1000,c->{Map<String,String> o=c.getObservation();return new ToolRequest(UUID.randomUUID().toString(),"true".equals(o.get("targetAdjacent"))?"capture":"move_to",Json.object("targetId",o.get("goalTarget")));},(text,q)->TaskIntent.ofSequence(q,Arrays.asList(Json.object("kind","CAPTURE","targetId","field-treecko"),Json.object("kind","CAPTURE","targetId","field-mudkip")),EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE),null,null));AgentRoom r=new AgentRoom("sequence-owned",provider,Runnable::run,true,store);parse(r);send(r,"CONFIRM",Collections.emptyMap());run(r);assertEquals("COMPLETED",r.snapshot().get("status"));assertEquals("CAPTURED",FieldAgentTest.target(r,"field-treecko").get("state"));assertEquals("CAPTURED",FieldAgentTest.target(r,"field-mudkip").get("state"));assertEquals(ID,r.snapshot().get("combatPartner"));assertEquals("29",Json.asObject(r.snapshot().get("world")).get("x"));}
 @Test void postgresOwnedPartnerBindingAndReadyConfirmationRecover()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");String owner="owned-pg-"+UUID.randomUUID();try(WorldStore store=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){AgentRoom r=room(store,owner,"CAPTURE","field-mudkip");parse(r);r.close();AgentRoom restored=new AgentRoom(owner,FieldAgentTest.provider("CAPTURE","field-mudkip",EnumSet.noneOf(TaskIntent.Constraint.class),null,null,new AtomicInteger()),Runnable::run,true,store);assertEquals(ID,restored.snapshot().get("aiPartner"));assertEquals(200,send(restored,"CONFIRM",Collections.emptyMap()).status);run(restored);assertEquals("COMPLETED",restored.snapshot().get("status"));}}
}
