package game.agent;
import game.agent.web.PlayerIdentity;import game.agent.persistence.*;import game.agent.llm.Json;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class PlayerIdentityTest {
 @TempDir Path dir;
 @Test void inviteCopiesOldSaveAndDevicesShareOwnerWithoutPersistingSecrets(){try(FileWorldStore store=new FileWorldStore(dir)){store.save("growth:old",Json.object("hello","world"));PlayerIdentity ids=new PlayerIdentity(store,Set.of(PlayerIdentity.hash("invite-test")));Map<String,Object> created=ids.redeem("old","invite-test");String owner=(String)created.get("owner"),device=(String)created.get("device"),recovery=(String)created.get("recovery");assertEquals(owner,ids.resolve(device));assertEquals("world",store.load("growth:"+owner).get("hello"));assertNotNull(store.load("growth:old"));assertThrows(IllegalArgumentException.class,()->ids.redeem("other","invite-test"));PlayerIdentity restart=new PlayerIdentity(store,Set.of());assertEquals(owner,restart.resolve(device));Map<String,Object> second=restart.restoreDevice(recovery);assertEquals(owner,restart.resolve((String)second.get("device")));restart.revoke(owner,device);assertNull(restart.resolve(device));assertTrue(restart.knownDevice(device));assertFalse(Json.write(store.load("player-identities")).contains(recovery));}}
 @Test void unknownOutstandingUsagePreventsMigration(){try(FileWorldStore store=new FileWorldStore(dir)){String id=UUID.randomUUID().toString();store.save("evaluation:old",Json.object("batchesJson",Json.write(List.of(Json.object("cases",List.of(Json.object("id",id))))),"purgeJson","[]"));store.save("evaluation:old:"+id+":usage",Json.object("issued",1,"calls",List.of()));PlayerIdentity ids=new PlayerIdentity(store,Set.of(PlayerIdentity.hash("invite-test")));assertThrows(IllegalStateException.class,()->ids.redeem("old","invite-test"));}}
 @Test void copyFailureDoesNotConsumeInviteOrActivateIdentity(){try(FileWorldStore disk=new FileWorldStore(dir)){disk.save("growth:old",Json.object("hello","world"));boolean[] fail={true};WorldStore store=new WorldStore(){public Map<String,Object> load(String key){return disk.load(key);}public void save(String key,Map<String,Object> value){if(fail[0]&&key.startsWith("growth:")&&!key.equals("growth:old"))throw new IllegalStateException("synthetic failure");disk.save(key,value);}public void close(){}};PlayerIdentity ids=new PlayerIdentity(store,Set.of(PlayerIdentity.hash("invite-test")));assertThrows(IllegalStateException.class,()->ids.redeem("old","invite-test"));assertNull(disk.load("player-identities"));assertEquals("world",disk.load("growth:old").get("hello"));fail[0]=false;Map<String,Object> registered=ids.redeem("old","invite-test");assertEquals(registered.get("owner"),ids.resolve((String)registered.get("device")));}}
 @Test void redemptionResponseLossCanReplaySameCredentialsAfterRestart(){try(FileWorldStore store=new FileWorldStore(dir)){String request=UUID.randomUUID().toString(),device=UUID.randomUUID().toString(),secret="a".repeat(64);store.save("growth:old",Json.object("hello","world"));PlayerIdentity ids=new PlayerIdentity(store,Set.of(PlayerIdentity.hash("invite-test")));Map<String,Object> first=retryRedeem(ids,"old",request,device,secret);PlayerIdentity restarted=new PlayerIdentity(store,Set.of(PlayerIdentity.hash("invite-test")));Map<String,Object> replay=retryRedeem(restarted,"old",request,device,secret);assertEquals(first,replay);assertEquals(first.get("owner"),restarted.resolve(device));assertEquals(1,Json.asArray(store.load("player-identities").get("players")).size());assertThrows(IllegalArgumentException.class,()->retryRedeem(restarted,"other",request,device,"d".repeat(64)));assertThrows(IllegalArgumentException.class,()->retryRedeem(restarted,"old",request,UUID.randomUUID().toString(),secret));assertFalse(Json.write(store.load("player-identities")).contains(secret));}}
 @SuppressWarnings("unchecked") Map<String,Object> retryRedeem(PlayerIdentity ids,String old,String request,String device,String secret){try{return(Map<String,Object>)PlayerIdentity.class.getMethod("redeem",String.class,String.class,String.class,String.class,String.class).invoke(ids,old,"invite-test",request,device,secret);}catch(java.lang.reflect.InvocationTargetException e){throw(RuntimeException)e.getCause();}catch(ReflectiveOperationException e){throw new IllegalStateException(e);}}
 @Test void unknownCommittedRegistrationIsReconciledBeforeRetry(){try(FileWorldStore disk=new FileWorldStore(dir)){boolean[] once={true};WorldStore store=new WorldStore(){public Map<String,Object> load(String key){return disk.load(key);}public void save(String key,Map<String,Object> value){disk.save(key,value);if(key.equals("player-identities")&&once[0]){once[0]=false;throw new IllegalStateException("unknown commit");}}public void close(){}};PlayerIdentity ids=new PlayerIdentity(store,Set.of(PlayerIdentity.hash("invite-test")));String request=UUID.randomUUID().toString(),device=UUID.randomUUID().toString(),secret="c".repeat(64);assertThrows(IllegalStateException.class,()->retryRedeem(ids,"old",request,device,secret));String committed=(String)Json.asObject(Json.asArray(disk.load("player-identities").get("players")).get(0)).get("owner");assertEquals(committed,retryRedeem(ids,"old",request,device,secret).get("owner"));}}
}