package game.agent;
import game.agent.web.*;import game.agent.persistence.*;import game.agent.llm.Json;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.net.*;import java.net.http.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class PlayerIdentityHttpTest {
 @TempDir Path dir;
 HttpClient http=HttpClient.newHttpClient();String site,cookie,csrf;
 HttpResponse<String> request(String path,Map<String,Object> body,String useCookie)throws Exception{HttpRequest.Builder r=HttpRequest.newBuilder(URI.create(site+path));if(useCookie!=null)r.header("Cookie",useCookie);if(body!=null)r.header("Origin",site).header("X-CSRF-Token",csrf).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(Json.write(body)));return http.send(r.build(),HttpResponse.BodyHandlers.ofString());}
 void connect()throws Exception{HttpResponse<String> response=request("/api/player/session",null,null);cookie=response.headers().firstValue("Set-Cookie").orElseThrow().split(";",2)[0];csrf=(String)Json.asObject(Json.read(response.body())).get("csrfToken");}
 @Test void publicOwnerIdentifierIsNotAnAuthenticationCredential()throws Exception{try(AgentWebServer server=new AgentWebServer(0,ProviderSelection.fromEnvironment(Map.of("LLM_PROVIDER","disabled")),Path.of("client/agent"),true,new FileWorldStore(dir),false,Map.of("PLAYER_IDENTITY_ENABLED","true","PLAYER_INVITE_HASHES",PlayerIdentity.hash("invite-test")))){server.start();site="http://127.0.0.1:"+server.getPort();connect();HttpResponse<String> registered=request("/api/player/redeem",registration(),cookie);assertEquals(200,registered.statusCode(),registered.body());String owner=(String)Json.asObject(Json.read(registered.body())).get("owner");String forged=cookie.split("=",2)[0]+"="+owner;HttpResponse<String> auth=request("/api/player/session",null,forged);assertEquals(false,Json.asObject(Json.read(auth.body())).get("identified"));connect();assertNotNull(csrf);}}
 @Test void twoDevicesShareAuthoritativeRoomAndRevocationOnlyRemovesOneDevice()throws Exception{try(AgentWebServer server=new AgentWebServer(0,ProviderSelection.fromEnvironment(Map.of("LLM_PROVIDER","disabled")),Path.of("client/agent"),true,new FileWorldStore(dir),false,Map.of("PLAYER_IDENTITY_ENABLED","true","PLAYER_INVITE_HASHES",PlayerIdentity.hash("invite-test")))){
  server.start();site="http://127.0.0.1:"+server.getPort();connect();
  HttpResponse<String> registered=request("/api/player/redeem",registration(),cookie);assertEquals(200,registered.statusCode());
  String first=registered.headers().firstValue("Set-Cookie").orElseThrow().split(";",2)[0],recovery=(String)Json.asObject(Json.read(registered.body())).get("recovery");
  csrf=(String)Json.asObject(Json.read(request("/api/player/session",null,first).body())).get("csrfToken");
  Map<String,Object> firstRoom=Json.asObject(Json.read(request("/api/growth/rooms",Map.of(),first).body()));
  connect();String anonymous=cookie;assertEquals(200,request("/api/player/preview",Json.object("recovery",recovery),anonymous).statusCode());
  HttpResponse<String> restored=request("/api/player/restore",Json.object("recovery",recovery,"useCloud",true),anonymous);assertEquals(200,restored.statusCode());String second=restored.headers().firstValue("Set-Cookie").orElseThrow().split(";",2)[0];
  csrf=(String)Json.asObject(Json.read(request("/api/player/session",null,second).body())).get("csrfToken");Map<String,Object> secondRoom=Json.asObject(Json.read(request("/api/growth/rooms",Map.of(),second).body()));assertEquals(firstRoom.get("roomId"),secondRoom.get("roomId"));assertNotNull(firstRoom.get("roomId"));
  assertEquals(200,request("/api/player/revoke",Map.of(),second).statusCode());assertEquals(false,Json.asObject(Json.read(request("/api/player/session",null,second).body())).get("identified"));assertEquals(true,Json.asObject(Json.read(request("/api/player/session",null,first).body())).get("identified"));
 }}
 Map<String,Object> registration(){return Json.object("invite","invite-test","confirm",true,"requestId",UUID.randomUUID().toString(),"device",UUID.randomUUID().toString(),"recovery","b".repeat(64));}
 @Test void lostResponseReplayUsingOldCookieReturnsSameIdentity()throws Exception{try(AgentWebServer server=new AgentWebServer(0,ProviderSelection.fromEnvironment(Map.of("LLM_PROVIDER","disabled")),Path.of("client/agent"),true,new FileWorldStore(dir),false,Map.of("PLAYER_IDENTITY_ENABLED","true","PLAYER_INVITE_HASHES",PlayerIdentity.hash("invite-test")))){server.start();site="http://127.0.0.1:"+server.getPort();connect();String old=cookie;Map<String,Object> body=registration();HttpResponse<String> first=request("/api/player/redeem",body,old);assertEquals(200,first.statusCode());String owner=(String)Json.asObject(Json.read(first.body())).get("owner");HttpResponse<String> refreshed=request("/api/player/session",null,old);csrf=(String)Json.asObject(Json.read(refreshed.body())).get("csrfToken");String retryCookie=refreshed.headers().firstValue("Set-Cookie").map(v->v.split(";",2)[0]).orElse(old);HttpResponse<String> retry=request("/api/player/redeem",body,retryCookie);assertEquals(200,retry.statusCode(),retry.body());assertEquals(owner,Json.asObject(Json.read(retry.body())).get("owner"));assertEquals(first.headers().firstValue("Set-Cookie"),retry.headers().firstValue("Set-Cookie"));}}
}