package game.agent;
import game.agent.web.*;import game.agent.llm.*;import game.agent.tools.*;import game.agent.persistence.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class SequenceAgentTest {
 static TaskIntent plan(String quest,Set<TaskIntent.Constraint> cs,String area,Long deadline){return TaskIntent.ofSequence(quest,Arrays.asList(Json.object("kind","CAPTURE","targetId","field-treecko"),Json.object("kind","DEFEAT","targetId","field-torchic")),cs,area,deadline);}
 static LlmGateway gateway(){return c->{String target=c.getObservation().get("goalTarget"),kind=c.getObservation().get("goalType");return new ToolRequest(UUID.randomUUID().toString(),"true".equals(c.getObservation().get("targetAdjacent"))?("CAPTURE".equals(kind)?"capture":"attack"):"move_to",Json.object("targetId",target));};}
 static ProviderSelection provider(){return new ProviderSelection("test","offline",1000,gateway(),(text,quest)->plan(quest,EnumSet.of(TaskIntent.Constraint.NO_SPENDING),null,null));}
 @Test void sequenceRejectsDuplicateTargetsUnsupportedStepsAndGlobalConflict(){
  assertThrows(IllegalArgumentException.class,()->plan("q",EnumSet.of(TaskIntent.Constraint.NO_ACTIVE_BATTLE),null,null));
  for(List<Map<String,Object>> steps:Arrays.asList(Arrays.asList(Json.object("kind","CAPTURE","targetId","field-treecko")),Arrays.asList(Json.object("kind","CAPTURE","targetId","field-treecko"),Json.object("kind","DEFEAT","targetId","field-treecko")),Arrays.asList(Json.object("kind","CAPTURE","targetId","field-torchic"),Json.object("kind","DEFEAT","targetId","field-mudkip"))))assertThrows(IllegalArgumentException.class,()->TaskIntent.ofSequence("q",steps,EnumSet.noneOf(TaskIntent.Constraint.class),null,null));
 }
 @Test void orderedNativeActionsFinishBothGoalsWithoutPrematureCompletion(){AgentRoom room=new AgentRoom("sequence",provider(),Runnable::run,true,null);FieldAgentTest.start(room);boolean first=false;for(int i=3;i<150&&!"COMPLETED".equals(room.snapshot().get("status"));i++){room.tick(i);if("CAPTURED".equals(FieldAgentTest.target(room,"field-treecko").get("state"))&&!"DEFEATED".equals(FieldAgentTest.target(room,"field-torchic").get("state"))){first=true;assertNotEquals("COMPLETED",room.snapshot().get("status"));assertEquals("field-torchic",room.snapshot().get("targetId"));}}assertTrue(first);assertEquals("COMPLETED",room.snapshot().get("status"));assertEquals("CAPTURED",FieldAgentTest.target(room,"field-treecko").get("state"));assertEquals("DEFEATED",FieldAgentTest.target(room,"field-torchic").get("state"));assertEquals("5",Json.asObject(room.snapshot().get("world")).get("coins"));assertEquals(2,Json.asArray(room.snapshot().get("goalSteps")).size());}
 @Test void futureStageTargetAndOperationAreRejected(){game.agent.demo.GeminiQuestScenario scene=new game.agent.demo.GeminiQuestScenario("ordered",true);game.agent.runtime.AgentLoop loop=scene.start(plan(scene.getSession().getQuestId(),EnumSet.noneOf(TaskIntent.Constraint.class),null,null),c->new ToolRequest("out","attack",Json.object("targetId","field-torchic")),Runnable::run);loop.tick(1);assertEquals("TARGET_NOT_IN_TASK",loop.tick(2).getCode());assertEquals(0,scene.getSession().getTurn());}
 @Test void fileRestoreResumesSecondStageAndRetainsCompletedFirstStage(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);AgentRoom room=new AgentRoom("resume-sequence",provider(),Runnable::run,true,store);FieldAgentTest.start(room);for(int i=3;i<35&&!"CAPTURED".equals(FieldAgentTest.target(room,"field-treecko").get("state"));i++)room.tick(i);assertEquals("CAPTURED",FieldAgentTest.target(room,"field-treecko").get("state"));room.command(AgentRoomTest.command(room,"PAUSE",Collections.emptyMap()),40);room.close();AgentRoom restored=new AgentRoom("resume-sequence",provider(),Runnable::run,true,store);assertEquals("PAUSED",restored.snapshot().get("status"));assertEquals("SEQUENCE",restored.snapshot().get("taskKind"));assertEquals("field-torchic",restored.snapshot().get("targetId"));restored.command(AgentRoomTest.command(restored,"RESUME",Collections.emptyMap()),41);for(int i=42;i<180&&!"COMPLETED".equals(restored.snapshot().get("status"));i++)restored.tick(i);assertEquals("COMPLETED",restored.snapshot().get("status"));restored.close();assertEquals("COMPLETED",new AgentRoom("resume-sequence",provider(),Runnable::run,true,store).snapshot().get("status"));}
 @Test void schemaDecodesSequenceAndRetainsLegacySingleGoal(){String body=OpenAiGatewayTest.text(Json.write(Json.object("status","SUPPORTED","goal","SEQUENCE","questId","quest","targetId",null,"steps",Arrays.asList(Json.object("kind","CAPTURE","targetId","field-treecko"),Json.object("kind","DEFEAT","targetId","field-torchic")),"constraints",Collections.emptyList(),"areaId",null,"deadlineTurn",null,"unsupportedClauses",Collections.emptyList())));TaskIntent t=OpenAiGatewayTest.gateway((m,k,b,time)->new JsonTransport.Response(200,body)).parse("先捕捉木守宫再击败火稚鸡","quest");assertEquals("SEQUENCE",t.getKind());assertEquals(2,t.getSteps().size());assertEquals("CAPTURE",t.getSteps().get(0).getKind());}

 @Test void confirmationChecksEveryStageAreaBeforeSpawning(){ProviderSelection p=new ProviderSelection("test","offline",1000,c->new ToolRequest("obs","observe",Collections.emptyMap()),(text,q)->plan(q,EnumSet.of(TaskIntent.Constraint.AREA_RESTRICTED),"ORCHARD_AREA",null));AgentRoom room=new AgentRoom("sequence-area",p,Runnable::run,true,null);FieldAgentTest.parse(room);assertEquals("AREA_RESTRICTED",room.command(AgentRoomTest.command(room,"CONFIRM",Collections.emptyMap()),2).body.get("reasonCode"));assertTrue(Json.asArray(room.snapshot().get("wild")).isEmpty());}
 @Test void pausedManualControlCannotSkipOrChangeCurrentStageOperation(){AgentRoom room=new AgentRoom("manual-sequence",provider(),Runnable::run,true,null);FieldAgentTest.start(room);room.command(AgentRoomTest.command(room,"PAUSE",Collections.emptyMap()),3);assertEquals("TARGET_NOT_IN_TASK",room.command(AgentRoomTest.command(room,"WILD_ACTION",Json.object("action","attack","arguments",Json.object("targetId","field-torchic"))),4).body.get("reasonCode"));assertEquals("STAGE_OPERATION_NOT_ALLOWED",room.command(AgentRoomTest.command(room,"WILD_ACTION",Json.object("action","attack","arguments",Json.object("targetId","field-treecko"))),5).body.get("reasonCode"));assertEquals("0",Json.asObject(room.snapshot().get("world")).get("turn"));}
 @Test void deadlineAfterFirstStageDoesNotReportOverallSuccess(){ProviderSelection p=new ProviderSelection("test","offline",1000,gateway(),(text,q)->plan(q,EnumSet.of(TaskIntent.Constraint.DEADLINE),null,3L));AgentRoom room=new AgentRoom("sequence-deadline",p,Runnable::run,true,null);FieldAgentTest.start(room);for(int i=3;i<40&&!"FAILED".equals(room.snapshot().get("status"));i++)room.tick(i);assertEquals("FAILED",room.snapshot().get("status"));assertEquals("CAPTURED",FieldAgentTest.target(room,"field-treecko").get("state"));assertEquals("WILD",FieldAgentTest.target(room,"field-torchic").get("state"));}
 @Test void readySequenceRestoresWithoutSpawning(@TempDir Path dir){WorldStore store=new FileWorldStore(dir);AgentRoom room=new AgentRoom("sequence-ready",provider(),Runnable::run,true,store);FieldAgentTest.parse(room);room.close();AgentRoom restored=new AgentRoom("sequence-ready",provider(),Runnable::run,true,store);assertEquals("READY",restored.snapshot().get("status"));assertEquals(2,Json.asArray(restored.snapshot().get("goalSteps")).size());assertTrue(Json.asArray(restored.snapshot().get("wild")).isEmpty());}
 @Test void threeDistinctGoalsFinishInOrder(){ProviderSelection p=new ProviderSelection("test","offline",1000,gateway(),(text,q)->TaskIntent.ofSequence(q,Arrays.asList(Json.object("kind","CAPTURE","targetId","field-treecko"),Json.object("kind","CAPTURE","targetId","field-mudkip"),Json.object("kind","DEFEAT","targetId","field-torchic")),EnumSet.noneOf(TaskIntent.Constraint.class),null,null));AgentRoom room=new AgentRoom("three-sequence",p,Runnable::run,true,null);FieldAgentTest.start(room);for(int i=3;i<180&&!"COMPLETED".equals(room.snapshot().get("status"));i++)room.tick(i);assertEquals("COMPLETED",room.snapshot().get("status"));assertEquals("CAPTURED",FieldAgentTest.target(room,"field-mudkip").get("state"));}
 @Test void postgresSequenceRestoresCurrentStageAndCompletedResult()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");String owner="sequence-pg-"+UUID.randomUUID();try(WorldStore store=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){AgentRoom room=new AgentRoom(owner,provider(),Runnable::run,true,store);FieldAgentTest.start(room);for(int i=3;i<35&&!"CAPTURED".equals(FieldAgentTest.target(room,"field-treecko").get("state"));i++)room.tick(i);room.command(AgentRoomTest.command(room,"PAUSE",Collections.emptyMap()),40);room.close();AgentRoom restored=new AgentRoom(owner,provider(),Runnable::run,true,store);assertEquals("field-torchic",restored.snapshot().get("targetId"));restored.command(AgentRoomTest.command(restored,"RESUME",Collections.emptyMap()),41);for(int i=42;i<180&&!"COMPLETED".equals(restored.snapshot().get("status"));i++)restored.tick(i);assertEquals("COMPLETED",restored.snapshot().get("status"));restored.close();assertEquals("COMPLETED",new AgentRoom(owner,provider(),Runnable::run,true,store).snapshot().get("status"));}}
}
