package game.agent;
import game.agent.multi.*;import game.agent.multi.MultiAgentFoundation.Role;import game.agent.llm.*;import game.agent.runtime.AgentLoop;import game.agent.tools.*;import game.agent.action.*;import game.agent.persistence.*;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.Path;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class V3CognitionTest {
 static ToolRequest plan(AgentLoop.Context c,String next){Map<String,Object> k=Json.asObject(Json.read(c.getObservation().get("knowledge")));List<Object> rows=Json.asArray(k.get("observations"));return new ToolRequest("model","reflect_plan",args((String)Json.asObject(rows.get(rows.size()-1)).get("id"),next));}
 static Map<String,Object> args(String evidence,String next){return Json.object("evidenceId",evidence,"reflection","依据自身观察安排协作，不把历史消息当作即时事实","morning","观察并共享本角色信息","afternoon","核查变化并协助伙伴","evening","汇总历史并避免过期信息","nextAction",next);}
 Map<String,String> obs(int quantity,int turn){Map<String,String> o=new LinkedHashMap<>();o.put("turn",""+turn);o.put("facts",Json.write(Arrays.asList(Json.object("id","berry","subject","BERRY","x",31,"y",10,"quantity",quantity))));return o;}
 String evidence(NpcKnowledge k,Role r){return(String)Json.asObject(Json.asArray(k.view(r).get("observations")).get(0)).get("id");}
 @Test void planRequiresOwnEvidenceAndCannotAuthorizeMerchantMovement(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,obs(2,0));k.observe(Role.MERCHANT,obs(2,0));NpcCognition c=new NpcCognition();assertThrows(IllegalArgumentException.class,()->c.accept(Role.MERCHANT,args(evidence(k,Role.TORCHIC),"SEND_FACT"),"s",0,k));assertThrows(IllegalArgumentException.class,()->c.accept(Role.MERCHANT,args(evidence(k,Role.MERCHANT),"MOVE"),"s",0,k));assertTrue(c.needsPlan(Role.MERCHANT,"s",0));}
 @Test void changesPhasesAndNewDaysRequireReplanning(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,obs(2,0));NpcCognition c=new NpcCognition();c.accept(Role.TORCHIC,args(evidence(k,Role.TORCHIC),"SEND_FACT"),"s",0,k);assertFalse(c.needsPlan(Role.TORCHIC,"s",19));assertTrue(c.needsPlan(Role.TORCHIC,"s",20));assertTrue(c.needsPlan(Role.TORCHIC,"changed",1));assertTrue(c.needsPlan(Role.TORCHIC,"s",60));assertEquals(false,Json.asObject(c.view(Role.TORCHIC,0).get("reflection")).get("liveFact"));}
 @Test void compressedHistoryRetainsSourceAndCanRetrieveOldResource(){NpcKnowledge k=new NpcKnowledge();for(int i=0;i<20;i++){Map<String,String> o=obs(i,i);o.put("facts",Json.write(Arrays.asList(Json.object("id","resource"+i,"subject",i==0?"OLD_RESOURCE":"NEW","x",i,"y",1))));k.observe(Role.TORCHIC,o);}List<Map<String,Object>> rows=k.recall(Role.TORCHIC,"OLD_RESOURCE",3);assertEquals(1,rows.size());assertTrue(k.ownsEvidence(Role.TORCHIC,(String)rows.get(0).get("id")));assertEquals(4,Json.asArray(k.view(Role.TORCHIC).get("longTerm")).size());assertTrue(Json.asArray(k.view(Role.MERCHANT).get("longTerm")).isEmpty());assertEquals("SELF_OBSERVATION",rows.get(0).get("source"));assertEquals(0L,((Number)rows.get(0).get("lastTurn")).longValue());assertTrue(k.recall(Role.MERCHANT,"OLD_RESOURCE",3).isEmpty());assertEquals(k.checkpoint(),NpcKnowledge.restore(k.checkpoint()).checkpoint());}
 @Test void relayPreservesContentOriginAndExpiryAcrossRestore(){MultiAgentFoundation f=new MultiAgentFoundation("w",4);f.send("a",Role.TORCHIC,Role.PROFESSOR,"BERRY","true observed fact","QUEST_AREA",31,10,0,1,8);assertTrue(f.relay("b",Role.PROFESSOR,Role.MUDKIP,"a",2));Map<String,Object> row=f.inbox(Role.MUDKIP,2).get(0);assertEquals(Arrays.asList("torchic","professor","mudkip"),row.get("route"));assertEquals("a",row.get("rootMessageId"));assertEquals(8L,((Number)row.get("expiresTurn")).longValue());assertEquals("true observed fact",row.get("content"));assertEquals(f.checkpoint(),MultiAgentFoundation.restore(f.checkpoint()).checkpoint());assertTrue(f.inbox(Role.MUDKIP,9).get(0).get("expired").equals(true));}
 @Test void relayRejectsUnreceivedExpiredAndLoopedMessages(){MultiAgentFoundation f=new MultiAgentFoundation("w",4);f.send("a",Role.TORCHIC,Role.PROFESSOR,"BERRY","fact","QUEST_AREA",1,1,0,0,3);assertThrows(IllegalArgumentException.class,()->f.relay("b",Role.MERCHANT,Role.MUDKIP,"a",1));assertThrows(IllegalArgumentException.class,()->f.relay("b",Role.PROFESSOR,Role.MUDKIP,"a",4));assertThrows(IllegalArgumentException.class,()->f.relay("b",Role.PROFESSOR,Role.TORCHIC,"a",1));f.relay("b",Role.PROFESSOR,Role.MUDKIP,"a",1);assertFalse(f.relay("c",Role.PROFESSOR,Role.MUDKIP,"a",2));}
 @Test void forgedRelayCheckpointIsRejected(){MultiAgentFoundation f=new MultiAgentFoundation("w",4);f.send("a",Role.TORCHIC,Role.PROFESSOR,"BERRY","fact","QUEST_AREA",1,1,0,0,3);f.relay("b",Role.PROFESSOR,Role.MUDKIP,"a",1);Map<String,Object> saved=f.checkpoint();Json.asObject(Json.asArray(saved.get("messages")).get(1)).put("content","forged");assertThrows(IllegalArgumentException.class,()->MultiAgentFoundation.restore(saved));}
 @Test void modelPlansThenActsAndQuiescenceDoesNotDrainBudget(){int[] calls={0};NpcAgentRuntime r=new NpcAgentRuntime("w",c->{calls[0]++;return c.getTools().get(0).getName().equals("reflect_plan")?plan(c,"SEND_FACT"):new ToolRequest("a","send_message",Json.object("recipient","mudkip","factId","berry"));},Runnable::run,100,role->obs(2,0),(role,t)->ActionResult.success("OBSERVED"),true);for(int i=0;i<20;i++)r.tick(i,0,0);assertEquals(6,calls[0]);assertEquals(3,r.inbox(Role.MUDKIP,0).size());Map<String,Object> checkpoint=r.checkpoint();for(int i=0;i<100;i++)assertFalse(r.tick(i,0,0));assertEquals(checkpoint,r.checkpoint());}
 @Test void modelReflectionCannotSkipEvidenceValidation(){NpcAgentRuntime r=new NpcAgentRuntime("w",c->new ToolRequest("a","reflect_plan",args("forged","SEND_FACT")),Runnable::run,100,role->obs(2,0),(role,t)->ActionResult.success("OBSERVED"),true);r.tick(0,0,0);r.tick(1,0,0);assertTrue(Json.asObject(r.checkpoint().get("cognitionState")).isEmpty());assertTrue(r.inbox(Role.MUDKIP,0).isEmpty());}
 @Test void checkpointRestoresModelClaimsAndPausesWork(@TempDir Path dir){NpcAgentRuntime r=new NpcAgentRuntime("w",c->c.getTools().get(0).getName().equals("reflect_plan")?plan(c,"SEND_FACT"):new ToolRequest("a","send_message",Json.object("recipient","mudkip","factId","berry")),Runnable::run,100,role->obs(2,0),(role,t)->ActionResult.success("OBSERVED"),true);for(int i=0;i<15;i++)r.tick(i,0,0);Map<String,Object> saved=r.checkpoint();try(WorldStore store=new FileWorldStore(dir)){store.save("v3",saved);NpcAgentRuntime restored=new NpcAgentRuntime("w",c->{throw new AssertionError("no replay");},Runnable::run,100,role->obs(2,0),(role,t)->ActionResult.success("OBSERVED"),true);restored.restore(store.load("v3"),"w");assertEquals(saved.get("knowledge"),restored.checkpoint().get("knowledge"));assertEquals(saved.get("cognitionState"),restored.checkpoint().get("cognitionState"));assertFalse(restored.tick(20,0,0));}}
 @Test void modelOutputTooLongAndCorruptRestoreRejected(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,obs(2,0));NpcCognition c=new NpcCognition();Map<String,Object> a=args(evidence(k,Role.TORCHIC),"OBSERVE");a.put("reflection",String.join("",Collections.nCopies(601,"a")));assertThrows(IllegalArgumentException.class,()->c.accept(Role.TORCHIC,a,"s",0,k));c.accept(Role.TORCHIC,args(evidence(k,Role.TORCHIC),"OBSERVE"),"s",0,k);Map<String,Object> saved=c.checkpoint();Json.asObject(saved.get("torchic")).put("period","EVENING");assertThrows(IllegalArgumentException.class,()->NpcCognition.restore(saved,k));}
 @Test void runtimeReplansOnChangedFactsAndDayPhase(){int[] turn={0},quantity={2},calls={0};NpcAgentRuntime r=new NpcAgentRuntime("w",c->{if(c.getTools().get(0).getName().equals("reflect_plan")){calls[0]++;return plan(c,"SEND_FACT");}return new ToolRequest("a","send_message",Json.object("recipient","mudkip","factId","berry"));},Runnable::run,100,role->obs(quantity[0],turn[0]),(role,t)->ActionResult.success("OBSERVED"),true);for(int i=0;i<20;i++)r.tick(i,turn[0],0);assertEquals(3,calls[0]);quantity[0]=1;turn[0]=1;for(int i=0;i<20;i++)r.tick(i,turn[0],0);assertEquals(6,calls[0]);turn[0]=20;for(int i=0;i<20;i++)r.tick(i,turn[0],0);assertEquals(9,calls[0]);}
 @Test void plannedActionCannotBeReplacedByUnplannedMessage(){NpcAgentRuntime r=new NpcAgentRuntime("w",c->c.getTools().get(0).getName().equals("reflect_plan")?plan(c,"SEND_FACT"):new ToolRequest("a","observe",Collections.emptyMap()),Runnable::run,100,role->obs(2,0),(role,t)->ActionResult.success("OBSERVED"),true);for(int i=0;i<12;i++)r.tick(i,0,0);assertTrue(r.inbox(Role.MUDKIP,0).isEmpty());assertTrue(Json.write(r.view(0).get("trace")).contains("INVALID_ARGUMENTS"));}
 @Test void compressedArchiveHasFiniteCapacity(){NpcKnowledge k=new NpcKnowledge();for(int i=0;i<80;i++){Map<String,String> o=obs(i,i);o.put("facts",Json.write(Arrays.asList(Json.object("id","r"+i,"subject","BERRY"))));k.observe(Role.TORCHIC,o);}assertEquals(32,Json.asArray(Json.asObject(k.checkpoint().get("_archive")).get("torchic")).size());}
 @Test void postgresPersistsModelsArchiveAndRelayTogether()throws Exception{String url=System.getProperty("pokemon.test.jdbcUrl");org.junit.jupiter.api.Assumptions.assumeTrue(url!=null);Class.forName("org.postgresql.Driver");NpcKnowledge k=new NpcKnowledge();for(int i=0;i<20;i++)k.observe(Role.TORCHIC,obs(i,i));NpcCognition c=new NpcCognition();List<Object> rows=Json.asArray(k.view(Role.TORCHIC).get("observations"));c.accept(Role.TORCHIC,args((String)Json.asObject(rows.get(rows.size()-1)).get("id"),"SEND_FACT"),"s",19,k);MultiAgentFoundation f=new MultiAgentFoundation("w",32);f.send("a",Role.TORCHIC,Role.PROFESSOR,"BERRY","observed","QUEST_AREA",31,10,19,19,29);f.relay("b",Role.PROFESSOR,Role.MUDKIP,"a",20);String owner="v3-cognition-"+UUID.randomUUID();try(WorldStore store=new JdbcWorldStore(()->java.sql.DriverManager.getConnection(url,System.getProperty("pokemon.test.jdbcUser","pokemon_v1"),""))){store.save(owner,Json.object("memory",k.checkpoint(),"model",c.checkpoint(),"world",f.checkpoint()));Map<String,Object> loaded=store.load(owner);NpcKnowledge m=NpcKnowledge.restore(Json.asObject(loaded.get("memory")));assertEquals(k.checkpoint(),m.checkpoint());assertEquals(c.checkpoint(),NpcCognition.restore(Json.asObject(loaded.get("model")),m).checkpoint());assertEquals(f.checkpoint(),MultiAgentFoundation.restore(Json.asObject(loaded.get("world"))).checkpoint());}}
}
