package game.agent;
import game.agent.multi.*;import game.agent.multi.MultiAgentFoundation.Role;import game.agent.llm.*;import game.agent.tools.*;import game.agent.action.*;import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class V3FinalBoundaryTest {
 Map<String,String> observation(int n,int turn){Map<String,String> o=new LinkedHashMap<>();o.put("turn",""+turn);o.put("facts",Json.write(Arrays.asList(Json.object("id","berry","subject","BERRY","x",31,"y",10,"quantity",n))));return o;}
 @Test void idleRolesKeepTheirBudgetWhileAnotherRoleRetries(){Map<String,Integer> calls=new HashMap<>();NpcAgentRuntime r=new NpcAgentRuntime("w",c->{String role=c.getObservation().getOrDefault("agentId","unknown");calls.put(role,calls.getOrDefault(role,0)+1);if("torchic".equals(role))throw new ProviderException(ProviderException.Code.UNAVAILABLE);return c.getTools().get(0).getName().equals("reflect_plan")?V3CognitionTest.plan(c,"SEND_FACT"):new ToolRequest("decision","send_message",Json.object("recipient","mudkip","factId","berry"));},Runnable::run,100,role->{Map<String,String> o=observation(2,0);o.put("agentId",MultiAgentFoundation.agentId(role));return o;},(role,t)->ActionResult.success("OBSERVED"),true);for(int i=0;i<100;i++)r.tick(i,0,0);assertEquals(32,calls.get("torchic"));assertEquals(2,calls.get("professor"));assertEquals(2,calls.get("merchant"));assertEquals("RUNNING",r.view(0).get("status"));List<Object> agents=Json.asArray(Json.asObject(r.checkpoint().get("foundation")).get("agents"));assertEquals(0,((Number)Json.asObject(agents.get(0)).get("used")).intValue());assertEquals(2,((Number)Json.asObject(agents.get(2)).get("used")).intValue());}
 @Test void eligibleSchedulerDoesNotDebitOthersAndRestoresCursor(){MultiAgentFoundation f=new MultiAgentFoundation("w",4);Map<String,Object> lease=f.next(0,0,EnumSet.of(Role.MERCHANT));assertEquals("merchant",lease.get("agentId"));f.finish((String)lease.get("leaseId"),"observe",0);assertEquals(4,f.remaining(Role.TORCHIC));assertEquals(3,MultiAgentFoundation.restore(f.checkpoint()).remaining(Role.MERCHANT));assertNull(f.next(0,0,EnumSet.noneOf(Role.class)));assertEquals(4,f.remaining(Role.PROFESSOR));}
 @Test void unchangedObservationRefreshesTimeWithoutDuplicatingEvidence(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,observation(2,0));String first=Json.write(k.view(Role.TORCHIC).get("observations"));assertFalse(k.observe(Role.TORCHIC,observation(2,20)));List<Object> rows=Json.asArray(k.view(Role.TORCHIC).get("observations"));assertEquals(1,rows.size());assertEquals(20L,((Number)Json.asObject(rows.get(0)).get("lastSeenTurn")).longValue());assertEquals(Json.asObject(Json.asArray(Json.read(first)).get(0)).get("id"),Json.asObject(rows.get(0)).get("id"));assertThrows(IllegalArgumentException.class,()->k.observe(Role.TORCHIC,observation(1,19)));assertEquals(k.checkpoint(),NpcKnowledge.restore(k.checkpoint()).checkpoint());}
 @Test void corruptLastSeenTimeCannotBypassRestoreChronology(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,observation(2,0));k.observe(Role.TORCHIC,observation(1,1));Map<String,Object> saved=k.checkpoint();Json.asObject(Json.asArray(saved.get("torchic")).get(0)).put("lastSeenTurn",2);assertThrows(IllegalArgumentException.class,()->NpcKnowledge.restore(saved));}
 @Test void oldCheckpointsWithoutLastSeenRemainReadable(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,observation(2,3));Map<String,Object> saved=k.checkpoint();Json.asObject(Json.asArray(saved.get("torchic")).get(0)).remove("lastSeenTurn");NpcKnowledge restored=NpcKnowledge.restore(saved);assertFalse(restored.observe(Role.TORCHIC,observation(2,4)));assertThrows(IllegalArgumentException.class,()->restored.observe(Role.TORCHIC,observation(1,3)));}
 @Test void compactionRetainsMostRecentConfirmedTime(){NpcKnowledge k=new NpcKnowledge();k.observe(Role.TORCHIC,observation(2,0));k.observe(Role.TORCHIC,observation(2,5));for(int i=1;i<=16;i++)k.observe(Role.TORCHIC,observation(2+i,5+i));Map<String,Object> archive=Json.asObject(Json.asArray(Json.asObject(k.checkpoint().get("_archive")).get("torchic")).get(0));assertEquals(5L,((Number)archive.get("lastTurn")).longValue());}
}
