import {battleWorkspace} from './player-frame.mjs';
import {battleEvents,createEffectQueue,animateElement} from './battle-effects.mjs';
import {reducedMotion} from './scene-motion.mjs';
import {AgentClient} from './client.mjs';
import {labels,results,art,hpPercent,hint,canRetryAction,recoverDuelConnection} from './duel-view.mjs';
const client=new AgentClient(undefined,undefined,'/api/duel'),$=id=>document.getElementById(id);let rookieId=/^#rookie-([a-f0-9-]{36})$/.exec(location.hash)?.[1],latest,busy=false,configured=false,lastTrace=0,polling=null;
function text(tag,value){const el=document.createElement(tag);el.textContent=value;return el;}
function card(el,p){if(!p){el.replaceChildren();return;}if(!el.querySelector('.hp')){el.replaceChildren(text('strong',''),text('p',''));const bar=text('div','');bar.className='hp';bar.append(text('span',''));el.append(bar);}
 el.querySelector('strong').textContent=`${p.name} · Lv.${p.level}`;el.querySelector('p').textContent=`HP ${p.hp} / ${p.maxHp} · ${({NONE:'状态良好',BURN:'灼伤',POISON:'中毒',PARALYSIS:'麻痹',SLEEP:'睡眠'})[p.burned?'BURN':p.status]??'状态良好'}`;el.querySelector('.hp span').style.width=`${hpPercent(p)}%`;}
const effects=createEffectQueue({play:async(event,signal)=>{
 if(document.hidden)return;const actor=$(event.side===0?'partner-art':'opponent-art'),target=$(event.side===0?'opponent-art':'partner-art');
 const messages={miss:'未命中',prevented:'异常状态阻止行动',skipped:'伙伴倒下，未行动',switch:'替补伙伴出场',residual:event.status==='BURN'?'灼伤伤害':'中毒伤害',faint:'伙伴倒下'};$('battle-feedback').textContent=messages[event.kind]??'';
 if(reducedMotion())return;
 if(['move','miss'].includes(event.kind))await animateElement(actor,[{translate:'0px'},{translate:(event.side===0?'12px':'-12px')},{translate:'0px'}],{duration:120,easing:'ease-out'},signal);
 if(event.damage>0)await animateElement(event.kind==='residual'?actor:target,[{filter:'brightness(1)'},{filter:'brightness(2)',translate:'3px'},{filter:'brightness(1)'}],{duration:110},signal);
 if(event.kind==='switch')await animateElement(actor,[{opacity:0,scale:.7},{opacity:1,scale:1}],{duration:180},signal);
 if(event.kind==='faint')await animateElement(actor,[{opacity:1},{opacity:.3,translate:'0px 12px'}],{duration:220},signal);
}});
let previousEffects=null,shownOutcome=null;document.addEventListener('visibilitychange',()=>{if(document.hidden)effects.clear();});window.addEventListener('pagehide',()=>effects.clear());

async function command(name,params={}){if(busy)return;busy=true;if(latest)render(latest);try{const before=client.view;for(let attempt=0;;attempt++){try{await client.command(name,params);break;}catch(error){if(name!=='ACTION'||error.message!=='STALE_REVISION'||attempt>=2)throw error;const fresh=await client.poll();if(!canRetryAction(before,fresh,params))throw error;}}$('notice').textContent='';await poll();}catch(e){$('notice').textContent=e.message==='INVALID_ROOKIE_CONFIGURATION'?'见习对战需要选择一位伙伴，使用玩家操作与规则基线。':`操作未完成：${e.code??e.message}。`;}finally{busy=false;if(latest)render(latest);}}
function render(v){if(previousEffects?.taskId!==v.taskId)effects.clear();effects.enqueue(battleEvents(previousEffects,v));previousEffects=v;latest=v;const workspace=battleWorkspace(v);$('battle-arena').hidden=!workspace.arena;$('battle-controls').hidden=!workspace.arena&&v.status!=='STORAGE_ERROR';$('battle-outcome').hidden=!workspace.outcome;document.body.classList.toggle('battle-finished',workspace.outcome);if(!workspace.outcome)document.body.classList.remove('adjust-battle');document.body.classList.toggle('connection-normal',client.connected&&!client.pendingRequest);if(workspace.outcome){$('outcome-title').textContent=(results[v.world.result]??labels[v.status]??v.status)+' · '+v.world.round+' 回合';}$('connection').textContent=client.connected?(v.storage==='PERSISTENT'?'已连接 · 自动存档':'已连接 · 内存模式'):'连接中断，请重新连接';$('reconnect').disabled=busy;$('retry-request').hidden=!client.pendingRequest;$('retry-request').disabled=busy;$('battle-status').textContent=v.status==='COMPLETED'?(results[v.world.result]??v.world.result):(labels[v.status]??v.status);$('hint').textContent=hint(v);
 if(!configured){for(const id of ['left-model','right-model'])for(const model of v.models){const o=text('option',model==='baseline'?'规则基线（不调用模型）':model);o.value=model;$(id).append(o);}for(const p of v.teamOptions){const label=text('label',''),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.value=p.captureId;checkbox.checked=rookieId===p.captureId;const portrait=document.createElement('img');portrait.src=art(p.species);portrait.alt=p.name;portrait.hidden=!p.species;checkbox.addEventListener('change',updateDifficulty);label.append(checkbox,portrait,text('span',`${p.name} Lv.${p.level}`));$('team-options').append(label);}configured=true;if(rookieId)$('difficulty').value='rookie';updateDifficulty();}
 const p=v.world.ownTeam?.[v.world.activeSlot],o=v.world.opponentActive;card($('partner'),p);card($('opponent'),o);for(const [id,pokemon] of [['partner-art',p],['opponent-art',o]]){$(id).hidden=!pokemon;if(pokemon)$(id).src=art(pokemon.species);}
 $('actions').replaceChildren();if(v.status==='RUNNING'&&v.controlMode==='manual'&&v.world.canChoose){for(const id of v.world.legalMoves){const move=p.moves.find(m=>m.id===id);const button=text('button',`${move?.name??id}${move?` · PP ${move.pp}`:''}`);button.disabled=busy||!client.connected||!!client.pendingRequest;button.onclick=()=>command('ACTION',{tool:'battle_move',arguments:{moveId:id}});$('actions').append(button);}for(const slot of v.world.legalSwitches){const reserve=v.world.ownTeam[slot],button=text('button',`换上 ${reserve.name} · HP ${reserve.hp}`);button.className='switch-action';button.disabled=busy||!client.connected||!!client.pendingRequest;button.onclick=()=>command('ACTION',{tool:'battle_switch',arguments:{slot}});$('actions').append(button);}}
 for(const [id,allowed] of [['start',v.status!=='RUNNING'&&v.status!=='STORAGE_ERROR'],['pause',v.status==='RUNNING'],['resume',v.status==='PAUSED'&&(!v.usageIncomplete||(v.leftModel==='baseline'&&v.rightModel==='baseline'))],['manual',v.status==='PAUSED'],['cancel',['RUNNING','PAUSED'].includes(v.status)],['recover',v.status==='STORAGE_ERROR'],['download',!!v.trace.length]])$(id).disabled=busy||!allowed||(id!=='download'&&(!client.connected||!!client.pendingRequest));
 $('battle-again').disabled=$('start').disabled;$('battle-adjust').disabled=busy;
 for(const id of ['pause','resume','manual','cancel','recover','download'])$(id).hidden=$(id).disabled;document.body.classList.toggle('in-battle',['RUNNING','PAUSED'].includes(v.status));const n=v.trace.length;$('replay').max=Math.max(0,n-1);if(n!==lastTrace){$('replay').value=Math.max(0,n-1);lastTrace=n;}replay();$('usage').textContent=`调用：${v.calls.join(' / ')} · Token：${v.tokens}${v.usageIncomplete?'（存在未返回用量的调用，非完整费用）':''}`;$('decisions').replaceChildren(...v.decisions.slice(-12).map(d=>text('p',`${d.side===0?'己方':'对手'} · ${d.model} · ${Math.round(d.latencyMs)} ms · ${d.outcome}`)));if(v.status==='STORAGE_ERROR')$('notice').textContent=`保存失败：${v.errorCode}。操作已冻结。`;if(workspace.outcome&&shownOutcome!==v.taskId){shownOutcome=v.taskId;requestAnimationFrame(()=>{if(latest.taskId===v.taskId&&battleWorkspace(latest).outcome)$('battle-outcome').scrollIntoView({block:'start',behavior:'instant'});});}}
function replay(){const row=latest?.trace[Number($('replay').value)];$('replay-detail').replaceChildren();if(!row)return;$('replay-detail').append(text('p',`第 ${row.round} 回合${row.replacement?' · 倒下后换人':''}`));for(const a of row.actions)$('replay-detail').append(text('p',`${a.side===0?'己方':'对手'}：${a.type==='RESIDUAL'?`${a.status==='BURN'?'灼伤':'中毒'} · 伤害 ${a.damage}`:a.type==='SWITCH'?`换上队伍第 ${a.slot+1} 位`:`${a.moveId} · 伤害 ${a.damage}${a.outcome==='STATUS_PREVENTED'?'（异常状态阻止行动）':a.eligible?'':'（倒下，未行动）'}`}`));}
// Polls serialize to avoid stale snapshots overwriting a command response.
async function poll(){if(polling)return polling;polling=(async()=>{try{render(await client.poll());}catch(e){if(latest)render(latest);$('connection').textContent=`连接中断：${e.message}，请重新连接。`;}})();try{return await polling;}finally{polling=null;}}
function previewOpponent(){const meta=latest?.opponentPreviews,selected=[...$('team-options').querySelectorAll('input:checked')];const roster=$('difficulty').value==='rookie'?(selected.length===1&&meta?.rookieByPartner?.[selected[0].value]?[meta.rookieByPartner[selected[0].value]]:[]):meta?.standard??[];const host=$('battle-preview-roster');host.replaceChildren();for(const p of roster){const card=text('div',''),img=document.createElement('img');img.src=art(p.species);img.alt=p.name;card.append(img,text('span',p.name+' · Lv.'+p.level));host.append(card);}if(!roster.length)host.textContent=$('difficulty').value==='rookie'?'选择一位伙伴，查看对手等级。':'对手信息将在开始后显示。';}
function updateDifficulty(){if(/^(最多选择|见习对战请选择|见习对战需要选择)/.test($('notice').textContent))$('notice').textContent='';previewOpponent();$('battle-preview-label').textContent=$('difficulty').value==='rookie'?'见习训练师 · 单伙伴挑战':'标准训练师 · 队伍挑战';const rookie=$('difficulty').value==='rookie';document.body.classList.toggle('rookie',rookie);$('battle-advanced').hidden=rookie;$('setup-description').textContent=rookie?'选一位伙伴挑战低等级见习训练师。对战副本自动恢复 HP / PP，不影响冒险进度。':'最多选择 3 位伙伴。不选择时使用 Lv.20 示范队伍。对战副本自动恢复 HP / PP，不影响冒险进度。';$('seed').closest('label').style.display=rookie?'none':'';for(const id of ['mode','left-model','right-model']){$(id).closest('label').style.display=rookie?'none':'';$(id).disabled=rookie;if(rookie)$(id).value=id==='mode'?'manual':'baseline';}$('start-note').textContent=rookie?'带一位伙伴挑战低等级对手；不调用付费模型，战斗结束可返回伙伴冒险。':'';}
$('difficulty').onchange=updateDifficulty;
$('battle-adjust').onclick=()=>{document.body.classList.add('adjust-battle');document.querySelector('.setup').scrollIntoView({block:'start'});$('difficulty').focus({preventScroll:true});};
$('battle-again').onclick=()=>{$('start').click();};
$('start').onclick=()=>{const teamIds=[...$('team-options').querySelectorAll('input:checked')].map(e=>e.value);if(teamIds.length>3){$('notice').textContent='最多选择 3 位伙伴。';return;}if($('difficulty').value==='rookie'&&teamIds.length!==1){$('notice').textContent='见习对战请选择一位伙伴。';return;}command('START',{mode:$('mode').value,seed:Number($('seed').value),leftModel:$('left-model').value,rightModel:$('right-model').value,teamIds,difficulty:$('difficulty').value});};
for(const [id,name] of [['pause','PAUSE'],['resume','RESUME'],['manual','MANUAL'],['cancel','CANCEL'],['recover','RECOVER']])$(id).onclick=()=>command(name);
$('replay').oninput=replay;$('download').onclick=()=>{const blob=new Blob([JSON.stringify({version:5,world:latest.world,trace:latest.trace,decisions:latest.decisions,calls:latest.calls,tokens:latest.tokens,usageIncomplete:latest.usageIncomplete},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=text('a','');a.href=url;a.download='v5-battle-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function reconnect(){if(busy)return;busy=true;if(latest)render(latest);try{if(polling)await polling;await recoverDuelConnection(client);$('notice').textContent='';render(client.view);}catch(error){$('connection').textContent=`连接失败：${error.message}`;$('notice').textContent=client.pendingRequest?'有未确认操作，请重新连接后重试；不会重复出招。':'连接暂未恢复，请稍后重新连接。';}finally{busy=false;if(client.view)render(client.view);}}
$('reconnect').onclick=reconnect;$('retry-request').onclick=reconnect;
await reconnect();setInterval(()=>{if(!busy&&client.roomId)poll();},700);
