import {mountGrowthShell,explorationControls,transientFeedback,navigationPresentation,renderNavigation} from './growth-shell.mjs';
import {mountFailureRecovery} from './failure-recovery.mjs';
import {growthEvents,mountFeedback,mountJourney,mountTouch,filterPokemon,skillPresentation} from './ui-journey.mjs';
import {pokemonCard,growthGuide,renderAgentPanel} from './game-ui.mjs';
import {portraitUrl,pokemonNames} from './pokemon-art.mjs';
import {AgentClient} from './client.mjs';
import {mountGrowth} from './growth-scene.mjs';
import {regionNames,moveNames,reasonNames,manualAllowed,selectedTarget,skillEnabled,trainingConfig,growthTargetId,growthTargetHint,adventurePresentation,adventureNextStep,recoveryNeed,createRecoveryRunner,respawnHint} from './growth-view.mjs';
const client=new AgentClient(undefined,undefined,'/api/growth');let clientFailure='',busy=false,polling=false,targetId=null,last='',goalEdited=false,trainingRegionEdited=false;
const $=id=>document.getElementById(id),message=code=>reasonNames[code]??code;
const button=(label,action,enabled=false)=>{const b=document.createElement('button');b.textContent=label;if(['↑','←','↓','→'].includes(label)){b.className='direction';b.setAttribute('aria-label','伙伴向'+({'↑':'北','←':'西','↓':'南','→':'东'})[label]);}b.disabled=!enabled;b.addEventListener('click',action);return b;};
let feedbackTimer;const feedback=text=>{clearTimeout(feedbackTimer);$('feedback').textContent=text;$('feedback').hidden=!text;if(transientFeedback(text))feedbackTimer=setTimeout(()=>$('feedback').hidden=true,4000);};
async function command(kind,params={}){if(busy||autoReturn.running)return;busy=true;render();try{const ack=await client.command(kind,params);feedback(message(ack.reasonCode));await client.poll();}catch(e){if(e.message==='REQUEST_LIMIT')clientFailure=e.message;feedback(message(e.message));if(e.message==='STALE_REVISION')try{await client.poll();}catch{} }finally{busy=false;render();}}
const autoReturn=createRecoveryRunner({onChange:()=>{last='';},step:async action=>{busy=true;render();try{await client.command(action==='rest'?'REST':'MANUAL',action==='rest'?{}:{action,arguments:{}});await client.poll();if(client.view.status==='STORAGE_ERROR')throw new Error('STORAGE_UNAVAILABLE');}finally{busy=false;}}});
async function recoveryTick(){await autoReturn.tick(client.view,{online:client.connected,busy,pending:Boolean(client.pendingRequest)});render();}
const manual=(action,args={})=>command('MANUAL',{action,arguments:args});
const shell=mountGrowthShell();
let previousView=null;const events=mountFeedback($('event-feedback')),journey=mountJourney($('journey-host'),'growth'),touch=mountTouch($('touch-pad'),direction=>manual('move',{direction}));
const recovery=mountFailureRecovery($('failure-recovery'),kind=>{if(['RECONNECT','RETRY_PENDING'].includes(kind))connect();else if(kind==='RETURN_LAB')manual('go_to_region',{regionId:'lab'});else if(kind==='GROWTH_CONFIG'){shell.open('panel-ai');$('goal-level').focus();$('ai-title').scrollIntoView({block:'center'});}else if(kind==='SHOW_TRACE'){shell.open('panel-adventure');const d=$('trace').closest('details');if(d)d.open=true;$('trace').scrollIntoView({block:'center'});}else command(kind);});
const field=mountGrowth($('map'),{onTarget:id=>{targetId=id;last='';render();},onMove:direction=>manual('move',{direction}),canMove:()=>!shell.isOpen()&&manualAllowed(client.view,client.connected,busy||autoReturn.running,client.pendingRequest)});
shell.attachMapInfo();$('feedback').hidden=true;
$('collision-overlay').addEventListener('change',()=>field.setCollisionVisible($('collision-overlay').checked));
function options(select,items,empty){const current=select.value;select.replaceChildren();if(empty){const o=document.createElement('option');o.value='';o.textContent=empty;select.append(o);}for(const item of items){const o=document.createElement('option');o.value=item;o.textContent=moveNames[item]??regionNames[item]??item;select.append(o);}if([...select.options].some(o=>o.value===current))select.value=current;}
function render(){const v=client.view;shell.update(v,client.connected,busy,Boolean(client.pendingRequest));$('retry-growth').hidden=!client.pendingRequest;$('retry-growth').disabled=busy;$('reconnect').disabled=busy;$('connection').textContent=client.connected?(v?.storage==='PERSISTENT'?'已连接 · 自动存档':'已连接 · 内存模式'):'连接中断／等待连接';recovery.update({...v,clientError:clientFailure},'growth',client.connected,busy,Boolean(client.pendingRequest));if(!v)return;autoReturn.update(v,{online:client.connected,busy,pending:Boolean(client.pendingRequest)});const w=v.world,p=w.partner,allowed=manualAllowed(v,client.connected,busy||autoReturn.running,client.pendingRequest),lab=w.region==='lab';
 journey.update(v);touch.update(()=>allowed&&!!p);events.show(growthEvents(previousView,v));previousView=v;
 $('wild-refresh').textContent=respawnHint(w);targetId=growthTargetId(v,targetId);field.update(w,targetId);if($('map').dataset.state==='ERROR')feedback($('map-status').textContent);const key=JSON.stringify([v.revision,client.connected,busy,targetId,Boolean(client.pendingRequest),autoReturn.running,autoReturn.reason,autoReturn.steps]);if(key===last)return;last=key;
 $('starter').replaceChildren(...(w.starterAvailable!==false&&!p?[['TREECKO','木守宫 · 草'],['MUDKIP','水跃鱼 · 水'],['TORCHIC','火稚鸡 · 火']].map(([species,label])=>{const card=document.createElement('div');card.className='starter-card';const img=document.createElement('img');img.src=portraitUrl(species);img.alt=pokemonNames[species];card.append(img,button('选择'+label,()=>command('STARTER',{species}),allowed));return card;}):[]));
 const partnerDetailsOpen=$('partner').querySelector('details')?.open??false;
 $('partner').replaceChildren();if(p){const card=pokemonCard(p,{selected:true}),experienceNote=shell.decoratePartner(card,p);$('partner').append(card);const details=document.createElement('details');details.className='partner-details';details.open=partnerDetailsOpen;const summary=document.createElement('summary');summary.textContent='能力、性格与进化';const stats=document.createElement('p');stats.textContent='HP / 攻击 / 防御 / 特攻 / 特防 / 速度：'+p.stats.join(' / ')+(p.traits?' · 性格 '+({HARDY:'勤奋',ADAMANT:'固执',MODEST:'内敛',JOLLY:'爽朗',BOLD:'大胆'})[p.traits.nature]+' · EV '+p.traits.ev.join('/')+' · 特性 '+({OVERGROW:'茂盛',BLAZE:'猛火',TORRENT:'激流',KEEN_EYE:'锐利目光',STATIC:'静电',NONE:'无'})[p.ability]:'');details.append(summary,stats);if(experienceNote)details.append(experienceNote);if(p.evolutionSpecies){const preview=document.createElement('div');preview.className='evolution-preview';const img=document.createElement('img');img.src=portraitUrl(p.evolutionSpecies);img.alt=pokemonNames[p.evolutionSpecies];const text=document.createElement('span');text.textContent='Lv.'+p.evolutionLevel+' 自动进化 → '+pokemonNames[p.evolutionSpecies];preview.append(img,text);details.append(preview);}$('partner').append(details);}else{const text=document.createElement('p');text.className='empty-state';text.textContent=w.starterAvailable===false?'伙伴已带回委托地图。可以在下方接回继续培养。':'三位伙伴，从这里开启你的冒险。';$('partner').append(text);}
 const guide=growthGuide(v,client.connected,selectedTarget(w,targetId));$('guide-title').textContent=guide.title;$('guide-detail').textContent=guide.detail;$('region-title').textContent=regionNames[w.region]??'冒险地图';
 const returnHost=$('return-recovery'),need=recoveryNeed(v);returnHost.hidden=!need&&!autoReturn.running&&!autoReturn.reason;returnHost.replaceChildren();if(!returnHost.hidden){const title=document.createElement('strong'),detail=document.createElement('p');title.textContent=autoReturn.running?'正在返回恢复点':need==='FAINTED'?'伙伴需要恢复':need==='LOW'?'伙伴体力偏低':'恢复状态';detail.textContent=autoReturn.running?(w.canRest?'已抵达，正在恢复全队 HP / PP':'正在沿地图路线自动返程 · 已走 '+autoReturn.steps+' 步'):(autoReturn.reason?message(autoReturn.reason):['RUNNING','REPLANNING'].includes(v.status)?'AI 培养期间由委托负责恢复；暂停后可手动返回。':'一键返回当前区域恢复点，抵达后恢复全队 HP / PP。');returnHost.append(title,detail);returnHost.append(autoReturn.running?button('取消自动返程',()=>{autoReturn.cancel();render();},true):button('一键返回并恢复',()=>{autoReturn.start(v,{online:client.connected,busy,pending:Boolean(client.pendingRequest)});render();recoveryTick();},allowed&&!!p));}
 const a=w.adventure;if(a){const context={online:client.connected,busy:busy||autoReturn.running,pending:Boolean(client.pendingRequest)},presentation=adventurePresentation(v,context),next=adventureNextStep(v,context),header=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('p');header.className='adventure-summary'+(next?' active':'');header.setAttribute('role','status');header.setAttribute('aria-live','polite');title.textContent=next?'✓ '+next.title:'开启你的连续冒险';detail.textContent=next?next.detail:presentation.detail;header.append(title,detail);
 if(next?.action){const n=next.action;header.append(button(n.label,()=>{if(n.kind==='TRAVEL')manual('go_to_region',{regionId:n.regionId});else{const node=$(n.kind==='PARTNER'?'partner-title':'targets');if(n.kind!=='PARTNER')node.closest('details').open=true;node.scrollIntoView({block:'center',behavior:'smooth'});}},n.enabled));if(!n.enabled){const reason=document.createElement('p');reason.className='adventure-blocker';reason.textContent=next.reason;header.append(reason);}}
 const actions=document.createElement('div');actions.className='adventure-actions';
 if(!next){const item=document.createElement('div'),reason=document.createElement('small'),start=button(presentation.start.label,()=>command('START_ADVENTURE'),presentation.start.enabled);reason.textContent=presentation.start.reason;reason.id='adventure-start-reason';start.setAttribute('aria-describedby',reason.id);item.className='adventure-action';item.append(start,reason);header.append(item);}
 for(const [index,control] of presentation.rewards.entries()){const item=document.createElement('div'),reason=document.createElement('small'),heading=document.createElement('strong'),badge=document.createElement('span');item.className='adventure-action adventure-quest'+(control.claimed?' claimed':control.ready?' ready':'');heading.textContent=control.label;badge.className='adventure-badge';badge.textContent=control.claimed?'已领取':control.ready?'待领取':control.id==='DEX_THREE'?'收集中':!a.enabled?'待开启':w.regions?.find(r=>r.id===control.id.substring(10).toLowerCase())?.unlocked===false?'待解锁':'调查中';reason.id='adventure-reason-'+index;reason.textContent=control.reason;item.append(badge,heading,reason);if(control.ready&&!control.claimed){const action=button('领取奖励 +'+control.reward+' EXP',()=>command('CLAIM',{milestoneId:control.id}),control.enabled);action.setAttribute('aria-describedby',reason.id);item.append(action);}actions.append(item);}$('adventure').replaceChildren(header,actions);$('dex-count').textContent='图鉴 · 发现 '+a.seen.length+'/21 · 收集 '+a.caught.length+'/21';$('dex').replaceChildren(...a.dex.filter(e=>$('dex-filter').value==='all'||($('dex-filter').value==='seen'?e.seen:e.caught)).map(e=>{const card=document.createElement('div');card.className='dex-entry'+(e.seen?'':' unknown');if(e.seen){const img=document.createElement('img');img.src=portraitUrl(e.species);img.alt=e.name;card.append(img);}const name=document.createElement('span');name.textContent=e.seen?e.name+(e.caught?' ✓':' · 已见'):'未发现';card.append(name);if(e.seen){const action=button('查看 '+e.name,()=>{$('dex-detail').textContent=e.name+' · '+(e.caught?'已收集，可在队伍或收藏管理个体。':'已发现，还未收集；在野外接近并尝试捕捉。');},true);card.append(action);}return card;}));}
 $('return-growth').replaceChildren(...(v.collection??[]).map(e=>button((e.growth?'返回培养 ':'迁移为 Lv.5 ')+pokemonNames[e.species]+' · HP '+e.hp+'/'+e.maxHp,()=>command('RETURN_GROWTH',{captureId:e.captureId}),allowed&&lab&&e.state==='IN_BALL'&&v.collectionAvailable!==false)));
 $('team').replaceChildren(...filterPokemon(w.team,$('team-search').value).filter(e=>e.captureId!==p?.captureId).map(e=>{const item=document.createElement('div');item.className='team-item';item.append(pokemonCard(e,{compact:true}),button('切换为出战伙伴',()=>command('SELECT',{captureId:e.captureId}),allowed&&lab));return item;}));
 const navigation=navigationPresentation(v,{online:client.connected,busy,pending:Boolean(client.pendingRequest),returning:autoReturn.running});$('navigation-current').textContent='当前位置：'+navigation.current;renderNavigation($('travel'),navigation,regionId=>manual('go_to_region',{regionId}),()=>manual('go_to_recovery'));

 const target=selectedTarget(w,targetId);$('target-name').textContent=target?target.name+' Lv.'+target.level+' · HP '+target.hp+'/'+target.maxHp+(target.targetAdjacent?' · 已接近':' · 尚未接近'):growthTargetHint(v);
 $('targets').replaceChildren(...w.encounters.filter(e=>w.region!=='lab'&&(!e.region||e.region===w.region)).map(e=>{const c=document.createElement('div');c.className='card'+(e.id===targetId?' selected':'');const img=document.createElement('img');img.src=portraitUrl(e.species);img.alt=e.name;const text=document.createElement('p');text.textContent=e.name+' Lv.'+e.level+' · '+({WILD:'野生',CAPTURED:'已捕捉',DEFEATED:'已击败',TRANSFERRED:'已带回原地图'})[e.state];c.append(img,text);if(e.state==='WILD')c.append(button(e.id===targetId?'当前目标':'选择目标',()=>{targetId=e.id;last='';render();},lab===false));return c;}));
 $('skills').replaceChildren(...(p?.moves??[]).map(m=>{const b=button(m.name,()=>manual('use_skill',{targetId,moveId:m.id}),allowed&&skillEnabled(w,target,m)),info=skillPresentation(m),name=document.createElement('strong'),type=document.createElement('span'),detail=document.createElement('small');b.className='skill-card';b.dataset.type=info.tone;name.textContent=m.name;type.className='type-badge';type.textContent=info.type;detail.textContent='PP '+m.pp+' / '+m.maxPp;b.replaceChildren(name,type,detail);b.title=info.detail+' · '+(!target?'请先选择目标':!target.targetAdjacent?'接近到相邻格后才能使用':m.pp<=0?'PP 已耗尽，请恢复':'使用此技能，推进一回合');return b;}));
 const visible=explorationControls(target);$('skills').hidden=!visible.skills;$('capture').hidden=!visible.capture;$('capture').replaceChildren(...(visible.approach?[button('接近目标',()=>manual('move_to',{targetId}),allowed&&!lab)]:[]),...(visible.capture?[button('捕捉',()=>manual('capture',{targetId}),allowed&&target.targetAdjacent&&!lab&&p?.hp>0)]:[]));
 $('skill-info').replaceChildren(...(p?.moves??[]).map(m=>{const row=document.createElement('p');row.textContent=m.name+' · '+skillPresentation(m).type+' · '+skillPresentation(m).detail;return row;}));
 $('lab').replaceChildren(button('带回原地图（移出成长队伍）',()=>command('CARRY'),allowed&&lab&&!!p&&p.hp>0&&v.collectionAvailable!==false),button('全队恢复',()=>command('REST'),allowed&&w.canRest&&!!p),button('开始下一轮探索',()=>command('NEXT_EXPEDITION'),allowed&&lab&&!!p&&w.encounters.every(e=>e.state!=='WILD')));
 options($('learn-move'),(p?.availableMoves??[]).filter(m=>!(m in p.pp)),'选择技能');options($('replace-move'),Object.keys(p?.pp??{}),'有空位时无需替换');$('learn').disabled=!allowed||!lab||!p||!$('learn-move').value||(Object.keys(p.pp).length>=4&&!$('replace-move').value);$('learn-preview').textContent=!p?'先选择伙伴':!lab?'返回研究室后才能学习技能':!$('learn-move').value?'选择可学习技能；四个技能已满时需要指定替换。':Object.keys(p.pp).length>=4?'已装备四个技能，请指定替换；学习后原技能将被移除。':'有空位，可以直接学习；学习后不会自动攻击。';$('learn-move').disabled=!allowed||!lab||!p;$('replace-move').disabled=!allowed||!lab||!p;
 $('milestones').replaceChildren(...w.milestones.map(m=>button(({FIRST_CAPTURE:'首次捕捉',FIRST_CLEAR:'完成探索',FIRST_EVOLUTION:'首次进化'})[m.id]+(m.claimed?' · 已领取':' +'+m.reward+' EXP'),()=>command('CLAIM',{milestoneId:m.id}),allowed&&lab&&m.ready&&!m.claimed)));
 const training=trainingConfig(v,{region:trainingRegionEdited?$('training-region').value:w.expeditionRegion??'forest',level:goalEdited?Number($('goal-level').value):Math.min(p?.levelCap??40,(p?.level??5)+1)});options($('training-region'),(w.regions??[]).filter(e=>e.id!=='lab'&&e.unlocked!==false).map(e=>e.id));if(training.retained||!trainingRegionEdited)$('training-region').value=training.region;$('training-region').disabled=!allowed;
 $('ai').replaceChildren(button('委托 AI 培养',()=>command('AI_TRAIN',{targetLevel:Number($('goal-level').value),regionId:$('training-region').value}),allowed&&!!p&&v.aiAvailable&&p.level<p.levelCap),button('暂停',()=>command('PAUSE'),client.connected&&!busy&&!client.pendingRequest&&['RUNNING','REPLANNING'].includes(v.status)),button('继续委托',()=>command('RESUME'),client.connected&&!busy&&!client.pendingRequest&&['PAUSED','PROVIDER_UNAVAILABLE'].includes(v.status)),button('取消委托',()=>command('CANCEL'),client.connected&&!busy&&['RUNNING','REPLANNING','PAUSED','PROVIDER_UNAVAILABLE'].includes(v.status)),button('恢复存档',()=>command('RECOVER'),client.connected&&!busy&&v.status==='STORAGE_ERROR'));
 renderAgentPanel($('growth-agent-panel'),v,client.connected,busy);$('ai-status').textContent=v.errorCode?message(v.errorCode):v.recovered?'进度已从存档恢复；未完成的委托需手动继续。':'';$('ai-model').textContent='模型 '+v.model+' · '+v.provider+' · '+(v.aiAvailable?'已配置':'未配置，仍可手动试玩');if(p&&(training.retained||!goalEdited))$('goal-level').value=training.level;$('goal-level').disabled=!allowed;if(p){$('goal-level').max=p.levelCap;$('goal-level').min=training.retained?training.level:Math.min(p.levelCap,p.level+1);}
 $('trace').replaceChildren(...v.trace.slice(-12).reverse().map(row=>{const li=document.createElement('li');const d=row.data??{};li.textContent=message(row.code)+(d.experienceGained?' · EXP +'+d.experienceGained:'')+(d.damage?' · 伤害 '+d.damage:'');return li;}));
}
for(const id of ['team-search','dex-filter','learn-move','replace-move'])$(id).addEventListener(id==='team-search'?'input':'change',()=>{last='';render();});
window.addEventListener('pagehide',()=>{clearTimeout(feedbackTimer);autoReturn.cancel();events.destroy();});
$('training-region').addEventListener('change',()=>trainingRegionEdited=true);
$('goal-level').addEventListener('input',()=>goalEdited=true);$('learn').addEventListener('click',()=>{const moveId=$('learn-move').value;if(!moveId){feedback('请选择要学习的技能');return;}command('LEARN',{moveId,replaceId:$('replace-move').value||null});});
async function connect(){if(busy)return;busy=true;render();try{await client.connect();clientFailure='';if(client.pendingRequest){await client.retry();await client.poll();}feedback('成长模式已连接，进度以服务器存档为准');}catch(e){if(e.message==='REQUEST_LIMIT')clientFailure=e.message;feedback(message(e.message));}finally{busy=false;last='';render();}}
$('retry-growth').addEventListener('click',connect);$('reconnect').addEventListener('click',connect);await connect();setInterval(async()=>{if(polling||busy||!client.roomId)return;polling=true;try{await client.poll();}catch(e){if(e.message==='REQUEST_LIMIT')clientFailure=e.message;feedback(message(e.message));}finally{polling=false;render();await recoveryTick();}},700);
