package game.agent.growth;
import game.actors.pokemon.Pokemon;import edu.monash.fit2099.engine.actions.*;import edu.monash.fit2099.engine.displays.Display;import edu.monash.fit2099.engine.positions.GameMap;import edu.monash.fit2099.engine.weapons.IntrinsicWeapon;import game.agent.llm.Json;import java.util.*;import java.math.BigDecimal;
/** Actual native Actor with persistent RSE-reference progression and equipped PP. */
public final class GrowthPokemon extends Pokemon {
 public final String captureId;public String species;public int experience;public final LinkedHashMap<String,Integer> pp=new LinkedHashMap<>();public boolean burned;public String nature="HARDY",status="NONE";public final int[] ev=new int[6];public int sleepTurns,confusionTurns;public int attackStage,defenseStage,speedStage,accuracyStage,chain;
 public GrowthPokemon(String id,String species,int level){super(GrowthRules.species(species).name,'P',GrowthRules.stats(species,level)[0]);if(!id.matches("[a-f0-9-]{36}"))throw new IllegalArgumentException("INVALID_CAPTURE_ID");captureId=id;this.species=species;experience=GrowthRules.experienceAt(level);learnAutomatic();}
 public int level(){return GrowthRules.levelAt(experience);}public int[] stats(){return GrowthRules.stats(species,level(),nature,ev);}public int maxHp(){return stats()[0];}
 public void awardEv(String defeated){int total=0;for(int n:ev)total+=n;int i=GrowthRules.evIndex(defeated),hp=getHitPoints(),old=maxHp();if(total<510&&ev[i]<255){ev[i]++;resetMaxHp(maxHp());hurt(maxHp()-Math.min(maxHp(),hp==0?0:hp+maxHp()-old));}}
 public void assignNature(String value){if(!GrowthRules.NATURES.contains(value))throw new IllegalArgumentException("INVALID_NATURE");nature=value;int hp=getHitPoints();resetMaxHp(maxHp());hurt(maxHp()-Math.min(maxHp(),hp));}
 public List<String> availableMoves(){List<String> ids=new ArrayList<>();for(Map.Entry<String,Integer> e:GrowthRules.species(species).learn.entrySet())if(level()>=e.getValue())ids.add(e.getKey());return ids;}
 private void learnAutomatic(){for(String move:availableMoves())if(pp.size()<4&&!pp.containsKey(move))pp.put(move,GrowthRules.move(move).pp);}
 public void gainExperience(int amount){if(amount<0)throw new IllegalArgumentException("INVALID_REWARD");int old=maxHp(),hp=getHitPoints();experience=(int)Math.min(GrowthRules.experienceAt(GrowthRules.LEVEL_CAP),(long)experience+amount);resetMaxHp(maxHp());hurt(maxHp()-Math.min(maxHp(),hp==0?0:hp+maxHp()-old));learnAutomatic();}
 public String learn(String move,String replace){if(!availableMoves().contains(move))return "MOVE_NOT_LEARNABLE";if(pp.containsKey(move))return "MOVE_ALREADY_EQUIPPED";if(pp.size()>=4){if(replace==null||!pp.containsKey(replace))return "REPLACE_MOVE_REQUIRED";pp.remove(replace);}else if(replace!=null)return "INVALID_REPLACEMENT";pp.put(move,GrowthRules.move(move).pp);return "MOVE_LEARNED";}
 public String evolve(){String next=GrowthRules.species(species).evolution;if(next==null)return "NO_EVOLUTION";if(level()<GrowthRules.species(species).evolutionLevel)return "EVOLUTION_LEVEL_REQUIRED";int hp=getHitPoints(),old=maxHp();species=next;int max=maxHp();resetMaxHp(max);hurt(max-(int)((long)hp*max/old));learnAutomatic();clearBattle();return "EVOLVED";}
 public void rest(){resetMaxHp(maxHp());burned=false;status="NONE";sleepTurns=0;for(String m:pp.keySet())pp.put(m,GrowthRules.move(m).pp);clearBattle();}
 public void clearBattle(){confusionTurns=0;attackStage=defenseStage=speedStage=accuracyStage=chain=0;}
 /** Apply a validated same-individual deployed checkpoint without replacing the native Actor. */
 public void applyCheckpoint(Map<String,Object> value){GrowthPokemon restored=restore(value);if(!captureId.equals(restored.captureId))throw new IllegalArgumentException("GROWTH_ID_MISMATCH");species=restored.species;experience=restored.experience;nature=restored.nature;System.arraycopy(restored.ev,0,ev,0,6);status=restored.status;sleepTurns=restored.sleepTurns;confusionTurns=restored.confusionTurns;resetMaxHp(maxHp());hurt(maxHp()-restored.getHitPoints());pp.clear();pp.putAll(restored.pp);burned=restored.burned;attackStage=restored.attackStage;defenseStage=restored.defenseStage;speedStage=restored.speedStage;accuracyStage=restored.accuracyStage;chain=restored.chain;}
 public Map<String,Object> export(){return Json.object("captureId",captureId,"species",species,"experience",experience,"hp",Math.max(0,getHitPoints()),"pp",new LinkedHashMap<>(pp),"burned",burned,"attackStage",attackStage,"defenseStage",defenseStage,"speedStage",speedStage,"accuracyStage",accuracyStage,"chain",chain,"traits",traits());}
 private Map<String,Object> traits(){List<Integer> values=new ArrayList<>();for(int n:ev)values.add(n);return Json.object("nature",nature,"ev",values,"status",status,"sleepTurns",sleepTurns,"confusionTurns",confusionTurns);}
 public Map<String,Object> view(){Map<String,Object> v=export();v.put("ability",GrowthRules.ability(species));v.put("name",GrowthRules.species(species).name);v.put("level",level());v.put("maxHp",maxHp());List<Integer> stats=new ArrayList<>();for(int n:stats())stats.add(n);v.put("stats",stats);v.put("art",GrowthRules.species(species).art);v.put("types",Arrays.asList(GrowthRules.species(species).types));v.put("nextLevelExperience",level()==GrowthRules.LEVEL_CAP?experience:GrowthRules.experienceAt(level()+1));v.put("levelCap",GrowthRules.LEVEL_CAP);v.put("evolutionLevel",GrowthRules.species(species).evolutionLevel);v.put("evolutionSpecies",GrowthRules.species(species).evolution);v.put("evolutionAvailable",GrowthRules.species(species).evolution!=null&&level()>=GrowthRules.species(species).evolutionLevel);v.put("availableMoves",availableMoves());List<Object> moves=new ArrayList<>();for(String id:pp.keySet()){Map<String,Object> m=GrowthRules.move(id).view();m.put("pp",pp.get(id));moves.add(m);}v.put("moves",moves);return v;}
 public static GrowthPokemon restore(Map<String,Object> r){Set<String> fields=new HashSet<>(Arrays.asList("captureId","species","experience","hp","pp","burned","attackStage","defenseStage","speedStage","accuracyStage","chain"));if(r.containsKey("traits"))fields.add("traits");if(!r.keySet().equals(fields))throw new IllegalArgumentException("INVALID_GROWTH_POKEMON");int exp=num(r.get("experience"));GrowthPokemon p=new GrowthPokemon((String)r.get("captureId"),(String)r.get("species"),GrowthRules.levelAt(exp));p.experience=exp;if(r.containsKey("traits")){Map<String,Object> t=Json.asObject(r.get("traits"));if(!t.keySet().equals(new HashSet<>(Arrays.asList("nature","ev","status","sleepTurns","confusionTurns"))))throw new IllegalArgumentException("INVALID_TRAITS");p.assignNature((String)t.get("nature"));List<Object> values=Json.asArray(t.get("ev"));if(values.size()!=6)throw new IllegalArgumentException("INVALID_EV");int total=0;for(int i=0;i<6;i++){int n=num(values.get(i));if(n<0||n>255)throw new IllegalArgumentException("INVALID_EV");p.ev[i]=n;total+=n;}if(total>510)throw new IllegalArgumentException("INVALID_EV");p.status=(String)t.get("status");p.sleepTurns=bounded(t,"sleepTurns",0,3);p.confusionTurns=bounded(t,"confusionTurns",0,4);if(!Arrays.asList("NONE","POISON","PARALYSIS","SLEEP").contains(p.status)||p.status.equals("SLEEP")!=(p.sleepTurns>0)||Boolean.TRUE.equals(r.get("burned"))&&!p.status.equals("NONE"))throw new IllegalArgumentException("INVALID_STATUS");p.resetMaxHp(p.maxHp());}String predecessor=GrowthRules.predecessor(p.species);if(predecessor!=null&&p.level()<GrowthRules.species(predecessor).evolutionLevel)throw new IllegalArgumentException("INVALID_EVOLVED_LEVEL");int hp=num(r.get("hp"));if(hp<0||hp>p.maxHp()||!(r.get("burned") instanceof Boolean))throw new IllegalArgumentException("INVALID_GROWTH_POKEMON");p.hurt(p.maxHp()-hp);p.pp.clear();Map<String,Object> saved=Json.asObject(r.get("pp"));if(saved.isEmpty()||saved.size()>4)throw new IllegalArgumentException("INVALID_MOVES");for(String id:saved.keySet()){int count=num(saved.get(id));boolean retained=false;for(String base=GrowthRules.predecessor(p.species);base!=null;base=GrowthRules.predecessor(base)){Integer oldLevel=GrowthRules.species(base).learn.get(id);if(oldLevel!=null&&oldLevel<=p.level())retained=true;}if(!p.availableMoves().contains(id)&&!retained||count<0||count>GrowthRules.move(id).pp)throw new IllegalArgumentException("INVALID_MOVES");p.pp.put(id,count);}p.burned=(Boolean)r.get("burned");p.attackStage=bounded(r,"attackStage",-6,6);p.defenseStage=bounded(r,"defenseStage",-6,6);p.speedStage=bounded(r,"speedStage",-6,6);p.accuracyStage=bounded(r,"accuracyStage",-6,6);p.chain=bounded(r,"chain",0,4);return p;}
 private static int bounded(Map<String,Object> r,String k,int lo,int hi){int n=num(r.get(k));if(n<lo||n>hi)throw new IllegalArgumentException("INVALID_STAGE");return n;}
 public static int num(Object v){if(!(v instanceof Number))throw new IllegalArgumentException("INVALID_NUMBER");return new BigDecimal(v.toString()).intValueExact();}
 @Override public void toggleWeapon(boolean equip){}@Override public IntrinsicWeapon getIntrinsicWeapon(){return new IntrinsicWeapon(10,"hits");}@Override public Action playTurn(ActionList list,Action last,GameMap map,Display display){return new DoNothingAction();}
}
