import test from 'node:test';import assert from 'node:assert/strict';import {hpPercent,hint,art,results,canRetryAction,recoverDuelConnection} from '../../agent/duel-view.mjs';import {AgentClient} from '../../agent/client.mjs';
test('duel UI uses authoritative health and existing sprite assets',()=>{assert.equal(hpPercent({hp:20,maxHp:40}),50);assert.equal(hpPercent({hp:-5,maxHp:40}),0);assert.equal(art('MARSHTOMP'),'/rpg/assets/images/pokemon/sprites/marshtomp.png');assert.equal(results.LEFT_WON,'己方获胜');});
test('locked choice and forced switch explain waiting instead of promising actions',()=>{assert.match(hint({status:'RUNNING',controlMode:'manual',world:{choiceLocked:true}}),/锁定/);assert.match(hint({status:'RUNNING',controlMode:'manual',world:{activeSlot:0,ownTeam:[{hp:0}]}}),/倒下/);assert.match(hint({status:'PAUSED',errorCode:'PROVIDER_TIMEOUT'}),/PROVIDER_TIMEOUT/);});
test('duel uses same CSRF and idempotent request client',()=>{const c=new AgentClient(async()=>{},()=> 'request','/api/duel');assert.equal(c.apiBase,'/api/duel');assert.throws(()=>new AgentClient(async()=>{},()=> 'request','/api/arbitrary'),/INVALID_API_BASE/);});

test('unknown usage explains paid pause and manual recovery',()=>{assert.match(hint({status:'PAUSED',usageIncomplete:true}),/用量尚未确认/);assert.match(hint({status:'PAUSED',usageIncomplete:true}),/手动接管/);});

const actionView={taskId:'task',status:'RUNNING',controlMode:'manual',world:{round:1,activeSlot:0,canChoose:true,legalMoves:['POUND'],legalSwitches:[1]}};
test('safe stale-action retry allows unchanged pending round with still legal action',()=>{assert.equal(canRetryAction(actionView,{...actionView,revision:20},{tool:'battle_move',arguments:{moveId:'POUND'}}),true);assert.equal(canRetryAction(actionView,actionView,{tool:'battle_switch',arguments:{slot:1}}),true);});
test('stale-action retry rejects new task, advanced round and locked choice',()=>{const move={tool:'battle_move',arguments:{moveId:'POUND'}};assert.equal(canRetryAction(actionView,{...actionView,taskId:'other'},move),false);assert.equal(canRetryAction(actionView,{...actionView,world:{...actionView.world,round:2}},move),false);assert.equal(canRetryAction(actionView,{...actionView,world:{...actionView.world,canChoose:false}},move),false);});
test('stale-action retry cannot invent a skill or reserve',()=>{assert.equal(canRetryAction(actionView,actionView,{tool:'battle_move',arguments:{moveId:'WATER_GUN'}}),false);assert.equal(canRetryAction(actionView,actionView,{tool:'battle_switch',arguments:{slot:2}}),false);});

test('duel reconnect resends original pending request then refreshes authoritative state',async()=>{const calls=[],client={pendingRequest:{body:'original'},async connect(){calls.push('connect');},async retry(){calls.push('retry-original');this.pendingRequest=null;},async poll(){calls.push('poll');},view:{revision:8}};assert.equal(await recoverDuelConnection(client),client.view);assert.deepEqual(calls,['connect','retry-original','poll']);});
test('duel reconnect never replays a request discarded after room replacement',async()=>{const calls=[],client={pendingRequest:{body:'old'},async connect(){calls.push('connect');this.pendingRequest=null;this.view={taskId:'new'};},async retry(){calls.push('unsafe');}};assert.equal((await recoverDuelConnection(client)).taskId,'new');assert.deepEqual(calls,['connect']);});
test('duel recovery leaves uncertain request available when transport is still down',async()=>{const pending={body:'original'},client={pendingRequest:pending,async connect(){throw new Error('offline');}};await assert.rejects(recoverDuelConnection(client),/offline/);assert.equal(client.pendingRequest,pending);});
