import test from 'node:test';import assert from 'node:assert/strict';import {postAdventureGoals} from '../../agent/post-adventure.mjs';
test('goals use original individual and persisted victories, not selected partner',()=>{const v={firstAdventure:{stage:'COMPLETE',starterId:'original',species:'TREECKO',rookieWon:false},world:{team:[{captureId:'original',species:'GROVYLE',level:18},{captureId:'other',species:'MUDKIP',level:5}],partner:{captureId:'other'},adventure:{cleared:['forest','river','mountain']}}};let g=postAdventureGoals(v);assert.equal(g.primary.id,'rookie');assert.equal(g.items.find(x=>x.id==='evolution').done,true);assert.equal(g.items.find(x=>x.id==='survey').done,true);v.firstAdventure.rookieWon=true;g=postAdventureGoals(v);assert.equal(g.primary.id,'trainer');});

test('legacy save has achievable goals without inventing an original individual',()=>{const g=postAdventureGoals({firstAdventure:{stage:'SKIPPED'},world:{partner:{captureId:'legacy'},milestones:[{id:'FIRST_EVOLUTION',claimed:true}],adventure:{cleared:[]}}});assert.equal(g.items.some(x=>x.id==='rookie'),false);assert.equal(g.items.find(x=>x.id==='evolution').done,true);assert.equal(g.primary.id,'survey');});

test('next goals expose actual level, survey count and a concrete next step',()=>{const g=postAdventureGoals({firstAdventure:{stage:'COMPLETE',starterId:'first',species:'TREECKO',rookieWon:true},world:{team:[{captureId:'first',species:'TREECKO',level:12,evolutionLevel:16}],adventure:{cleared:['forest']}}});assert.equal(g.primary.progress,'Lv.12 / Lv.16');assert.match(g.primary.next,/16/);const survey=g.items.find(x=>x.id==='survey');assert.equal(survey.progress,'1 / 3 区域');assert.match(survey.next,/浅溪河岸/);});
test('missing original is explained instead of recommending an unavailable duel',()=>{const g=postAdventureGoals({firstAdventure:{stage:'COMPLETE',starterId:'missing',species:'TREECKO'},world:{team:[]}});assert.match(g.primary.next,/接回/);assert.equal(g.primary.href,'/growth/#team');});

test('survey explains continuous adventure prerequisite before region navigation',()=>{const g=postAdventureGoals({firstAdventure:{stage:'SKIPPED'},world:{milestones:[{id:'FIRST_EVOLUTION',claimed:true}],adventure:{enabled:false,cleared:[]}}});assert.match(g.primary.next,/开启连续冒险/);assert.equal(g.primary.href,'/growth/#adventure');});
