import test from 'node:test';import assert from 'node:assert/strict';
import {growthEvents,journeySteps,filterPokemon,skillPresentation} from '../../agent/ui-journey.mjs';
const p={captureId:'one',species:'TREECKO',level:5,hp:19,moves:[{id:'POUND',name:'拍击',type:'NORMAL',pp:35,maxPp:35,power:40,accuracy:100}]};
const view=(partner=p,turn=0,encounters=[])=>({status:'IDLE',world:{partner,team:[partner],turn,region:'forest',encounters}});
test('feedback ignores initial/repeated/reversed snapshots and changed partner',()=>{assert.deepEqual(growthEvents(null,view()),[]);assert.deepEqual(growthEvents(view(),view()),[]);assert.deepEqual(growthEvents(view(p,4),view({...p,level:6},3)),[]);assert.deepEqual(growthEvents(view(),view({...p,captureId:'two',level:7},1)),[]);});
test('level evolution and learned skill use same individual actual changes',()=>{const next={...p,level:16,species:'GROVYLE',moves:[...p.moves,{id:'ABSORB',name:'吸取'}]};const e=growthEvents(view(),view(next,1));assert.deepEqual(e.map(x=>x.kind),['evolution','learn']);assert.match(e[0].detail,/16/);});
test('capture only follows encounter committed WILD to CAPTURED',()=>{const before=view(p,2,[{id:'a',state:'WILD',species:'MUDKIP',name:'水跃鱼'}]);assert.equal(growthEvents(before,view(p,3,[{id:'a',state:'CAPTURED',species:'MUDKIP',name:'水跃鱼'}]))[0].kind,'capture');assert.deepEqual(growthEvents(before,view(p,3,[{id:'new',state:'CAPTURED'}])),[]);});
test('skill feedback derives PP spend rather than hp damage or mere polling',()=>{const next={...p,moves:[{...p.moves[0],pp:34}]};assert.equal(growthEvents(view(p,2),view(next,3))[0].kind,'skill');assert.deepEqual(growthEvents(view(p,2),view({...p,hp:17},3)),[]);});
test('tutorial keeps capture incomplete when only starter is owned and AI manual fallback honest',()=>{const steps=journeySteps(view());assert.equal(steps.find(x=>x.id==='capture').done,false);assert.equal(steps.find(x=>x.id==='delegate').done,false);assert.match(steps.find(x=>x.id==='delegate').detail,/手动/);assert.equal(journeySteps({...view(),status:'COMPLETED'}).find(x=>x.id==='delegate').done,true);});
test('search and state filter never mutate owned list or unknown dex names',()=>{const list=[{species:'TREECKO',state:'IN_BALL'},{species:'MUDKIP',state:'DEPLOYED'}];assert.equal(filterPokemon(list,'木守', 'IN_BALL').length,1);assert.equal(filterPokemon(list,'','DEPLOYED')[0].species,'MUDKIP');assert.equal(list.length,2);});
test('skill cards use provided numeric values and effect metadata',()=>{assert.deepEqual(skillPresentation(p.moves[0]),{type:'一般',tone:'normal',detail:'威力 40 · 命中 100% · PP 35 / 35'});assert.match(skillPresentation({type:'GRASS',power:0,accuracy:100,pp:0,maxPp:40}).detail,/变化/);});

test('level and evolution coalesce for same identity; task change does not replay',()=>{const before={taskId:'same',world:{turn:1,partner:{captureId:'a',species:'TREECKO',level:15,moves:[]},encounters:[]}},after={taskId:'same',world:{turn:2,partner:{captureId:'a',species:'GROVYLE',level:16,moves:[]},encounters:[]}};const events=growthEvents(before,after);assert.equal(events.filter(e=>['level','evolution'].includes(e.kind)).length,1);assert.equal(events[0].kind,'evolution');assert.equal(growthEvents(before,{...after,taskId:'new'}).length,0);});
