package game.agent.web;
import game.agent.duel.DuelBattle;import game.agent.runtime.AgentLoop;import game.agent.llm.*;import game.agent.eval.*;import game.agent.persistence.*;import java.util.*;import java.nio.file.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicLong;
public class V5LiveAcceptance {
 static final AtomicLong total=new AtomicLong();
 static final java.util.concurrent.atomic.AtomicBoolean usageUncertain=new java.util.concurrent.atomic.AtomicBoolean();
 static Map<String,Object> request(DuelRoom r,String c,Map<String,Object> params){return Json.object("requestId",UUID.randomUUID().toString(),"taskId",r.snapshot().get("taskId"),"expectedRevision",r.snapshot().get("revision"),"command",c,"params",params);}
 static Map<String,Object> safePartner(Map<String,Object> raw,boolean own){Map<String,Object> safe=new LinkedHashMap<>();for(String field:Arrays.asList("species","level","hp","maxHp"))safe.put(field,raw.get(field));if(own){List<Object> moves=new ArrayList<>();for(Object item:Json.asArray(raw.get("moves"))){Map<String,Object> move=Json.asObject(item);moves.add(Json.object("id",move.get("id"),"pp",move.get("pp")));}safe.put("moves",moves);}return safe;}
 static AgentLoop.Context outbound(AgentLoop.Context source){Map<String,String> raw=source.getObservation(),safe=new LinkedHashMap<>();for(String field:Arrays.asList("round","activeSlot","legalMoves","legalSwitches","forcedSwitch"))safe.put(field,raw.get(field));List<Object> own=new ArrayList<>();for(Object row:Json.asArray(Json.read(raw.get("ownTeam"))))own.add(safePartner(Json.asObject(row),true));safe.put("ownTeam",Json.write(own));safe.put("opponentActive",Json.write(safePartner(Json.asObject(Json.read(raw.get("opponentActive"))),false)));return AgentLoop.Context.snapshot("Choose exactly one legal battle move or switch. Win the singles battle. Use the listed legal actions only.",safe,source.getTools(),null);}
 public static void main(String[] args)throws Exception{
  if(args.length>0&&args[0].equals("--verify-payload")){DuelBattle battle=new DuelBattle(DuelBattle.demoTeam(),DuelBattle.demoTeam(),11);AgentLoop.Context safe=outbound(AgentLoop.Context.snapshot("probe",battle.observation(0),battle.tools(0),null));String payload=Json.write(safe.getObservation());for(String banned:Arrays.asList("captureId","traits","experience","art","nature","ev","taskId","owner"))if(payload.contains("\""+banned+"\""))throw new IllegalStateException("UNAUTHORIZED_METADATA");System.out.println(payload);return;}
  Map<String,String> env=new HashMap<>(System.getenv());env.put("LLM_PROVIDER","openai");env.put("OPENAI_MODEL","gpt-6-luna");ProviderSelection live=ProviderSelection.fromEnvironment(env);if(live.gateway==null)throw new IllegalStateException("LIVE_CONFIGURATION_UNAVAILABLE");
  LlmGateway guarded=new LlmGateway(){public game.agent.tools.ToolRequest decide(AgentLoop.Context c){if(usageUncertain.get()||total.get()>=350000)throw new ProviderException(ProviderException.Code.BUDGET_EXHAUSTED);try{game.agent.tools.ToolRequest r=live.gateway.decide(outbound(c));Map<String,Number> usage=live.gateway.getUsage();Number tokens=usage.get("totalTokens");if(tokens==null||tokens.longValue()<0){usageUncertain.set(true);throw new ProviderException(ProviderException.Code.UNAVAILABLE);}total.addAndGet(tokens.longValue());return r;}catch(RuntimeException failure){usageUncertain.set(true);throw failure;}}public Map<String,Number> getUsage(){return live.gateway.getUsage();}};
  ProviderSelection provider=new ProviderSelection("openai",live.model,live.timeoutMillis,guarded,null);ExecutorService executor=Executors.newFixedThreadPool(2);Path output=Paths.get(args[0]);Files.createDirectories(output);
  try{for(String mode:Arrays.asList("manual","delegated","auto")){
   if(usageUncertain.get()||total.get()>=350000){System.out.println(mode+": SKIPPED acceptance budget or usage uncertain");break;}
   try(WorldStore store=new FileWorldStore(output.resolve("saves-"+mode))){DuelRoom room=new DuelRoom("live-"+mode,provider,new EvaluationProviders(Collections.singletonList("baseline"),1000,m->DuelRoom::baseline),executor,store,Collections::emptyList);
    Map<String,Object> configuration=Json.object("mode",mode,"seed",11,"leftModel",mode.equals("manual")?"baseline":live.model,"rightModel",mode.equals("delegated")?"baseline":live.model,"teamIds",Collections.emptyList());if(room.command(request(room,"START",configuration),0).status!=200)throw new IllegalStateException("START_FAILED");long start=System.nanoTime();
    while(room.snapshot().get("status").equals("RUNNING")&&(System.nanoTime()-start)/1000000<180000){long now=System.nanoTime()/1000000;Map<String,Object> snapshot=room.snapshot(),world=Json.asObject(snapshot.get("world"));if(mode.equals("manual")&&Boolean.TRUE.equals(world.get("canChoose"))){Map<String,String> observation=new LinkedHashMap<>();observation.put("ownTeam",Json.write(world.get("ownTeam")));observation.put("activeSlot",world.get("activeSlot").toString());observation.put("opponentActive",Json.write(world.get("opponentActive")));observation.put("legalMoves",Json.write(world.get("legalMoves")));observation.put("legalSwitches",Json.write(world.get("legalSwitches")));Map<String,Object> own=Json.asObject(Json.asArray(world.get("ownTeam")).get(((Number)world.get("activeSlot")).intValue()));observation.put("forcedSwitch",String.valueOf(((Number)own.get("hp")).intValue()==0));game.agent.tools.ToolRequest action=DuelRoom.baseline(AgentLoop.Context.snapshot("manual acceptance driver",observation,Collections.emptyList(),null));room.command(request(room,"ACTION",Json.object("tool",action.getName(),"arguments",action.getArguments())),now);}room.tick(now);Thread.sleep(30);}
    if(room.snapshot().get("status").equals("RUNNING"))room.command(request(room,"PAUSE",Collections.emptyMap()),System.nanoTime()/1000000);Map<String,Object> result=new LinkedHashMap<>(room.snapshot());result.put("realAi",true);result.put("manualDriver",mode.equals("manual")?"explicit HTTP-equivalent rule choices, not a human skill measurement":null);result.put("elapsedMs",(System.nanoTime()-start)/1000000);result.put("totalAcceptanceTokens",total.get());Files.write(output.resolve(mode+".json"),Json.write(result).getBytes(java.nio.charset.StandardCharsets.UTF_8));System.out.println(mode+": "+result.get("status")+" "+Json.asObject(result.get("world")).get("result")+" tokens="+result.get("tokens")+" calls="+result.get("calls"));room.close();if(Boolean.TRUE.equals(result.get("usageIncomplete")))usageUncertain.set(true);
   }
  }}finally{executor.shutdownNow();}
 }
}
